#!/usr/bin/env python3
import sys
from collections import deque


def solve(Q: int, T: "List[int]", X: "List[int]"):

    d = deque()

    for t, x in zip(T, X):
        if t == 1:
            d.appendleft(x)
        elif t == 2:
            d.append(x)
        else:
            print(d[x - 1])


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    Q = int(next(tokens))  # type: int
    t = [int()] * (Q)  # type: "List[int]"
    x = [int()] * (Q)  # type: "List[int]"
    for i in range(Q):
        t[i] = int(next(tokens))
        x[i] = int(next(tokens))
    solve(Q, t, x)

if __name__ == '__main__':
    main()
