#!/usr/bin/env python3
import sys
from collections import defaultdict
import heapq
INF = float('inf')  # type: float


def solve(N: int, K: int, A: "List[int]"):

    use_set = set()
    ans_list = []

    h = [0]

    while len(ans_list) <= K:
        v = heapq.heappop(h)
        ans_list.append(v)
        for a in A:
            n = v + a
            if n not in use_set:
                use_set.add(n)
                heapq.heappush(h, n)

    print(ans_list[K])



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, K, A)

if __name__ == '__main__':
    main()
