#!/usr/bin/env python3
import sys
from collections import defaultdict
INF = float('inf')  # type: float

from heapq import heappop, heappush


def solve(N: int, A: "List[int]"):

    que = []
    stocks = [[INF, INF, INF] for _ in range(N)]
    cnts = [0] * N

    for i, a in enumerate(A):
        a -= 1
        stocks[a][cnts[a]] = i
        cnts[a] += 1
        if cnts[a] == 3:
            heappush(que, (stocks[a][1], a))

    ans_list = []
    while que:
        _, a = heappop(que)

        ans_list.append(a + 1)

    print(*ans_list)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(3 * N)]  # type: "List[int]"
    solve(N, A)

if __name__ == '__main__':
    main()
