#!/usr/bin/env python3
import sys


from collections import defaultdict

class UnionFind:

    def __init__(self, n, zero_index=False):
        self.n = n
        self.offset = 0 if zero_index else 1

        self.root = [-1] * (n + self.offset)

    def find(self, x):
        if self.root[x] < 0:
            return x
        else:
            # Path compression
            self.root[x] = self.find(self.root[x])
            return self.root[x]

    def unite(self, x, y):
        x = self.find(x)
        y = self.find(y)

        if x == y:
            return

        if self.root[x] > self.root[y]:
            x, y = y, x

        self.root[x] += self.root[y]
        self.root[y] = x

    def same(self, x, y):
        return self.find(x) == self.find(y)

    def roots(self):
        return [i for i, r in enumerate(self.root) if r < 0]

    def size(self, x):
        return -self.root[self.find(x)]

    def members(self, x):
        r = self.find(x)
        return [i + self.offset for i in range(self.n) if r == self.find(i + self.offset)]

    def group_size(self):
        return len(self.roots())

    def group_members(self):
        group = defaultdict(list)

        for i in range(self.n):
            i += self.offset
            group[self.find(i)].append(i)

        return group


def solve(N: int, M: int, u: "List[int]", v: "List[int]"):
    tree = UnionFind(N)
    for u_, v_ in zip(u, v):
        tree.unite(u_, v_)

    print(len(tree.group_members()))



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    u = [int()] * (M)  # type: "List[int]"
    v = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        u[i] = int(next(tokens))
        v[i] = int(next(tokens))
    solve(N, M, u, v)

if __name__ == '__main__':
    main()
