#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str




def solve(N: int, K: int, A: "List[int]", Q: int, L: "List[int]", R: "List[int]"):

    cumsum = [[0] * (N + 1) for _ in range(K)]
    for k in range(K):
        for i in range(N):
            v = 0
            if i % K == k: v = A[i]
            cumsum[k][i + 1] = cumsum[k][i] + v


    for l, r in zip(L, R):
        l -= 1

        v = None
        for k in range(K):
            if v is None: v = cumsum[k][r] - cumsum[k][l]
            elif v != (cumsum[k][r] - cumsum[k][l]):
                v = None
                break
        if v is not None:
            print(YES)
        else:
            print(NO)





# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    Q = int(next(tokens))  # type: int
    l = [int()] * (Q)  # type: "List[int]"
    r = [int()] * (Q)  # type: "List[int]"
    for i in range(Q):
        l[i] = int(next(tokens))
        r[i] = int(next(tokens))
    solve(N, K, A, Q, l, r)

if __name__ == '__main__':
    main()
