#!/usr/bin/env python3
import sys

sys.setrecursionlimit(1 << 25)


def solve(N: int, M: int, u: "List[int]", v: "List[int]"):

    edge = [[] for _ in range(N)]
    for u_, v_ in zip(u, v):
        u_, v_ = u_ - 1, v_ - 1
        edge[u_].append(v_)
        edge[v_].append(u_)

    ans = 0
    visits = [False] * N
    def dfs(i):
        nonlocal ans
        nonlocal visits
        visits[i] = True
        ans += 1

        for j in edge[i]:
            if not visits[j]:
                dfs(j)

        visits[i] = False

    dfs(0)
    print(ans)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    u = [int()] * (M)  # type: "List[int]"
    v = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        u[i] = int(next(tokens))
        v[i] = int(next(tokens))
    solve(N, M, u, v)

if __name__ == '__main__':
    main()
