#!/usr/bin/env python3
import sys
from collections import defaultdict


def solve(N: int, K: int, A: "List[int]"):

    ans = 0
    r_idx = 0
    curr_set = set()
    counter = defaultdict(int)

    for l_idx in range(N - 1):
        if r_idx == l_idx:
            r_idx += 1
            # 現在の種類と個数を更新
            curr_set.add(A[r_idx - 1])
            counter[A[r_idx - 1]] += 1

        if len(curr_set) > K: continue

        ans = max(ans, r_idx - l_idx)
        while r_idx + 1 <= N:
            r_idx += 1
            # 現在の種類と個数を更新
            curr_set.add(A[r_idx - 1])
            counter[A[r_idx - 1]] += 1

            if len(curr_set) > K: break
            ans = max(ans, r_idx - l_idx)
        """
        if r_idx <= N:
            r_idx += 1
            while r_idx <= N:
                # 現在の種類と個数を更新
                curr_set.add(A[r_idx - 1])
                counter[A[r_idx - 1]] += 1

                if len(curr_set) > K: break
                ans = max(ans, r_idx - l_idx)
                r_idx += 1
        """

        # 削除して個数が0になったものをSetから削除
        counter[A[l_idx]] = max(counter[A[l_idx]] - 1, 0)
        if counter[A[l_idx]] == 0:
            curr_set.remove(A[l_idx])

    print(ans)




# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    a = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, K, a)

if __name__ == '__main__':
    main()
