#!/usr/bin/env python3
import sys

def solve(N: int):

    # 条件式から上限のおおよその値を求める
    n_size = int(N ** (1/3))


    # エラストテレスのふるい
    # ----------------------------------------
    p_list = [i for i in range(n_size + 1)]
    root_n = n_size ** 0.5

    # 1と2の倍数(2以外)は予め0で埋めておく
    # (0は素数ではないという印みたいなもの)
    p_list[1] = 0
    for i in p_list[3:]:
        if p_list[i] % 2 == 0:
            p_list[i] = 0

    for i in range(3, n_size):
        if i > root_n: break
        if p_list[i] != 0:
            for j in range(i, n_size + 1, 2):
                if i * j >= n_size + 1 :
                    break
                p_list[i * j] = 0

    p_list = list(set(p_list))
    n_prime = len(p_list)
    # ----------------------------------------

    ans = 0
    for i in range(1, n_prime - 1):
        for j in range(i + 1, n_prime):
            p = p_list[i]
            q = p_list[j]
            if p * (q ** 3) <= N:
                ans += 1
            else:
                # 素数は小さい順に並んでいるため、一度条件を満たさなかった場合、
                # jのループ内で、以降条件を満たす値は無いので、ループを抜ける
                break

    print(ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
