#!/usr/bin/env python3
import sys


from heapq import heappop, heappush

class Heapque:
    def __init__(self, init=None, order_asc=True):
        self.que = [] if init is None else init
        self.order_asc = order_asc
        self.datatype = None

    def __call__(self):
        return self.que

    def _set_datatype(self, data):
        if isinstance(data, list):
            self.datatype = "list"
        elif isinstance(data, tuple):
            self.datatype = "tuple"
        else:
            self.datatype = "scalar"

    def _process(self, data):
        if self.datatype is None:
            self._set_datatype(data)

        if self.order_asc:
            return data

        if self.datatype == "tuple":
            return (-data[0], *data[1:])
        elif self.datatype == "list":
            return [-data[0], *data[1:]]
        else:
            return -data

    def push(self, data):
        heappush(self.que, self._process(data))

    def pop(self):
        data = heappop(self.que)
        return self._process(data)


def solve(N: int, M: int, A: "List[int]", S: "List[str]"):

    que_list = []
    pt_list = []
    max_num = 0

    for i, s in enumerate(S):
        que = Heapque(order_asc=False)
        num = i + 1
        for i, c in enumerate(s):
            if c == "o":
                num += A[i]
            else:
                que.push(A[i])

        max_num = max(max_num, num)
        que_list.append(que)
        pt_list.append(num)

    ans = []
    for i, (que, pt) in enumerate(zip(que_list, pt_list)):
        cnt = 0
        if pt == max_num:
            ans.append(cnt)
            continue
        while pt <= max_num:
            pt += que.pop()
            cnt += 1
        ans.append(cnt)

    for a in ans:
        print(a)

# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(M)]  # type: "List[int]"
    S = [next(tokens) for _ in range(N)]  # type: "List[str]"
    solve(N, M, A, S)

if __name__ == '__main__':
    main()
