#!/usr/bin/env python3
import sys


def solve(N: int, M: int, U: "List[int]", V: "List[int]"):

    edges = [[] for _ in range(N)]
    for u, v in zip(U, V):
        u -= 1
        v -= 1
        edges[u].append(v)
        edges[v].append(u)

    ans = 0
    for i in range(N):
        for j in edges[i]:
            for k in edges[j]:
                if i in edges[k] and i < j < k:
                    ans += 1
    print(ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    U = [int()] * (M)  # type: "List[int]"
    V = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        U[i] = int(next(tokens))
        V[i] = int(next(tokens))
    solve(N, M, U, V)

if __name__ == '__main__':
    main()
