#!/usr/bin/env python3
import sys


def solve(N: int, A: "List[int]"):

    L = [0] * 4

    p = 0
    for a in A:
        L[0] = 1

        for i in range(3, -1, -1):
            if L[i] == 0:
                continue
            ni = i + a
            L[i] = 0
            if ni >= 4:
                p += 1
                continue

            L[ni] = 1

    print(p)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, A)

if __name__ == '__main__':
    main()
