#!/usr/bin/env python3
import sys


def cumsum_1d(data):
    n = len(data)
    cumsum_data = [0] * (n + 1)
    for i in range(n):
        cumsum_data[i + 1] = data[i] + cumsum_data[i]
    return cumsum_data


def solve(N: int, A: list[int], B: list[int], C: list[int]):
    a_cumsum = cumsum_1d(A)
    b_cumsum = cumsum_1d(B)
    c_cumsum = cumsum_1d(C)

    ans = 0
    max_m = -float("INF")
    for y in range(2, N):
        max_m = max(max_m, a_cumsum[y - 1] - b_cumsum[y - 1])
        n = b_cumsum[y] - c_cumsum[y]
        o = c_cumsum[-1]
        ans = max(ans, max_m + n + o)

    print(ans)


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: list[int]
    B = [int(next(tokens)) for _ in range(N)]  # type: list[int]
    C = [int(next(tokens)) for _ in range(N)]  # type: list[int]
    solve(N, A, B, C)

if __name__ == '__main__':
    main()
