#!/usr/bin/env python3
import sys


def solve(N: int):

    if N % 2 == 0:
        for i in range(1 << N):
            ans = ''
            cnt = 0
            for j in range(N-1, -1, -1):
                if i & (1 << j) == 0:
                    ans += '('
                    cnt += 1
                else:
                    ans += ')'
                    cnt -= 1

                if cnt < 0:
                    break
            if cnt == 0:
                print(ans)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
