#!/usr/bin/env python3
import sys
from collections import deque


def solve(H: int, W: int, S: "List[str]"):

    _W = W + 2
    _H = H + 2
    WALL = 'w'
    PIECE = 'o'
    BLANK = '-'
    DISABLE = 'x'

    field = [[WALL] * _W for _ in range(_H)]

    flg = True
    bh, bw = 0, 0
    eh, ew = 0, 0

    for h in range(H):
        for w in range(W):
            field[h + 1][w + 1] = S[h][w]
            if S[h][w] == PIECE:
                if flg:
                    bh, bw = h + 1, w + 1
                    flg = False
                else:
                    eh, ew = h + 1, w + 1

    deq = deque()

    deq.append([bh, bw, 0])

    move = [(0, 1), (1, 0), (-1, 0), (0, -1)]

    while deq:
        ch, cw, cnt = deq.popleft()

        if ch == eh and cw == ew:
            print(cnt)
            break

        for m in move:
            nh = ch + m[0]
            nw = cw + m[1]
            if field[nh][nw] == BLANK or field[nh][nw] == PIECE:
                field[nh][nw] = DISABLE
                deq.append([nh, nw, cnt + 1])






# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    H = int(next(tokens))  # type: int
    W = int(next(tokens))  # type: int
    S = [next(tokens) for _ in range(H)]  # type: "List[str]"
    solve(H, W, S)

if __name__ == '__main__':
    main()
