#!/usr/bin/env python3
import sys
from collections import defaultdict
INF = float('inf')  # type: float


def solve(p: str, q: str):

    cvt = {
        "A": 0,
        "B": 1,
        "C": 2,
        "D": 3,
        "E": 4,
        "F": 5,
        "G": 6
    }

    data = [3,1,4,1,5,9]
    cumsum_data = [0] * (len(data) + 1)
    for i in range(len(data)):
        cumsum_data[i + 1] = cumsum_data[i] + data[i]

    p_i, q_i = cvt[p], cvt[q]
    max_i, min_i = max(p_i, q_i), min(p_i, q_i)
    print(cumsum_data[max_i] - cumsum_data[min_i])




# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    p = next(tokens)  # type: str
    q = next(tokens)  # type: str
    solve(p, q)

if __name__ == '__main__':
    main()
