#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1


"""
バグの根本原因
固定された r に対して、有効な l が複数存在する場合に正しく数えられていないことが問題です。

現在のコードは1つのスライディングウィンドウで l_idx を管理しているため、各 r につき最大1回しか ans を増やせません。しかし実際には、ある r に対して複数の有効な l が存在します。

反例
N=6, A=2, B=2, S="aaabba" で試すと：

有効なペア（1-indexed）：(1,2), (1,3), (1,4), (2,3), (2,4) → 答え 5

しかし現在のコードは 4 を出力します。r=2, r=3 のとき、l=2 が有効なのに l=1 の1ペアしかカウントしていません。

正しいアプローチ
各 r に対して有効な l の範囲 [lb, la-1] を求め、max(0, la - lb) を加算する必要があります：

lb：b_cnt < B を満たす最小の l（単調増加）
la：a_cnt >= A を満たす最大の l + 1（単調増加）
2つの独立したポインタで管理できます


lb と la はそれぞれ独立したウィンドウのカウントを持つため、互いに干渉しません。各ポインタは右にしか動かないので全体 O(N) です。
"""


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N, A, B = map(int, input().split())
    S = input()

    ans = 0
    lb = 0  # b制約: b_cnt([lb, r]) < B となる最小l
    la = 0  # a制約: a_cnt([la, r]) >= A となる最大l+1
    b_cnt_lb = 0
    a_cnt_la = 0

    for r, s in enumerate(S):
        if s == 'a':
            a_cnt_la += 1
        else:
            b_cnt_lb += 1

        # b_cnt >= B ならlbを右に動かす
        while b_cnt_lb >= B:
            if S[lb] == 'b':
                b_cnt_lb -= 1
            lb += 1

        # a_cnt >= A の間laを右に動かす（有効範囲の右端を探す）
        while a_cnt_la >= A:
            if S[la] == 'a':
                a_cnt_la -= 1
            la += 1

        # 有効なlの範囲は [lb, la-1]
        ans += max(0, la - lb)

    print(ans)


if __name__ == '__main__':
    main()
