#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1




# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N, A, B = map(int, input().split())
    S = input()

    a_cnt, b_cnt = 0, 0

    ans = 0
    l_idx = 0
    for r_idx, s in enumerate(S):

        if s == "a":
            a_cnt += 1
        else:
            b_cnt += 1
        
        while b_cnt >= B:
            if S[l_idx] == "a":
                a_cnt -= 1
                if a_cnt >= A and b_cnt - 1 < B:
                    ans += 1
            else:
                b_cnt -= 1
            l_idx += 1
        
        if a_cnt >= A and b_cnt < B:
            ans += 1
    
    print(ans)


if __name__ == '__main__':
    main()
