#!/usr/bin/env python3
import sys
from collections import defaultdict, Counter
INF = float('inf')  # type: float


def solve(N: int, S: str):
    cnt = Counter(S)
    if cnt["T"] > cnt["A"]:
        print("T")
    elif cnt["T"] < cnt["A"]:
        print("A")
    else:
        if S[-1] == "A":
            print("T")
        else:
            print("A")


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    solve(N, S)

if __name__ == '__main__':
    main()
