#!/usr/bin/env python3
import sys


def solve(N: int, A: "List[int]"):

    A = [0] + A
    l_l = [0] * (N + 2)
    r_l = [0] * (N + 2)
    for i in range(1, N + 1):
        l_l[i] = min(A[i], l_l[i - 1] + 1)
    for i in range(N, 0, -1):
        r_l[i] = min(A[i], r_l[i + 1] + 1)

    ans = 0
    for l, r in zip(l_l, r_l):
        ans = max(ans, min(l, r))
    print(ans)



# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, A)

if __name__ == '__main__':
    main()
