#!/usr/bin/env python3
import sys
from collections import defaultdict


def solve(A: int, B: int):

    a_dict = defaultdict(bool)
    b_dict = defaultdict(bool)

    if A >= 4:
        a_dict[4] = True
        A -= 4
    if B >= 4:
        b_dict[4] = True
        B -= 4

    if A >= 2:
        a_dict[2] = True
        A -= 2
    if B >= 2:
        b_dict[2] = True
        B -= 2

    if A >= 1:
        a_dict[1] = True
        A -= 41
    if B >= 1:
        b_dict[1] = True
        B -= 1

    ans = 0
    for k in [4, 2, 1]:
        if a_dict[k] or b_dict[k]:
            ans += k

    print(ans)



    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    solve(A, B)

if __name__ == '__main__':
    main()
