#!/usr/bin/env python3
import sys

from collections import deque


def solve(N: int, A: "List[int]"):

    edges = [[] for _ in range(N)]

    dirs = [0] * N

    for i, a in enumerate(A):
        a -= 1
        edges[i].append(a)
        dirs[a] += 1

    used = [False] * N

    base_pos = None
    for i in range(N):
        if used[i]:
            continue

        que = deque()
        que.append(i)
        used[i] = True

        while que:
            cur = que.popleft()

            nxt = edges[cur][0]
            if used[nxt]:
                base_pos = nxt
                break
            else:
                used[nxt] = True
                que.append(nxt)

        if base_pos is not None:
            break

    ans = []
    que = deque()
    que.append(base_pos)
    while True:
        cur = que.popleft()
        ans.append(cur + 1)
        nxt = edges[cur][0]
        if nxt == base_pos:
            break
        que.append(nxt)

    print(len(ans))
    print(*ans)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, A)

if __name__ == '__main__':
    main()
