#!/usr/bin/env python3


def solve(N, M, C_list, A_list):

    ans = 0
    for bit in range(1, 2**M):
        curr_set = set()
        for i in range(M):
            if (bit >> i) & 1:
                curr_set |= A_list[i]
        is_correct = True
        for i in range(1, N + 1):
            if i not in curr_set:
                is_correct = False
                break
        if is_correct:
            ans += 1
    print(ans)

# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N, M = map(int, input().split())
    C_list = []
    A_list = []
    for _ in range(M):
        C_list.append(int(input()))
        A_list.append(set(map(int, input().split())))

    solve(N, M, C_list, A_list)

if __name__ == '__main__':
    main()
