#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1


def solve(N: int, K: int, S: str):
    
    cnt = defaultdict(int)

    for i in range(N - K + 1):
        curr = ""
        for j in range(K):
            curr += S[i + j]
        cnt[curr] += 1
    
    cnt = sorted(cnt.items(), key=lambda x:x[1], reverse=True)
    n_max = cnt[0][1]

    num = 0
    chars = []
    for k, v in cnt:
        if v != n_max:
            break
        num = v
        chars.append(k)
    
    chars.sort()

    print(num)
    print(*chars)


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    solve(N, K, S)

if __name__ == '__main__':
    main()
