#!/usr/bin/env python3
import sys


def solve(A: "List[List[int]]"):

    board = [[0] * 3 for _ in range(3)]

    r_slope = set([2, 4, 6])
    l_slope = set([0, 4, 8])

    def put(v, i, j):
        nonlocal board
        board[i][j] = v

        def is_ok(check):
            return len(check) == 1 and v in check

        # lat lon check
        checK_lat, checK_lon = set(), set()
        for k in range(3):
            checK_lat.add(board[k][j])
            checK_lon.add(board[i][k])
        if is_ok(checK_lat) or is_ok(checK_lon):
            return True

        # slope check
        if (i + j) in l_slope:
            check_slope = set()
            for k in range(3):
                check_slope.add(board[k][k])
            if is_ok(check_slope):
                return True
        if (i + j) in r_slope:
            check_slope = set()
            for k in range(3):
                check_slope.add(board[k][2 - k])
            if is_ok(check_slope):
                return True

        return False

    def dfs(v, i, j):
        pass

    for i in range(3):
        for j in range(3):
            dfs(1, i, j)





# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    A = [[int(next(tokens)) for _ in range(3)] for _ in range(3)]  # type: "List[List[int]]"
    solve(A)

if __name__ == '__main__':
    main()
