#!/usr/bin/env python3
import sys


def solve(M: int, D: "List[int]"):

    n_d = sum(D)
    n_h_d = n_d // 2 + 1

    c_d = 0
    for i, d in enumerate(D):
        if c_d + d < n_h_d:
            c_d += d
            continue

        m = i + 1
        d = (n_h_d - c_d)
        print(m, d)
        break



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    M = int(next(tokens))  # type: int
    D = [int(next(tokens)) for _ in range(M)]  # type: "List[int]"
    solve(M, D)

if __name__ == '__main__':
    main()
