#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve():
    N, H = map(int, input().split())

    curr_t = 0

    lim_l = H
    lim_u = H
    
    query = []
    for _ in range(N):
        t, l, u = map(int, input().split())
        query.append((t, l, u))

    for t, l, u in query:
        diff_t = t - curr_t
        cur_l = max(lim_l - diff_t, 1)
        cur_u = lim_u + diff_t

        update_l = max(cur_l, l)
        update_u = min(cur_u, u)

        if update_l > update_u:
            print(NO)
            return

        lim_l = update_l
        lim_u = update_u
        curr_t = t

    print(YES)


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    T = int(input())

    for _ in range(T):
        solve()


if __name__ == '__main__':
    main()
