#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
from sortedcontainers import SortedSet
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1


def solve(N: int, Q: int, X: list[int], Y: list[int]):

    cnt_map = defaultdict(int)
    for i in range(1, N + 1):
        cnt_map[i] = 1
    
    store = SortedSet([-i for i in range(1, N + 1)])

    def solve(x, y):
        nonlocal cnt_map, store
        res = 0

        while True:
            i = store.pop()
            i = -i

            if i > x:
                store.add(-i)
                break

            cnt = cnt_map[i]
            res += cnt
            store.add(-y)

            cnt_map[i] = 0
            cnt_map[y] += cnt
            
        return res

    for x, y in zip(X, Y):
        ans = solve(x, y)
        print(ans)


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    Q = int(next(tokens))  # type: int
    X = [int()] * (Q)  # type: list[int]
    Y = [int()] * (Q)  # type: list[int]
    for i in range(Q):
        X[i] = int(next(tokens))
        Y[i] = int(next(tokens))
    solve(N, Q, X, Y)

if __name__ == '__main__':
    main()
