#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1


def solve(N: int):
    
    def f(n):
        res = 0
        while n > 0:
            res += n % 10
            n //= 10
        return res
    
    a_list = [0] * (N + 1)
    a_list[0] = 1
    for i in range(1, N + 1):
        a = 0
        for j in range(i):
            a += f(a_list[j])
        a_list[i] = a

    print(a_list[N])


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
