#!/usr/bin/env python3
import sys


"""
    0 1 2 ... V (10^3 * 100)
0 |
1 |
2 |
: |
N |
"""

def solve(N: int, W: int, w: "List[int]", v: "List[int]"):

    MAX_V = 10 ** 5 + 1
    dp = [[float('Inf')]*MAX_V for _ in range(N + 1)]
    dp[0][0] = 0

    for i in range(N):
        for j in range(MAX_V):
            if j - v[i] >= 0:
                dp[i + 1][j] = min(dp[i][j], dp[i][j - v[i]] + w[i])
            else:
                dp[i + 1][j] = dp[i][j]

    ans_idx = MAX_V - 1
    while dp[-1][ans_idx] > W:
        ans_idx -= 1

    print(ans_idx)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    W = int(next(tokens))  # type: int
    w = [int()] * (N)  # type: "List[int]"
    v = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        w[i] = int(next(tokens))
        v[i] = int(next(tokens))
    solve(N, W, w, v)

if __name__ == '__main__':
    main()
