#!/usr/bin/env python3
import sys
from collections import defaultdict

MOD = 998244353  # type: int
INF = float('inf')  # type: float


def solve(N: int, A: "List[int]", B: "List[int]"):

    dp = [[0] * 2 for _ in range(N)]

    AB = [[a, b] for a, b in zip(A, B)]

    dp[0][0] = 1
    dp[0][1] = 1

    for i in range(1, N):
        for p in range(2):
            for n in range(2):
                if AB[i][n] != AB[i-1][p]:
                    dp[i][n] += dp[i - 1][p]
                    dp[i][n] %= MOD

    print(sum(dp[-1]))



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int()] * (N)  # type: "List[int]"
    B = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        A[i] = int(next(tokens))
        B[i] = int(next(tokens))
    solve(N, A, B)

if __name__ == '__main__':
    main()
