#!/usr/bin/env python3


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N = int(input())
    XY = [tuple(map(int, input().split())) for _ in range(N)]

    c_a, c_t = 0, 0
    for x, y in XY:
        c_t += x
        c_a += y

    if c_t > c_a:
        print("Takahashi")
    elif c_t < c_a:
        print("Aoki")
    else:
        print("Draw")


if __name__ == '__main__':
    main()
