#!/usr/bin/env python3
import sys
import math

def warshall_floyd(N, edges):
    for k in range(N):
        for i in range(N):
            for j in range(N):
                edges[i][j] = min(edges[i][j], max(edges[i][k], edges[k][j]))
    return edges


def solve(N: int, x: "List[int]", y: "List[int]", P: "List[int]"):

    edges = [[float('Inf')] * N for _ in range(N)]

    for i in range(N):
        for j in range(N):
            edges[i][j] = (abs(x[i] - x[j]) + abs(y[i] - y[j])) / P[i]

    edges = warshall_floyd(N, edges)
    for a in edges:
        print(a)

    ans = float('Inf')
    for i in range(N):
        tmp = 0
        for j in range(N):
            tmp = max(tmp, edges[i][j])
        ans = min(ans, tmp)

    print(math.ceil(ans))



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    x = [int()] * (N)  # type: "List[int]"
    y = [int()] * (N)  # type: "List[int]"
    P = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        x[i] = int(next(tokens))
        y[i] = int(next(tokens))
        P[i] = int(next(tokens))
    solve(N, x, y, P)

if __name__ == '__main__':
    main()
