#!/usr/bin/env python3


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    H, W = map(int, input().split())

    data = [input() for _ in range(H)]

    def get_rect():

        #a, b = 0, H - 1
        #c, d = 0, W - 1
        a, b = H - 1, 0
        c, d = W - 1, 0

        for i in range(H):
            for j in range(W):
                if data[i][j] == "#":
                    a = min(i, a)
                    b = max(i, b)
                    c = min(j, c)
                    d = max(j, d)

        return a, b, c, d

    a, b, c, d = get_rect()

    for i in range(a, b + 1):
        for j in range(c, d + 1):
            if data[i][j] == ".":
                print(i + 1, j + 1)
                return

if __name__ == '__main__':
    main()
