#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
from atcoder.dsu import DSU
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1

MOD = 998244353  # type: int

def solve(N: int, M: int, U: list[int], V: list[int]):
    uf = DSU(N)

    ans = 0
    n_con = N
    for i in range(M - 1, -1, -1):
        u, v = U[i], V[i]

        if uf.same(u, v):
            continue

        if n_con > 2:
            uf.merge(u, v)
            n_con -= 1
        else:
            ans += pow(2, i + 1, MOD)

    print(ans % MOD)


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    U = [int()] * (M)  # type: list[int]
    V = [int()] * (M)  # type: list[int]
    for i in range(M):
        U[i] = int(next(tokens)) - 1
        V[i] = int(next(tokens)) - 1
    solve(N, M, U, V)

if __name__ == '__main__':
    main()
