#!/usr/bin/env python3
import sys
from collections import defaultdict

YES = "Yes"  # type: str
NO = "No"  # type: str
INF = float('inf')  # type: float


def solve(S: "List[int]"):

    ps = None
    for s in S:
        if ps is not None and ps > s:
            print(NO)
            return
        ps = s

        if s < 100 or s > 675:
            print(NO)
            return

        if s % 25 != 0:
            print(NO)
            return

    print(YES)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = [int(next(tokens)) for _ in range(8)]  # type: "List[int]"
    solve(S)

if __name__ == '__main__':
    main()
