#!/usr/bin/env python3
import sys


def solve(S: "List[str]"):

    ROW, COL = len(S), len(S[0])
    b_r, b_c = -1, -1
    for r in range(ROW):
        for c in range(COL):
            if S[r][c] == '#':
                b_r, b_c = r, c
                break
        if b_r != -1:
            break

    e_r, e_c = b_r, b_c
    for r in range(b_r + 1, ROW):
        if S[r][b_c] == '#':
            e_r = r
        else:
            break
    for c in range(b_c + 1, COL):
        if S[b_r][c] == '#':
            e_c = c
        else:
            break

    print(b_r + 1, e_r + 1)
    print(b_c + 1, e_c + 1)




# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = [next(tokens) for _ in range(10)]  # type: "List[str]"
    solve(S)

if __name__ == '__main__':
    main()
