#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1


def solve(N: int, W: list[int], V: list[int], Q: int, L: list[int], R: list[int], C: list[int]):
    return


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    W = [int()] * (N)  # type: list[int]
    V = [int()] * (N)  # type: list[int]
    for i in range(N):
        W[i] = int(next(tokens))
        V[i] = int(next(tokens))
    Q = int(next(tokens))  # type: int
    L = [int()] * (Q)  # type: list[int]
    R = [int()] * (Q)  # type: list[int]
    C = [int()] * (Q)  # type: list[int]
    for i in range(Q):
        L[i] = int(next(tokens))
        R[i] = int(next(tokens))
        C[i] = int(next(tokens))
    solve(N, W, V, Q, L, R, C)

if __name__ == '__main__':
    main()
