#!/usr/bin/env python3

import string

def solve(N, Q, S, query):

    eng_char = list(string.ascii_lowercase)
    eng_code = [i + 10 for i in range(len(eng_char))]

    eng_char2code = {ch: co for ch, co in zip(eng_char, eng_code)}
    eng_code2char = {co: ch for ch, co in zip(eng_char, eng_code)}

    s_num = 0
    for i, s in enumerate(S):
        unit = 2*(N - 1) - 2*i
        s_num += eng_char2code[s] * (10 ** unit)

    for q in query:

        if q[0] == 2:
            idx = q[1] - 1
            unit = 2*(N - idx - 1)
            code = (s_num // (10 ** unit)) % 100
            #print(s_num)
            #print(code)
            print(eng_code2char[code])
            #print('////')
        else:
            num = q[1]
            tail = s_num % (10 ** (2*num))
            head = s_num // (10 ** (2*num))
            #print(s_num, head, tail)
            s_num = tail * (10 ** (2*(N - num))) + head
            #print(s_num)
            #print('---')





# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N, Q = map(int, input().split())
    S = input()
    query = []
    for _ in range(Q):
        query.append(list(map(int, input().split())))

    solve(N, Q, S, query)


if __name__ == '__main__':
    main()
