#!/usr/bin/env python3

import string

def solve(N, Q, S, query):

    cnt = 0
    for q in query:

        if q[0] == 2:
            idx = q[1] - cnt % N - 1
            print(S[idx])

        else:
            cnt += q[1]




# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N, Q = map(int, input().split())
    S = input()
    query = []
    for _ in range(Q):
        query.append(list(map(int, input().split())))

    solve(N, Q, S, query)


if __name__ == '__main__':
    main()
