#!/usr/bin/env python3
import sys


def solve(Y: int):

    mod1 = Y % 4
    mod2 = (Y + 2) % 4

    if mod1 == 0:
        print(Y + 2)
    elif mod2 == 0:
        print(Y)
    else:
        print(Y - mod2 + 4)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    Y = int(next(tokens))  # type: int
    solve(Y)

if __name__ == '__main__':
    main()
