#!/usr/bin/env python3
import sys


def solve(X: int, A: int, D: int, N: int):
    
    end = A + D * (N - 1)

    num_min = A
    num_max = end

    if num_min > num_max:
        num_min, num_max = num_max, num_min

    if X <= num_min:
        print(abs(num_min - X))
        return
    
    if X >= num_max:
        print(abs(num_max - X))
        return

    nx = abs(X - A)
    D = abs(D)
    mod = abs(nx % D)
    if mod == 0:
        print(0)
    else:
        diff = abs(D - mod)
        print(min(mod, diff))



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    X = int(next(tokens))  # type: int
    A = int(next(tokens))  # type: int
    D = int(next(tokens))  # type: int
    N = int(next(tokens))  # type: int
    solve(X, A, D, N)

if __name__ == '__main__':
    main()
