#!/usr/bin/env python3


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N, M = map(int, input().split())
    S = input()
    T = input()
    Q = int(input())
    W = [input() for _ in range(Q)]

    set_s = set(S)
    set_t = set(T)
    set_st = set_s.intersection(set_t)
    unique_s = set_s - set_st
    unique_t = set_t - set_st

    def judge(w):
        for c in w:
            if c in unique_s:
                return "Takahashi"
            elif c in unique_t:
                return "Aoki"
        return "Unknown"
    
    for w in W:
        print(judge(w))


if __name__ == '__main__':
    main()
