#!/usr/bin/env python3

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(H1, W1, A, H2, W2, B):

    # 1bit: remove, 0bit: save
    for i in range(1 << H1):
        for j in range(1 << W1):
            row_list = []
            for k in range(H1):
                if i & (1 << k) == 0:
                    row_list.append(k)
            col_list = []
            for k in range(W1):
                if j & (1 << k) == 0:
                    col_list.append(k)

            if len(row_list) != H2 or len(col_list) != W2:
                continue

            is_match = True
            for ri, r in enumerate(row_list):
                for ci, c in enumerate(col_list):
                    if A[r][c] != B[ri][ci]:
                        is_match = False
                        break

            if is_match:
                print(YES)
                return

    print(NO)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    # Failed to predict input format

    H1, W1 = map(int, input().split())
    A = [[] for _ in range(H1)]
    for i in range(H1):
        A[i] = list(map(int, input().split()))

    H2, W2 = map(int, input().split())
    B = [[] for _ in range(H2)]
    for i in range(H2):
        B[i] = list(map(int, input().split()))

    solve(H1, W1, A, H2, W2, B)

if __name__ == '__main__':
    main()
