#!/usr/bin/env python3
import sys
from collections import deque

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(N: int, M: int, u: "List[int]", v: "List[int]"):

    edge = [[] for _ in range(N)]

    for ui, vi in zip(u, v):
        ui -= 1
        vi -= 1
        edge[ui].append(vi)
        edge[vi].append(ui)

    is_visit = [False] * N
    q = deque()
    q.append((0, None))

    while q:
        c, p = q.popleft()
        is_visit[c] = True

        for n in edge[c]:
            if p is not None and p == n:
                continue

            if is_visit[n]:
                print(NO)
                return
            q.append((n, c))

    for r in is_visit:
        if not r:
            print(NO)
            return

    print(YES)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    u = [int()] * (M)  # type: "List[int]"
    v = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        u[i] = int(next(tokens))
        v[i] = int(next(tokens))
    solve(N, M, u, v)

if __name__ == '__main__':
    main()
