#!/usr/bin/env python3
import sys
from collections import deque


def create_cost_edges(n, us, vs, cs, directed=False, onebase=True):
    edges = [[] for _ in range(n)]
    for u, v, c in zip(us, vs, cs):
        if onebase: u, v = u - 1, v - 1     # convert zero-base index
        edges[u].append((v, c))
        if directed: edges[v].append((u, c))
    return edges


def solve(N: int, M: int, L: int, S: int, T: int, U: list[int], V: list[int], C: list[int]):
    graph = create_cost_edges(N, U, V, C)
    
    que = deque()
    que.append((0, 0, 0))   # (node, cnt_branch, total_cost)

    used = set()            # (node, cnt_branch, total_cost)

    is_ok = [False] * N
    
    while que:
        curr_i, curr_branch, curr_cost = que.popleft()
        
        if not is_ok[curr_i] and (curr_branch == L) and (S <= curr_cost <= T):
            is_ok[curr_i] = True
        
        if is_ok[curr_i] or (curr_branch >= L) or (curr_cost >= T):
            continue

        for next_i, next_cost in graph[curr_i]:
            next_item = (next_i, curr_branch + 1, curr_cost + next_cost)
            if next_item not in used:
                que.append(next_item)
                used.add(next_item)
    
    ans = []
    for idx, flg in enumerate(is_ok):
        if flg:
            ans.append(str(idx + 1))
    print(" ".join(ans))



# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    L = int(next(tokens))  # type: int
    S = int(next(tokens))  # type: int
    T = int(next(tokens))  # type: int
    U = [int()] * (M)  # type: list[int]
    V = [int()] * (M)  # type: list[int]
    C = [int()] * (M)  # type: list[int]
    for i in range(M):
        U[i] = int(next(tokens))
        V[i] = int(next(tokens))
        C[i] = int(next(tokens))
    solve(N, M, L, S, T, U, V, C)

if __name__ == '__main__':
    main()
