#!/usr/bin/env python3
import sys
import bisect


def solve(N: int, W: int, A: "List[int]"):

    A.sort()

    ans = set()

    for i in range(N):
        red_num_i = W - A[i]
        if red_num_i < 0:
            break

        ans.add(A[i])

        for j in range(i + 1, N):
            red_num_j = red_num_i - A[j]
            if red_num_j < 0:
                break

            ans.add(A[i] + A[j])

            idx = bisect.bisect_right(A, red_num_j)

            for k in range(j + 1, idx):
                ans.add(A[i] + A[j] + A[k])

    print(len(ans))



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    W = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, W, A)

if __name__ == '__main__':
    main()
