#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(N: int, M: int, S: str, T: str):

    def create_patterns(t):
        pattern = set()
        n = len(t)
        for i in range(1, n):
            head_t = "*" * i + t[i:]
            tail_t = t[:-i] + "*" * i
            pattern.add(head_t)
            pattern.add(tail_t)

        for i in range(1, (n + 1) // 2):
            mid_t = "*" * i + t[i:-i] + "*" * i
            pattern.add(mid_t)
        return pattern

    patterns = create_patterns(T)

    s = S.replace(T, "#" * M)

    def my_replace(s, pattern):
        a_ary = list(s)

        base = -1
        idx = 0
        for i in range(len(a_ary)):
            if base > -1:
                if pattern[idx] == "*" or pattern[idx] == a_ary[i]:
                    idx += 1
                    if idx >= len(pattern):
                        for j in range(base, i + 1): a_ary[j] = "#"
                        base = -1
                        idx = 0
                        continue
                else:
                    base = -1
                    idx = 0

            if base == -1:
                if pattern[idx] == "*" or pattern[idx] == a_ary[i]:
                    base = i
                    idx = 1

        if base > -1 and idx >= len(pattern):
            for j in range(base, base + len(pattern)):
                a_ary[j] = "#"

        return "".join(a_ary)

    for pattern in patterns:
        s = my_replace(s, pattern)
        print(s, pattern)

    if s.count("#") < N:
        print(NO)
    else:
        print(YES)

# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    T = next(tokens)  # type: str
    solve(N, M, S, T)

if __name__ == '__main__':
    main()
