#!/usr/bin/env python3
import sys
from collections import deque

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(N: int, M: int, S: str, T: str):

    S = list(S)

    def replace(i):
        nonlocal S
        for j in range(M):
            S[i + j] = "#"

    def is_equal(i):
        for j in range(M):
            if S[i + j] != "#" and S[i + j] != T[j]:
                return False
        replace(i)
        return True

    BUF_SIZE = N - M + 1

    used = [is_equal(i) for i in range(BUF_SIZE)]
    que = deque([i for i, flg in enumerate(used) if flg])

    while que:
        curr = que.popleft()

        head = max(0, curr - M + 1)
        tail = min(BUF_SIZE, curr + M)
        for next in range(head, tail):
            if not used[next] and is_equal(next):
                used[next] = True
                que.append(next)

    if S.count("#") == N:
        print(YES)
    else:
        print(NO)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    T = next(tokens)  # type: str
    solve(N, M, S, T)

if __name__ == '__main__':
    main()
