#!/usr/bin/env python3
import sys
from heapq import heappop, heappush
from collections import deque


def solve(N: int, M: int, a: "List[int]", b: "List[int]", Q: int, x: "List[int]", k: "List[int]"):

    g = [[] for _ in range(N + 1)]

    for _a, _b in zip(a, b):
        g[_a].append(_b)
        g[_b].append(_a)

    for _x, _k in zip(x, k):
        d = deque()
        d.append((_x, 1))
        visit_set = set()
        visit_set.add(_x)

        while d:
            c_x, dist = d.popleft()

            for n_x in g[c_x]:
                if n_x not in visit_set and dist <= _k:
                    visit_set.add(n_x)
                    d.append((n_x, dist + 1))

        ans = 0
        for i in visit_set:
            ans += i

        print(ans)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    a = [int()] * (M)  # type: "List[int]"
    b = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        a[i] = int(next(tokens))
        b[i] = int(next(tokens))
    Q = int(next(tokens))  # type: int
    x = [int()] * (Q)  # type: "List[int]"
    k = [int()] * (Q)  # type: "List[int]"
    for i in range(Q):
        x[i] = int(next(tokens))
        k[i] = int(next(tokens))
    solve(N, M, a, b, Q, x, k)

if __name__ == '__main__':
    main()
