#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(S: str):

    col_dict = {
        1: 3,
        2: 2,
        3: 4,
        4: 1,
        5: 3,
        6: 5,
        7: 0,
        8: 2,
        9: 4,
        10: 6,
    }

    row_set = set()
    for i, v in enumerate(S):
        if i == 0 and v == "1":
            print(NO)
            return

        if v == "1":
            row_set.add(col_dict[i + 1])

    row_list = list(row_set)
    row_list.sort()

    prev_row = None
    for row in row_list:
        if prev_row is not None and row - prev_row > 1:
            print(YES)
            return
        prev_row = row

    print(NO)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
