#!/usr/bin/env python3
import sys


def solve(H: int, W: int, N: int, T: str, S: "List[str]"):

    T = "-" + T
    ans = 0
    for i in range(1, H - 1):
        for j in range(1, W - 1):
            ci, cj = i, j
            is_ok = True
            for t in T:
                if t == "U": ci -= 1
                elif t == "D": ci += 1
                elif t == "L": cj -= 1
                elif t == "R": cj += 1

                if S[ci][cj] == "#":
                    is_ok = False
                    break
            if is_ok:
                ans += 1
    print(ans)


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    H = int(next(tokens))  # type: int
    W = int(next(tokens))  # type: int
    N = int(next(tokens))  # type: int
    T = next(tokens)  # type: str
    S = [next(tokens) for _ in range(H)]  # type: "List[str]"
    solve(H, W, N, T, S)

if __name__ == '__main__':
    main()
