#!/usr/bin/env python3
import sys


def solve(H: int, W: int, N: int, T: str, S: "List[str]"):

    def encode(i, j):
        return i * W + j
    def decode(c):
        return (c // W, c % W)

    land_pos_set = set()
    for i in range(H):
        for j in range(W):
            if S[i][j] == ".":
                land_pos_set.add(encode(i, j))

    route_pos_list = [0]
    cur_x, cur_y = 0, 0
    for t in T:
        if t == "U": cur_y -= 1
        elif t == "D": cur_y += 1
        elif t == "L": cur_x -= 1
        else: cur_x += 1
        route_pos_list.append(encode(cur_y, cur_x))

    ans = 0
    for i in range(H):
        for j in range(W):
            if S[i][j] == "#": continue
            base = encode(i, j)
            rel_pos_set = set([c + base for c in route_pos_list])

            result = land_pos_set & rel_pos_set
            if result == rel_pos_set:
                ans += 1
    print(ans)


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    H = int(next(tokens))  # type: int
    W = int(next(tokens))  # type: int
    N = int(next(tokens))  # type: int
    T = next(tokens)  # type: str
    S = [next(tokens) for _ in range(H)]  # type: "List[str]"
    solve(H, W, N, T, S)

if __name__ == '__main__':
    main()
