#!/usr/bin/env python3
import sys


def solve(N: int, X: int, A: "List[int]"):

    def is_ok(store, src):
        store.append(src)
        store.sort()
        store = store[1:-1]
        return sum(store) >= X

    for i in range(0, 101):
        if is_ok(A.copy(), i):
            print(i)
            return

    print(-1)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    X = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N - 1)]  # type: "List[int]"
    solve(N, X, A)

if __name__ == '__main__':
    main()
