#!/usr/bin/env python3
import sys


"""
2, 3

1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11
-, 2, 3, 4, -, -, -, 8, 9, 10, -

(N % 2) & (N % 3) & !(N % 6)

-, 2, -, 4, -, -, -, 8, -, 10, -, -, -, 14,  -,
-, -, 3, -, -, -, -, -, 9,  -, -, -, -,  -, 15,
-, -, -, -, -, 6, -, -, -,  -, -,12, -,  -,  -, (gcd)

"""

import math

def lcm(a, b):
    y = a * b // math.gcd(a, b)
    return y


def solve(N: int, M: int, K: int):
    N, M = min(N, M), max(N, M)
    lcm_num = lcm(N, M)

    n_n = lcm_num // N - 1
    n_m = lcm_num // M - 1
    n_nm = n_n + n_m

    div = K // n_nm
    diff_k = K - div * n_nm

    offset = div * lcm_num

    tmp = M // N
    if tmp > diff_k:
        ans = offset + N * diff_k
        print(11)
    elif tmp + 1 == diff_k:
        ans = offset + M
        print(12)
    else:
        ans = offset + N * (diff_k - 1)
        print(13)

    print((n_n, n_m), div, diff_k, offset, tmp, ans)



# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    solve(N, M, K)

if __name__ == '__main__':
    main()
