#!/usr/bin/env python3
import sys

MOD = 1000000007  # type: int

# dpの最後の行の処理を行うため、ダミーとして@を入れている
T = 'atcoder@'


def solve(N: int, S: str):
    
    dp = [[0]*(len(T)) for _ in range(N + 1)]

    dp[0][0] = 1

    for i in range(N):
        for j in range(len(T)):
            dp[i + 1][j] += dp[i][j]
            dp[i + 1][j] %= MOD
            if S[i] == T[j]:
                dp[i + 1][j + 1] += dp[i][j]
                dp[i + 1][j + 1] %= MOD
    
    print(dp[-1][-1])



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    solve(N, S)

if __name__ == '__main__':
    main()
