#!/usr/bin/env python3
import sys
import string

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(S: str):

    used_chars = {c: False for c in string.ascii_lowercase}

    set_boxes = [[] for i in range(len(S))]
    box_idx = 0

    for s in S:
        if s == "(":
            box_idx += 1
        elif s == ")":
            for c in set_boxes[box_idx]: used_chars[c] = False
            set_boxes[box_idx] = []
            box_idx -= 1
        else:
            if used_chars[s]:
                print(NO)
                return
            used_chars[s] = True
            set_boxes[box_idx].append(s)

    print(YES)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
