#!/usr/bin/env python3
import sys
from collections import defaultdict
from collections import Counter
INF = float('inf')  # type: float

from functools import reduce
def comb(n, r):
    r = min(r, n - r)
    numer = reduce(lambda x, y: x * y, range(n, n - r, -1), 1)
    denom = reduce(lambda x, y: x * y, range(1, r + 1), 1)
    return numer // denom


def solve(N: int, A: "List[int]"):
    """
    長さL = 4
    スライド数s = L - F + 1
    ペア数n = s * (F // 2)

    F = 1 : s = 4 - 1 + 1 = 4
    F = 2 : s = 4 - 2 + 1 = 3
    F = 3 : s = 4 - 3 + 1 = 2
    F = 3 : s = 4 - 3 + 1 = 1

    F = 1 : n = 4 * 1        = 4 ※ F = 1の時は例外
    F = 2 : n = 3 * (2 // 2) = 3
    F = 3 : n = 2 * (3 // 2) = 2
    F = 4 : n = 1 * (4 // 2) = 2
    """

    n_line = N
    for i in range(2, N + 1):
        s = N - i + 1
        n_line += s * (i // 2)

    """
    a_counter = Counter(A)
    n_line -= N
    for v in a_counter.values():
        if v > 1:
            n_line -= comb(v, 2)
    """
    print(n_line)

# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, A)

if __name__ == '__main__':
    main()
