#!/usr/bin/env python3
import sys


def solve(N: int, L: int, R: int, A: "List[int]"):

    ans_list = []

    # L <= x <= R
    # |x - a| <= |y - a|
    # L <= y <= R

    """
    L:4 R:7
    a = 3
    |x - 3| <= |y - 3| (|4 - 3| = 1, |7 - 3| = 4)
    x = 4

    L:4 R:7
    a = 9
    |x - 9| <= |y - 9| (|4 - 9| = 5, |7 - 9| = 2)
    x = 7

    L:4 R:7
    a = 6
    |x - 6| <= |y - 6| (|4 - 6| = 2, |7 - 6| = 1)
    x = 5
    """
    for a in A:
        if a <= L:
            ans_list.append(L)
        elif a >= R:
            ans_list.append(R)
        else:
            ans_list.append(a)

    print(*ans_list)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    L = int(next(tokens))  # type: int
    R = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, L, R, A)

if __name__ == '__main__':
    main()
