#!/usr/bin/env python3
import sys
from collections import defaultdict
INF = float('inf')  # type: float


def solve(N: int, A: "List[int]"):

    ans = []
    for i in range(1, N):
        head, tail = A[i - 1], A[i]
        if abs(head - tail) <= 1:
            ans.append(head)
            continue

        step = (tail - head) // abs(tail - head)
        for i in range(head, tail, step):
            ans.append(i)

    ans.append(tail)
    print(*ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, A)

if __name__ == '__main__':
    main()
