#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1


def solve(S: str, T: str):
    rep_s = S.replace("A", "")
    rep_t = T.replace("A", "")

    if rep_s != rep_t:
        print(-1)
        return

    S = S + "#"
    T = T + "#"

    ans = 0
    i_t = 0
    for s in S:
        if i_t >= len(T):
            break
        t = T[i_t]
        if t == "#":
            break

        if s == t:
            i_t += 1
        elif s == "A":
            ans += 1
        else:
            while t == "A":
                ans += 1
                i_t += 1
                t = T[i_t]
            i_t += 1
    
    print(ans)



# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    T = next(tokens)  # type: str
    solve(S, T)

if __name__ == '__main__':
    main()
