#!/usr/bin/env python3
import sys


def solve(S: str):

    ans = 1
    n = len(S)
    for i in range(n):
        j = i + 1
        k = i + 2

        if j < n and S[i] == S[j]:
            cnt = 2
            ans = max(ans, cnt)
            diff = 1
            while i - diff >= 0 and j + diff < n:
                if S[i - diff] != S[j + diff]:
                    break
                cnt += 2
                ans = max(ans, cnt)
                diff += 1

        if k < n and S[i] == S[k]:
            cnt = 3
            ans = max(ans, cnt)
            diff = 1
            while i - diff >= 0 and k + diff < n:
                if S[i - diff] != S[k + diff]:
                    break
                cnt += 2
                ans = max(ans, cnt)
                diff += 1

    print(ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
