#!/usr/bin/env python3
import sys


def solve(S: str):

    RS = S[::-1]

    def solve(A, B):
        ans = 0
        while B:
            cnt = 0
            for i in range(len(B)):
                if A[i] == B[i]:
                    cnt += 1
                    ans = max(ans, cnt)
                else:
                    cnt = 0
            B = B[1:]
        return ans

    ans = max(solve(S, RS), solve(RS, S))

    print(ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
