#!/usr/bin/env python3
import math

def lcm(a, b):
    y = a * b // math.gcd(a, b)
    return y

def solve(N, TESTS):

    for n, d, k in TESTS:
        x = d * (k - 1)

        lcm_nd = lcm(n, d)
        if lcm_nd != n * d:
            x += x // lcm_nd
        print(x % n)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():

    N = int(input())
    TESTS = [list(map(int, input().split())) for _ in range(N)]

    solve(N, TESTS)


if __name__ == '__main__':
    main()
