#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1


def create_simple_edges(n: int, us: list[int], vs: list[int], directed: bool = True, onebase: bool = True) -> list[list[int]]:
    # directed: 有向グラフかどうか, onebase: 1-indexかどうか
    edges = [[] for _ in range(n)]
    for u, v in zip(us, vs):
        if onebase: u, v = u - 1, v - 1     # convert zero-base index
        edges[u].append(v)
        if directed: edges[v].append(u)
    return edges


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():

    T = int(input())

    def solve():
        N, M, K = map(int, input().split())
        S = input()
        UV = [list(map(int, input().split())) for _ in range(M)]

        edges = create_simple_edges(N, [uv[0] for uv in UV], [uv[1] for uv in UV], False, True)

        dp = [[0] * N for _ in range(2 * K + 1)]

        for idx, s in enumerate(S):
            if s == "A":
                dp[2 * K][idx] = 1
        
        def check_win(k, cur_i):
            for nxt_i in edges[cur_i]:
                if dp[k + 1][nxt_i] == 0:
                    return 1
            return 0

        for k in range(2 * K - 1, -1, -1):
            for idx in range(N):
                dp[k][idx] = check_win(k, idx)

        if dp[0][0] == 1:
            print("Alice")
        else:
            print("Bob")


    for _ in range(T):
        solve()
    
    
    

if __name__ == '__main__':
    main()
