#!/usr/bin/env python3
import sys
from collections import defaultdict
from heapq import heappop, heappush

class Heapque:

    def __init__(self, init=None, order_asc=True):
        self.que = [] if init is None else init
        self.order_asc = order_asc
        self.datatype = None

    def __call__(self):
        return self.que

    def _set_datatype(self, data):
        if isinstance(data, list):
            self.datatype = "list"
        elif isinstance(data, tuple):
            self.datatype = "tuple"
        else:
            self.datatype = "scalar"

    def _process(self, data):
        if self.datatype is None:
            self._set_datatype(data)

        if self.order_asc:
            return data

        if self.datatype == "tuple":
            return (-data[0], *data[1:])
        elif self.datatype == "list":
            return [-data[0], *data[1:]]
        else:
            return -data

    def push(self, data):
        heappush(self.que, self._process(data))

    def pop(self):
        data = heappop(self.que)
        return self._process(data)

def solve(N: int, S: "List[int]", C: "List[int]"):

    que = Heapque()
    num_store = defaultdict(int)

    def merge(s):
        nonlocal num_store, que

        c = num_store[s]
        if c < 2:
            return

        ps, pc = s, c % 2
        ns, nc = s * 2, c // 2
        while nc % 2 == 0:
            nc //= 2
            ns *= 2

        num_store[ps] = pc

        if num_store[ns] == 0:
            num_store[ns] = nc
            que.push(ns)
        else:
            num_store[ns] += nc

    def push(s, c):
        nonlocal que
        if num_store[s] == 0:
            num_store[s] = c
            que.push(s)
        else:
            num_store[s] += c

    for s, c in zip(S, C):
        push(s, c)


    while que.que:
        s = que.pop()
        merge(s)

    ans = 0
    for v in num_store.values():
        ans += v
    print(ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = [int()] * (N)  # type: "List[int]"
    C = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        S[i] = int(next(tokens))
        C[i] = int(next(tokens))
    solve(N, S, C)

if __name__ == '__main__':
    main()

