#!/usr/bin/env python3
import sys


def solve(N: int, L: int, R: int, A: "List[int]"):

    INF = float('Inf')

    dp = [[INF] * (N + 2) for _ in range(3)]
    dp[1][0] = 0
    dp[2][-1] = 0

    # left process
    for i in range(1, N + 1):
        dp[1][i] = dp[1][i - 1] + L
        dp[0][i] = min(dp[1][i - 1] + A[i - 1], dp[0][i - 1] + A[i - 1])

    # rigfht process
    ans = INF
    for i in range(1, N + 1):
        i = N + 1 - i
        dp[2][i] = dp[2][i + 1] + R
        dp[0][i] = min(dp[0][i], dp[0][i] + dp[2][i + 1])

    ans = min(min(dp[0]), sum(A))

    print(dp[0])
    print(dp[1])
    print(dp[2])

    print(ans)




# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    L = int(next(tokens))  # type: int
    R = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, L, R, A)

if __name__ == '__main__':
    main()
