#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
from sortedcontainers import SortedSet

# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1


def solve(N: int, D: int, A: list[int]):    

    ans = 0
    r_idx = 0
    store = SortedSet([-INF, INF])
    for l_idx in range(N):

        while r_idx < N:
            a = A[r_idx]
            ind = store.bisect_left(a)
            l_a = store[ind - 1]
            r_a = store[ind]
            if l_a + D <= a <= r_a - D:
                r_idx += 1
                store.add(a)
            else:
                break

        ans += r_idx - l_idx
        store.discard(A[l_idx])

    print(ans)


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    D = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: list[int]
    solve(N, D, A)

if __name__ == '__main__':
    main()
