#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1


def solve(L: int, R: int, D: int, U: int):
    
    if L < 0 and R < 0:
        L -= L
        R -= R
    if D < 0 and U < 0:
        D -= D
        U -= U
    
    def count_naive_in_rect(x, y):
        if x == 1 and y == 1:
            return 0
        elif x == 1:
            return y // 2
        elif y == 0:
            return x // 2 + 1

    # 境界線の個数は含めない
    def count_in_rect(x, y):
        assert(x == 0 or y == 0)

        if x == 1 or y == 1:
            return count_naive_in_rect(x, y)
        
        mx = x - x % 2
        my = y - y % 2

        bx, by = mx // 2, my // 2

        # 2*2ブロック(bn)とxyが一致する際の2*2ブロック(cn)の個数を求める
        bn = bx * by
        cn = min(bx, by)

        res = (bn - cn) * 2 + cn * 3
        return res

    rect = []
    x_boundary = None
    y_boundary = None
    if L < 0 and R >= 0 and D < 0 and U >= 0:
        rect = [
            (0, R, 0, U),
            (0, -L, 0, -D),
            (0, R, 0, -D),
            (0, -L, 0, U)
        ]
        x_boundary = (L, R)
        y_boundary = (D, U)
    elif L < 0 and R >= 0:
        rect = [
            (0, R, D, U),
            (0, -L, D, U)
        ]
    elif D < 0 and U >= 0:
        rect = [
            (L, R, 0, U),
            (L, R, 0, -D)
        ]
    else:
        rect = [(L, R, D, U)]

    ans = 0
    for l, r, d, u in rect:
        ans += count_in_rect(u, r)
        ans -= count_in_rect(d, r)
        ans -= count_in_rect(u, l)
        ans += count_in_rect(d, l)

    print(ans)



# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    L = int(next(tokens))  # type: int
    R = int(next(tokens))  # type: int
    D = int(next(tokens))  # type: int
    U = int(next(tokens))  # type: int
    solve(L, R, D, U)

if __name__ == '__main__':
    main()
