#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1


def solve_naive(L: int, R: int, D: int, U: int, debug=False):
    ans = 0
    for y in range(D, U + 1):
        for x in range(L, R + 1):
            if max(abs(x), abs(y)) % 2 == 0:
                ans += 1
    if not debug:
        print(ans)
    else:
        return ans


def solve(L: int, R: int, D: int, U: int, debug=False):
    ans = 0
    x0_min, x0_max = L, R

    def calc_solid(a, b):
        a = a + a % 2
        b = b - b % 2
        return (b - a) // 2 + 1

    for y in range(D, U + 1):
        y = abs(y)
        x1_min, x1_max = max(x0_min, -y), min(x0_max, y)

        # square
        if x1_min <= x1_max and y % 2 == 0:
            ans += (x1_max - x1_min + 1)

        # out of square
        if x0_min >= x1_min and x0_max <= x1_max:
            pass
        else:
            ans += calc_solid(x0_min, x0_max)
            if x1_min <= x1_max:
                ans -= calc_solid(x1_min, x1_max)
    
    if not debug:
        print(ans)
    else:
        return ans


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    L = int(next(tokens))  # type: int
    R = int(next(tokens))  # type: int
    D = int(next(tokens))  # type: int
    U = int(next(tokens))  # type: int
    solve(L, R, D, U)


def debug():
    import random

    n_min = -10**2
    n_max = 10**2

    traial = 1000
    for i in range(traial):
        while True:
            L = random.randint(n_min, n_max)
            R = random.randint(n_min, n_max)
            D = random.randint(n_min, n_max)
            U = random.randint(n_min, n_max)
            if L <= R and D <= U:
                break

        ans1 = solve_naive(L, R, D, U, debug=True)
        ans2 = solve(L, R, D, U, debug=True)

        print(f"n{i} ({L}, {R}, {D}, {U}): ({ans1}, {ans2}) ")

        if ans1 != ans2:
            print("Not equal")
            break

if __name__ == '__main__':
    main()
    #debug()

