#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1


def solve(L: int, R: int, D: int, U: int):
    
    min_x = L
    max_x = R
        
    pos_min_x, pos_max_x = None, None
    neg_min_x, neg_max_x = None, None

    if min_x < 0 and max_x < 0:
        pos_min_x, pos_max_x = -min_x, -max_x
    elif max_x >= 0 and min_x < 0:
        pos_min_x, pos_max_x = 0, max_x
        neg_min_x, neg_max_x = 1, -min_x
    else:
        pos_min_x, pos_max_x = min_x, max_x

    pos_min_x = -1
    if neg_min_x:
        neg_min_x -= 1

    
    # 正の象限(is_pos_area=True)の計算の場合は、軸の値も含める
    def calc(base_y, x, is_pos_area = True):
        res = 0

        if x < 0:
            return 0
        
        in_num = None
        if base_y < x:
            num = x - (base_y - base_y % 2)
            res += num // 2
            in_num = base_y
        else:
            in_num = x

        if base_y % 2 == 0:
            res += (in_num + int(is_pos_area)) 

        return res
    
    ans = 0
    for y in range(D, U + 1):
        ans += calc(y, pos_max_x) - calc(y, pos_min_x)

        # print(1, y, (pos_max_x, calc(y, pos_max_x)), (pos_min_x, calc(y, pos_min_x)))
    
        if neg_min_x is not None:
            
            ans += calc(y, neg_max_x, False) - calc(y, neg_min_x, False)
            # print(2, y, (neg_max_x, calc(y, neg_max_x, False)), (neg_min_x, calc(y, neg_min_x, False)))

    print(ans)        








# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    L = int(next(tokens))  # type: int
    R = int(next(tokens))  # type: int
    D = int(next(tokens))  # type: int
    U = int(next(tokens))  # type: int
    solve(L, R, D, U)

if __name__ == '__main__':
    main()
