#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(N: int, X: int, A: "List[int]", B: "List[int]"):

    dp = [[False] * (X + 1) for _ in range(N + 1)]

    dp[0][0] = True

    for i in range(N):
        for j in range(X + 1):
            for k in range(B[i] + 1):
                v = A[i] * k
                if j - v >= 0:
                    if dp[i][j - v]: dp[i + 1][j] = True

    if dp[N][X]:
        print(YES)
    else:
        print(NO)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    X = int(next(tokens))  # type: int
    A = [int()] * (N)  # type: "List[int]"
    B = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        A[i] = int(next(tokens))
        B[i] = int(next(tokens))
    solve(N, X, A, B)

if __name__ == '__main__':
    main()
