#!/usr/bin/env python3
import sys
from collections import defaultdict
INF = float('inf')  # type: float


def solve(S: str, N: int):

    n = len(S)

    def check():
        new = S.replace("?", "0")
        num = int(new, 2)
        return num <= N

    if not check():
        print(-1)
        return

    S = S[::-1]
    s_curr = 0
    for i in reversed(range(n)):
        if S[i] == "1":
            s_curr |= 1 << i
    for i in reversed(range(n)):
        if S[i] == "?":
            if (s_curr | 1 << i) <= N:
                s_curr |= 1 << i

    print(s_curr)





# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    N = int(next(tokens))  # type: int
    solve(S, N)

if __name__ == '__main__':
    main()
