#!/usr/bin/env python3
import sys
import math
from collections import defaultdict
INF = float('inf')  # type: float


def solve(N: int):

    if N == 0:
        print(0)
        return

    in_cnt = int(math.log10(N))
    cnt = in_cnt

    while cnt > 2:
        N //= 10
        cnt -= 1

    while cnt < in_cnt:
        N *= 10
        cnt += 1

    print(N)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
