#!/usr/bin/env python3
import sys
from collections import defaultdict


YES = "Yes"  # type: str
NO = "No"  # type: str
INF = float('inf')  # type: float


def solve(N: int, S: str):

    visit_dict = defaultdict(bool)

    cx, cy = 0, 0
    visit_dict[(cx, cy)] = True
    for s in S:
        if s == "R":
            move = (cx + 1, cy)
        elif s == "L":
            move = (cx - 1, cy)
        elif s == "U":
            move = (cx, cy + 1)
        else:
            move = (cx, cy - 1)

        if visit_dict[move]:
            print(YES)
            return
        visit_dict[move] = True
        cx, cy = move

    print(NO)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    solve(N, S)

if __name__ == '__main__':
    main()
