#!/usr/bin/env python3
from cmath import sqrt
import sys
import math


PI = math.pi

def query(T, L, X, Y, e):
    res_rad = 2 * PI / T
    L_half = L / 2

    gondra_rad = 2 * PI - (e * res_rad + PI / 2)

    gondola_y = L_half * math.cos(gondra_rad)
    gondola_z = L_half + L_half * math.sin(gondra_rad)

    dist = math.sqrt(X ** 2 + (Y - gondola_y) ** 2)

    dep_rad = math.atan2(gondola_z, dist)
    return dep_rad *180 / PI


def solve(T: int, L: int, X: int, Y: int, Q: int, E: "List[int]"):

    for e in E:
        print(query(T, L, X, Y, e))


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    T = int(next(tokens))  # type: int
    L = int(next(tokens))  # type: int
    X = int(next(tokens))  # type: int
    Y = int(next(tokens))  # type: int
    Q = int(next(tokens))  # type: int
    E = [int(next(tokens)) for _ in range(Q)]  # type: "List[int]"
    solve(T, L, X, Y, Q, E)

if __name__ == '__main__':
    main()
