#!/usr/bin/env python3
import sys


def solve(N: int, A: "List[int]"):

    """
    a_table = [[i, A[i], False] for i in range(N)]
    a_table = sorted(a_table, key=lambda x: x[1])

    fix_cnt = 0
    ans = 0

    for a_raw in  a_table:
        if fix_cnt >= N:
            break

    print(ans)
    """

    ans = 0
    idx = 0

    head = A[-1]
    mid  = A[idx]
    tail = A[1]

    if (head + tail) < mid:
        ans += head + tail
        loop_idx = N - 2
        idx += 3
    else:
        ans += mid
        loop_idx = N - 1
        idx += 2

    while idx < loop_idx:
        head = A[idx - 1]
        mid  = A[idx]
        tail = A[idx + 1]

        if (head + tail) < mid:
            ans += head + tail
            idx += 3
        else:
            ans += mid
            idx += 2

    if idx == loop_idx:
        head = A[idx-1]
        mid  = A[idx]

        if head < mid:
            ans += head + tail
            idx += 3
        else:
            ans += mid
            idx += 2

    print(ans)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, A)

if __name__ == '__main__':
    main()
