#!/usr/bin/env python3
import sys


def solve(N: int, C: "List[int]", P: "List[int]", Q: int, L: "List[int]", R: "List[int]"):
    
    cls_1 = [0] * (N + 1)
    cls_2 = [0] * (N + 1)

    for i in range(N):
        if C[i] == 1:
            cls_1[i + 1] = cls_1[i] + P[i]
            cls_2[i + 1] = cls_2[i]
        else:
            cls_2[i + 1] = cls_2[i] + P[i]
            cls_1[i + 1] = cls_1[i]
    
    for l, r in zip(L, R):
        cls_1_sum = cls_1[r] - cls_1[l - 1]
        cls_2_sum = cls_2[r] - cls_2[l - 1]
        print(cls_1_sum, cls_2_sum)
    

# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    C = [int()] * (N)  # type: "List[int]"
    P = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        C[i] = int(next(tokens))
        P[i] = int(next(tokens))
    Q = int(next(tokens))  # type: int
    L = [int()] * (Q)  # type: "List[int]"
    R = [int()] * (Q)  # type: "List[int]"
    for i in range(Q):
        L[i] = int(next(tokens))
        R[i] = int(next(tokens))
    solve(N, C, P, Q, L, R)

if __name__ == '__main__':
    main()
