#!/usr/bin/env python3
import sys
"""
from math import ceil

def solve_old(W: int):

    if W == 1:
        num = 1
    elif W == 2:
        num = 2
    elif W == 4:
        num = 3
    else:
    num = ceil(W / 2)

    ans = [i + 1 for i in range(num)]

    print(len(ans))
    print(*ans)
"""

def solve(W: int):

    if W == 1:
        print(1)
        print(1)
        return

    unit_num = 0

    if W < 1000:
        step_unit = 1
        mod = 10
    else:
        step_unit = 2
        mod = 100


    ans = []

    while 10**unit_num < W:
        max_num = mod if W >= 10**(unit_num + 1) else (W // (10**unit_num)) % mod + 1
        for i in range(1, max_num):
            ans.append(i * (10**unit_num))

        unit_num += step_unit

    print(len(ans))
    print(*ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    W = int(next(tokens))  # type: int
    solve(W)

if __name__ == '__main__':
    main()
