# https://atcoder.jp/contests/abc335/submissions/49128164

#!/usr/bin/env python3
import sys
from heapq import heappop, heappush


def solve(N: int, M: int, A: "List[int]", U: "List[int]", V: "List[int]"):

    edges = [[] for _ in range(N)]
    for u, v in zip(U, V):
        u -= 1
        v -= 1
        if A[u] <= A[v]:
            edges[u].append(v)
        if A[u] >= A[v]:
            edges[v].append(u)

    visited = [False] * N
    dist = [0] * N
    dist[0] = 1

    que = []
    heappush(que, (A[0], -1, 0))

    while que:
        cur_a, _, cur_id = heappop(que)
        if visited[cur_id]:
            continue
        visited[cur_id] = True

        for nxt_id in edges[cur_id]:
            if visited[nxt_id]:
                continue
            if A[nxt_id] > cur_a:
                if dist[nxt_id] < dist[cur_id] + 1:
                    dist[nxt_id] = dist[cur_id] + 1
                    heappush(que, (A[nxt_id], -dist[nxt_id], nxt_id))
            # same (cur_a == nxt_a)
            else:
                dist[nxt_id] = max(dist[nxt_id], dist[cur_id])
                heappush(que, (A[nxt_id], -dist[nxt_id], nxt_id))

    print(dist[N - 1])

# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    U = [int()] * (M)  # type: "List[int]"
    V = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        U[i] = int(next(tokens))
        V[i] = int(next(tokens))
    solve(N, M, A, U, V)

if __name__ == '__main__':
    main()
