#!/usr/bin/env python3
import sys
from collections import deque
import heapq

from heapq import heappop, heappush

def dijkstra(edges, A, n_node, start):
    dist = [float('Inf')] * n_node
    used = [False] * n_node

    a = A[start]
    dist[start] = -1
    used[start] = True
    queue = [(dist[start], a, start)]

    while queue:
        _, cur_a, now = heappop(queue)
        used[now] = True
        for next in edges[now]:
            nxt_a = A[next]
            if cur_a >= nxt_a:
                continue
            if (not used[next]) and (dist[now] - 1 < dist[next]):
                dist[next] = dist[now] - 1
                used[next] = True
                heappush(queue, (dist[next], nxt_a, next))
    return dist


def solve(N: int, M: int, A: "List[int]", U: "List[int]", V: "List[int]"):

    edges = [[] for _ in range(N)]
    for u, v in zip(U, V):
        u -= 1
        v -= 1
        edges[u].append(v)
        edges[v].append(u)

    dist = dijkstra(edges, A, N, 0)
    ans = -(dist[N - 1] - 1)
    if ans < 0:
        print(0)
    else:
        print(ans)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    U = [int()] * (M)  # type: "List[int]"
    V = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        U[i] = int(next(tokens))
        V[i] = int(next(tokens))
    solve(N, M, A, U, V)

if __name__ == '__main__':
    main()
