#!/usr/bin/env python3
import sys


def solve(N: int, M: int, K: int, S: str):

    x_cumsum = [0] * (N + 1)
    for i, s in enumerate(S):
        x_cumsum[i + 1] = x_cumsum[i]
        if s == "x":
            x_cumsum[i + 1] += 1
    x_sum = x_cumsum[-1]

    def x_num(head, i):
        offset = x_cumsum[head]

        div = i // N
        mod = i % N

        ret = div * x_sum
        ret += x_cumsum[mod]
        ret -= offset
        return ret

    ans = 0
    for i in range(N):
        left = i + 1
        right = N * M
        while left <= right:
            mid = (left + right) // 2
            if x_num(i, mid) > K:
                right = mid - 1
            else:
                left = mid + 1

        ans = max(ans, right - i)

    print(ans)




# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    solve(N, M, K, S)

if __name__ == '__main__':
    main()
