#!/usr/bin/env python3
import sys
from collections import deque


def solve(N: int, X: "List[int]", Y: "List[int]"):

    # row, col
    move = [
        (1, 0),
        (0, -1),
        (-1, -1),
        (-1, 0),
        (0, 1),
        (1, 1)
    ]

    MAX_SIZE = 2010
    field = [[0] * MAX_SIZE for _ in range(MAX_SIZE)]
    visit = [[False] * MAX_SIZE for _ in range(MAX_SIZE)]
    offset = 1000

    visit_dict = {(x + offset, y + offset): False for x, y in zip(X, Y)}

    for x, y in zip(X, Y):
        x += offset
        y += offset
        field[y][x] = 1

    ans = 0
    visit_cnt = 0

    while visit_cnt < N:
        ans += 1
        bx = 0
        by = 0
        for k, v in visit_dict.items():
            if not v:
                bx = k[0]
                by = k[1]
                break

        deq = deque()
        deq.append((bx, by))
        visit[by][bx] = True
        visit_dict[(bx, by)] = True
        visit_cnt += 1

        while deq:
            cx, cy = deq.popleft()

            for m in move:
                nx = cx + m[0]
                ny = cy + m[1]
                if nx < 0 or ny < 0 or nx >= MAX_SIZE or ny >= MAX_SIZE:
                    continue

                if field[ny][nx] == 1 and not visit[ny][nx]:
                    deq.append((nx, ny))
                    visit[ny][nx] = True
                    visit_dict[(nx, ny)] = True
                    visit_cnt += 1

    print(ans)




# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    X = [int()] * (N)  # type: "List[int]"
    Y = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        X[i] = int(next(tokens))
        Y[i] = int(next(tokens))
    solve(N, X, Y)

if __name__ == '__main__':
    main()
