#!/usr/bin/env python3
import sys


INF = float("INF")



def solve(N: int, M: int, X: "List[int]"):

    v = [0] * (N + 1)

    def dist(from_v, to_v):
        return to_v - from_v if from_v <= to_v else to_v + N - from_v

    def record(from_v, to_v, dist):
        nonlocal v
        if from_v <= to_v:
            v[from_v] += dist
            v[to_v] -= dist
        else:
            v[from_v] += dist
            v[N] -= dist
            v[0] += dist
            v[to_v] -= dist

    for i in range(M - 1):
        record(X[i], X[i + 1], dist(X[i + 1], X[i]))
        record(X[i + 1], X[i], dist(X[i], X[i + 1]))

    ans = INF
    for i in range(N):
        v[i + 1] = v[i]
        ans = min(ans, v[i])

    print(ans)


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    X = [int(next(tokens)) - 1 for _ in range(M)]  # type: "List[int]"
    solve(N, M, X)

if __name__ == '__main__':
    main()
