#!/usr/bin/env python3
import sys


INF = float("INF")



def solve(N: int, M: int, X: "List[int]"):

    memo_cnt = [0] * N  # 通った数
    memo_a = [INF] * N  # 島姉妹同時のXの移動間隔
    memo_b = [True] * N  # 確定しているルートはFalse(Nが偶数のとき、複数通れる場合があるので)

    n_even = N % 2 == 0
    half_n = N // 2

    for i in range(M - 1):
        cur_x = X[i] - 1
        nxt_x = X[i + 1] - 1

        if cur_x > nxt_x:
            cur_x, nxt_x = nxt_x, cur_x

        diff = abs(nxt_x - cur_x)

        if diff > half_n:
            diff = N - diff
            cur_x, nxt_x = nxt_x, cur_x
            nxt_x += N
        elif n_even and diff == half_n:
            # 時計、半時計の両方のルートをメモ
            for j in range(N):
                memo_a[j] = min(diff, memo_a[j])
            continue
        for j in range(cur_x, nxt_x):
            j %= N
            memo_cnt[j] += 1
            memo_a[j] = min(diff, memo_a[j])
            memo_b[j] = False

    del_idx = INF
    #curr_ma = INF
    #curr_cnt = 0
    curr_value = 0
    for i, (cnt, ma, mb) in enumerate(zip(memo_cnt, memo_a, memo_b)):
        if ma == None:
            del_idx = i
            break
        if mb == True:
            del_idx = i
            break
        if curr_value > ma * cnt:
            curr_value = ma * cnt
            del_idx = i


    ans = 0
    for i in range(M - 1):
        cur_x = X[i] - 1
        nxt_x = X[i + 1] - 1

        if cur_x > nxt_x:
            cur_x, nxt_x = nxt_x, cur_x

        if cur_x <= del_idx < nxt_x:
            cur_x, nxt_x = nxt_x, cur_x
            nxt_x += N

        diff = abs(nxt_x - cur_x)
        ans += diff

    print(ans)



# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    X = [int(next(tokens)) for _ in range(M)]  # type: "List[int]"
    solve(N, M, X)

if __name__ == '__main__':
    main()
