#!/usr/bin/env python3
import sys

def solve(K: int):
    ans = 0
    for a in range(1, int(K ** 0.5) + 1):
        if K % a != 0:
            continue
        bc = K // a
        for b in range(a, int(bc ** 0.5) + 1):
            if bc % b == 0:
                ans += 1
    print(ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    K = int(next(tokens))  # type: int
    solve(K)

if __name__ == '__main__':
    main()
