#include <bits/stdc++.h>
#define rep(i,a,b) for(int i=a;i<b;i++)
#define all(x) (x).begin(),(x).end()
#define yesno(flag) if(flag) { cout<<"yes"<<"\n"; } else{ cout<<"no"<<"\n"; }
#define YesNo(flag) if(flag) { cout<<"Yes"<<"\n"; } else{ cout<<"No"<<"\n"; }
#define YESNO(flag) if(flag) { cout<<"YES"<<"\n"; } else{ cout<<"NO"<<"\n"; }
using namespace std;
using ll = long long;
const int INF = INT_MAX / 2;
const ll INF_LL = 1LL << 60;

{% if mod %}
const long long MOD = {{ mod }};
{% endif %}
{% if yes_str %}
const string YES = "{{ yes_str }}";
{% endif %}
{% if no_str %}
const string NO = "{{ no_str }}";
{% endif %}

{% if prediction_success %}
void solve({{ formal_arguments }})
{

}
{% endif %}

// Generated by {{ atcodertools.version }} {{ atcodertools.url }}  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    cin.tie(0);
    ios::sync_with_stdio(false);

    {% if prediction_success %}
    {{input_part}}
    solve({{ actual_arguments }});
    {% else %}
    // Failed to predict input format
    {% endif %}
    return 0;
}