#!/usr/bin/env python3
import sys
from bisect import bisect_left


def solve(N: int, M: int, P: int, A: "List[int]", B: "List[int]"):

    B.sort()
    b_cumsum = [0] * (M + 1)
    for i in range(M):
        b_cumsum[i + 1] = b_cumsum[i] + B[i]

    ans = 0
    for a in A:
        ind = bisect_left(B, P - a)
        ans += b_cumsum[ind] + ind * a
        ans += (M - ind) * P

    print(ans)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    P = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    B = [int(next(tokens)) for _ in range(M)]  # type: "List[int]"
    solve(N, M, P, A, B)

if __name__ == '__main__':
    main()
