#!/usr/bin/env python3
import sys


def solve(N: int, S: "List[str]"):

    s_set = set()
    for s in S:
        rs = s[::-1]
        if s in s_set or rs in s_set:
            continue

        s_set.add(s)

    print(len(s_set))


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = [next(tokens) for _ in range(N)]  # type: "List[str]"
    solve(N, S)

if __name__ == '__main__':
    main()
