#!/usr/bin/env python3
import sys
from collections import Counter

def solve(H: int, W: int, P: "List[List[int]]"):

    ans = 0
    for bit in range(1, 1 << H):

        match_idx = []
        for c in range(W):
            base = None
            is_match = True
            for r in range(H):
                if (bit >> r) & 1:
                    if base is None:
                        base = P[r][c]
                    elif base != P[r][c]:
                        is_match = False
                        break
            if is_match:
                match_idx.append(base)

        if not match_idx:
            continue

        row_cnt = 0
        for r in range(H):
            if (bit >> r) & 1:
                row_cnt += 1

        counter = Counter(match_idx)
        ans = max(ans, max(counter.values()) * row_cnt)

    print(ans)





# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    H = int(next(tokens))  # type: int
    W = int(next(tokens))  # type: int
    P = [[int(next(tokens)) for _ in range(W)] for _ in range(H)]  # type: "List[List[int]]"
    solve(H, W, P)

if __name__ == '__main__':
    main()
