#!/usr/bin/env python3
import sys
from collections import defaultdict
from collections import deque

sys.setrecursionlimit(10 * 8)

INF = float('inf')  # type: float


def solve(N: int, M: int, K: int, _a: "List[int]", _b: "List[int]", _p: "List[int]", _h: "List[int]"):
    edges = [[] for _ in range(N)]
    for a, b in zip(_a, _b):
        a -= 1
        b -= 1
        edges[a].append(b)
        edges[b].append(a)

    enable_list = [False] * N

    dist_memory = [-1] * N

    ph = [(p - 1, h) for p, h in zip(_p, _h)]
    ph.sort(key=lambda x: x[1], reverse=True)

    h_dict = {p: h for p, h in ph}
    set_p = set(h_dict.keys())
    use_ph = defaultdict(bool)


    def dfs(p, d):
        enable_list[p] = True
        dist_memory[p] = d
        if d - 1 <= 0:
            return
        for n in edges[p]:
            if not use_ph[n]:
                if p in set_p and d - 1 < h_dict[p]:
                    use_ph[n] = True
                    dfs(n, h_dict[p])
                else:
                    dfs(n, d - 1)
            else:
                if d - 1 > dist_memory[n]:
                    dfs(n, d - 1)

    for p in set_p:
        if use_ph[p]:
            continue

        use_ph[p] = True
        dfs(p, h_dict[p])

    """
    # O(N)
    for p, h in ph:
        p -= 1
        d = 0
        que = deque()
        que.append((p, d))

        visited = [False] * N
        visited[p] = True
        enable_list[p] = True
        dist_memory[p] = h - d

        # O(N)
        while que:
            c_p, c_d = que.pop()
            if c_d + 1 > h:
                continue
            for n_p in edges[c_p]:
                if visited[n_p]:
                    continue

                if dist_memory[n_p] >= h - (c_d + 1):
                    continue

                visited[n_p] = True
                enable_list[n_p] = True
                dist_memory[n_p] = h - (c_d + 1)
                que.append((n_p, c_d + 1))
    """
    ans_list = []
    for i in range(N):
        if enable_list[i]:
            ans_list.append(i + 1)

    print(len(ans_list))
    print(*ans_list)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    a = [int()] * (M)  # type: "List[int]"
    b = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        a[i] = int(next(tokens))
        b[i] = int(next(tokens))
    p = [int()] * (K)  # type: "List[int]"
    h = [int()] * (K)  # type: "List[int]"
    for i in range(K):
        p[i] = int(next(tokens))
        h[i] = int(next(tokens))
    solve(N, M, K, a, b, p, h)

if __name__ == '__main__':
    main()
