#!/usr/bin/env python3
import sys


def solve(N: int, K: int, D: int, a: "List[int]"):

    dp = [[[-1 for _ in range(D)] for _ in range(K + 1)] for _ in range(N + 1)]

    dp[0][0][0] = 0

    for i in range(N):
        for j in range(0, K + 1):
            for k in range(D):
                if dp[i][j][k] == -1: continue

                dp[i + 1][j][k] = max(dp[i + 1][j][k],
                                      dp[i][j][k])

                if j < K:
                    dp[i + 1][j + 1][(k + a[i]) % D] = max(dp[i + 1][j + 1][(k + a[i]) % D],
                                                           dp[i][j][k] + a[i])

    print(dp[N][K][0])






# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    D = int(next(tokens))  # type: int
    a = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, K, D, a)

if __name__ == '__main__':
    main()
