#!/usr/bin/env python3
from collections import deque


MOD = 998244353  # type: int


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    Q = int(input())
    q_list = [list(map(int, input().split())) for _ in range(Q)]

    que = deque([1])
    ans = 1

    for q in q_list:
        if q[0] == 1:
            x = q[1]
            ans = ans * 10 + x
            ans %= MOD
            que.appendleft(x)
        elif q[0] == 2:
            x = que.pop()
            num = pow(10, len(que), MOD) * x
            ans -= num
            ans %= MOD
        if q[0] == 3:
            print(ans)


if __name__ == '__main__':
    main()
