#!/usr/bin/env python3
from collections import defaultdict


MOD = 998244353  # type: int


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    Q = int(input())
    q_list = [list(map(int, input().split())) for _ in range(Q)]


    rem_dict = defaultdict(int)
    idx = 0
    cnt = 0
    for q in q_list:
        if q[0] == 2:
            cnt += 1
        elif q[0] == 3:
            rem_dict[idx] = cnt
            cnt = 0

    idx = 0
    cnt = 0
    ans = 1
    if rem_dict[idx] > 0:
        rem_dict[idx] -= 1
        ans = 0

    for q in q_list:
        if q[0] == 1:
            if cnt >= rem_dict[idx]:
                x = q[1]
                ans = (ans * 10) + x
                ans %= MOD
            cnt += 1
        elif q[0] == 3:
            print(ans % MOD)
            idx += 1
            cnt = 0

if __name__ == '__main__':
    main()
