#!/usr/bin/env python3
import sys


def solve(H: int, W: int, N: int, A: "List[int]", B: "List[int]"):

    dp = [[0] * (W + 1) for _ in range(H + 1)]

    ab_set = set([(a - 1, b - 1) for a, b in zip(A, B)] )

    for i in range(1, H + 1):
        for j in range(1, W + 1):
            if (i - 1, j - 1) in ab_set:
                continue
            dp[i][j] = min(dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1]) + 1

    ans = 0
    for d in dp:
        ans += sum(d)
    print(ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    H = int(next(tokens))  # type: int
    W = int(next(tokens))  # type: int
    N = int(next(tokens))  # type: int
    a = [int()] * (N)  # type: "List[int]"
    b = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        a[i] = int(next(tokens))
        b[i] = int(next(tokens))
    solve(H, W, N, a, b)

if __name__ == '__main__':
    main()
