#!/usr/bin/env python3
from collections import defaultdict

INF = float("INF")

# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N, K, P = map(int, input().split())

    C, A = [], []
    for _ in range(N):
        line = list(map(int, input().split()))
        C.append(line[0])
        A.append(line[1:])


    dp = [defaultdict(lambda: INF) for _ in range(N + 1)]
    dp[0][tuple([0] * K)] = 0

    def add_key(key_a, key_b):
        return tuple([a + b for a, b in zip(key_a, key_b)])

    def key_saturation(key):
        return tuple([min(k, P) for k in key])


    for i in range(N):
        for p in dp[i].keys():
            dp[i + 1][p] = min(dp[i + 1][p], dp[i][p])
            n_p = add_key(p, tuple(A[i]))
            n_p = key_saturation(n_p)
            dp[i + 1][n_p] = min(dp[i + 1][n_p], dp[i][p] + C[i])

    ans = dp[N][tuple([P] * K)]
    if ans == INF:
        print(-1)
    else:
        print(ans)

if __name__ == '__main__':
    main()
