#!/usr/bin/env python3
import sys
import string
from collections import Counter


def solve(S: str):
    cnt = Counter(S)

    n_max = max([n for n in cnt.values()])

    for c in string.ascii_lowercase:
        if n_max == cnt[c]:
            print(c)
            return


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
