#!/usr/bin/env python3
from email.policy import default
import sys
from collections import defaultdict

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(N: int, M: int, T: int, A: "List[int]", X: "List[int]", Y: "List[int]"):

    bonus_dict = defaultdict(int)
    for x, y in zip(X, Y):
        bonus_dict[x - 1] = y

    curr_t = T

    for i, a in enumerate(A):
        curr_t -= a
        if curr_t <= 0:
            print(NO)
            return

        curr_t += bonus_dict[i + 1]

    print(YES)





# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    T = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N - 1)]  # type: "List[int]"
    X = [int()] * (M)  # type: "List[int]"
    Y = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        X[i] = int(next(tokens))
        Y[i] = int(next(tokens))
    solve(N, M, T, A, X, Y)

if __name__ == '__main__':
    main()
