#!/usr/bin/env python3
#https://atcoder.jp/contests/abc293/submissions/39647215

import sys
from collections import defaultdict
INF = float('inf')  # type: float

def mod_pow(x, y, mod):
    num = 1
    while y > 0:
        if y & 1:
            num = (num * x) % mod
        x = (x ** 2) % mod
        y >>= 1
    return num

def solve(A: int, X: int, M: int):

    if A == 1:
        print(X % M)
        sys.exit()

    max_pow = mod_pow(A, X, M*(A - 1))
    ans = (1 - max_pow) // (1 - A)
    ans %= M
    print(ans)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    A = int(next(tokens))  # type: int
    X = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    solve(A, X, M)

if __name__ == '__main__':
    main()
