#!/usr/bin/env python3
import sys


"""
def solve(N: int, Q: "List[int]", A: "List[int]", B: "List[int]"):

    sum_q = sum(Q)
    sum_a = sum(A)
    sum_b = sum(B)

    if sum_a > sum_b:
        sum_a, sum_b = sum_b, sum_a

    max_a = sum_q // sum_a

    ans = 0
    for n_a in range(max_a + 1):
        value = sum_a * n_a
        n_b = (sum_q - value) // sum_b
        ans = max(ans, n_a + n_b)

    print(ans)
"""

def solve(N: int, Q: "List[int]", A: "List[int]", B: "List[int]"):

    max_a = float("INF")
    for a, q in zip(A, Q):
        if a != 0:
            max_a = min(max_a, q // a)

    ans = 0
    for na in range(max_a + 1):
        is_ok = True
        nb = float("INF")
        for a, b, q in zip(A, B, Q):
            diff = q - a * na
            if diff < 0:
                is_ok = False
                break
            if b != 0:
                nb = min(nb, diff // b)
        if is_ok:
            ans = max(ans, na + nb)
    print(ans)


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    Q = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    B = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, Q, A, B)

if __name__ == '__main__':
    main()
