#!/usr/bin/env python3


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N, M = map(int, input().split())
    A = list(map(int, input().split()))
    B = list(map(int, input().split()))

    a_ans = []
    b_ans = []

    rank = 1

    a_idx = 0
    b_idx = 0
    while a_idx < N or b_idx < M:
        a_v = float("INF")
        b_v = float("INF")
        if a_idx < N:
            a_v = A[a_idx]

        if b_idx < M:
            b_v = B[b_idx]

        if a_v < b_v:
            a_ans.append(rank)
            a_idx += 1
        else:
            b_ans.append(rank)
            b_idx += 1

        rank += 1


    print(*a_ans)
    print(*b_ans)

if __name__ == '__main__':
    main()
