#!/usr/bin/env python3
import sys
from collections import deque
from bisect import bisect_left, bisect_right


def solve(N: int, M: int, S: "List[str]"):

    row_b = [[] for _ in range(N)]
    col_b = [[] for _ in range(M)]

    for i in range(N):
        for j in range(M):
            if S[i][j] == "#":
                row_b[i].append(j)

    for j in range(M):
        for i in range(N):
            if S[i][j] == "#":
                col_b[j].append(i)

    DIR = [(-1, 0), (1, 0), (0, -1), (0, 1)]

    sx, sy = 1, 1
    visited = [[False] * M for _ in range(N)]

    que = deque()
    que.append((sx, sy))
    visited[sy][sx] = True

    while que:
        cx, cy = que.popleft()

        nx, ny = None, None
        for dx, dy in DIR:
            if dy == 0:
                if dx == -1:
                    idx_x = bisect_left(row_b[cy], cx)
                    nx = row_b[cy][idx_x - 1] + 1
                    ny = cy

                else:
                    idx_x = bisect_left(row_b[cy], cx)
                    nx = row_b[cy][idx_x] - 1
                    ny = cy

            else:
                if dy == -1:
                    idx_y = bisect_left(col_b[cx], cy)
                    ny = col_b[cx][idx_y - 1] + 1
                    nx = cx
                else:
                    idx_y = bisect_left(col_b[cx], cy)
                    ny = col_b[cx][idx_y] - 1
                    nx = cx

            if not visited[ny][nx]:
                que.append((nx, ny))

            if dy == 0:
                for x in range(min(cx, nx), max(cx, nx) + 1):
                    visited[ny][x] = True
            else:
                for y in range(min(cy, ny), max(cy, ny) + 1):
                    visited[y][nx] = True

    ans = 0
    for v in visited:
        ans += v.count(True)
    print(ans)




# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    S = [next(tokens) for _ in range(N)]  # type: "List[str]"
    solve(N, M, S)

if __name__ == '__main__':
    main()
