#!/usr/bin/env python3

"""
import itertools
def solve_old(h: "List[int]", w: "List[int]"):

    ans = 0

    for h1_i in range(1, h[0]-2):
        for h1_j in range(1, h1_i-1):
            h1_k = h[0] - h1_i - h1_j

            h1 = set([h1_i, h1_j, h1_k])

            for v in itertools.product(h1, h1, h1):
                h1_1, h1_2, h1_3 = v

                w1_i = h1_1
                for w1_j in range(1, w[0] - w1_i - 1):
                    w1_k = w[0] - w1_i - w1_j
                    w1 = [w1_i, w1_j, w1_k]

                    w2_i = h1_2
                    for w2_j in range(1, w[1] - w2_i - 1):
                        w2_k = w[1] - w2_i - w2_j
                        w2 = [w2_i, w2_j, w2_k]

                        w3_i = h1_3
                        for w3_j in range(1, w[2] - w3_i - 1):
                            w3_k = w[2] - w3_i - w3_j
                            w3 = [w3_i, w3_j, w3_k]

                            if (w1[1] + w2[1] + w3[1] == w[1]) and (w1[2] + w2[2] + w3[2] == w[2]):
                                ans += 1

    print(ans)
"""
import sys

def solve(h: "List[int]", w: "List[int]"):

    ans = 0
    for m_11 in range(1, max(h[0], w[0])):
        for m_12 in range(1, max(h[0], w[1])):
            for m_21 in range(1, max(h[1], w[0])):
                for m_22 in range(1, max(h[0], w[1])):
                    m_13 = h[0] - m_11 - m_12
                    m_23 = h[1] - m_21 - m_22
                    m_31 = w[0] - m_11 - m_21
                    m_32 = w[1] - m_12 - m_22
                    m_33 = w[2] - m_13 - m_23
                    if min(m_13, m_23, m_31, m_32, m_33) > 0 and m_31 + m_32 + m_33 == h[2]:
                        ans += 1
    print(ans)




# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    h = [int(next(tokens)) for _ in range(3)]  # type: "List[int]"
    w = [int(next(tokens)) for _ in range(3)]  # type: "List[int]"
    solve(h, w)

if __name__ == '__main__':
    main()
