#!/usr/bin/env python3
from collections import deque


def solve():
    N, M = map(int,input().split())
    c_list = list(map(int,input().split()))
    edges = [[] for _ in range(N)]
    for _ in range(M):
        u, v = map(int,input().split())
        u, v = u-1, v-1
        edges[u].append(v)
        edges[v].append(u)

    if c_list[0] == c_list[N - 1]:
        print(-1)
        return

    q = deque()
    q.append((0, N-1, 0))
    is_visited = [[False] * N for _ in range(N)]
    is_visited[0][N-1] = True

    while q:
        ti, ai, d = q.popleft()

        if ti == N - 1 and ai == 0:
            print(d)
            return

        for tn in edges[ti]:
            for an in edges[ai]:
                if is_visited[tn][an] or (c_list[tn] == c_list[an]):
                    continue
                q.append((tn, an, d + 1))
                is_visited[tn][an] = True


    print(-1)

# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():

    INF = float('INF')
    T = int(input())

    for _ in range(T):
        solve()


if __name__ == '__main__':
    main()
