#!/usr/bin/env python3

from heapq import heappop, heappush

def dijkstra(edges, n_node, start, c_list):
    dist = [float('Inf')] * n_node
    used = [False] * n_node

    dist[start] = 0
    used[start] = True
    queue = [(dist[start], start)]

    weight = 1
    while queue:
        _, now = heappop(queue)
        used[now] = True
        for next in edges[now]:
            #if c_list[now] == c_list[next]: continue
            if (not used[next]) and (dist[now] + weight < dist[next]):
                dist[next] = dist[now] + weight
                heappush(queue, (dist[next], next))
    return dist


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():

    T = int(input())

    for t in range(T):
        N, M = map(int,input().split())
        c_list = list(map(int,input().split()))
        edges = [[] for _ in range(N)]
        for _ in range(M):
            u, v = map(int,input().split())
            u, v = u-1, v-1
            edges[u].append(v)
            edges[v].append(u)

        taka_dist = dijkstra(edges, N, 0, c_list)
        aoki_dist = dijkstra(edges, N, N - 1, c_list)

        res = abs(taka_dist[N - 1] - aoki_dist[0])
        if res % 2 != 0:
            #print(-1)
            pass
        print(t)
        print(taka_dist)
        print(aoki_dist)
        print()







if __name__ == '__main__':
    main()
