
#!/usr/bin/env python3
from heapq import heappop, heappush
from collections import defaultdict

class Multiset:

    def __init__(self, is_delete=True):
        self.len = 0
        self.f = defaultdict(int)
        self.pos = []
        self.neg = []
        self.is_delete = is_delete

    def _delete(self, key):
        if self.is_delete and self.f[key] == 0:
            del self.f[key]

    def exist(self, key):
        if self.f.get(key) is None:
            return False
        else:
            return True

    def add(self, x, key=None):
        if key is None:
            key = x
        self.len += 1
        heappush(self.pos, (x, key))
        heappush(self.neg, (-x, key))
        self.f[key] += 1

    def pop_max(self, is_return_key=False):
        while True:
            x, key = heappop(self.neg)
            if self.f[key]:
                self.f[key] -= 1
                self.len -= 1
                self._delete(key)
                if is_return_key:
                    return -x, key
                else:
                    return x

    def pop_min(self, is_return_key=False):
        while True:
            x, key = heappop(self.pos)
            if self.f[key]:
                self.f[key] -= 1
                self.len -= 1
                self._delete(key)
                if is_return_key:
                    return x, key
                else:
                    return x

    def search_max(self, is_return_key=False):
        while True:
            x, key = self.neg[0]
            if self.f[key]:
                if is_return_key:
                    return -x, key
                else:
                    return -x
            else:
                heappop(self.neg)

    def search_min(self, is_return_key=False):
        while True:
            x, key = self.pos[0]
            if self.f[key]:
                if is_return_key:
                    return x, key
                else:
                    return x
            else:
                heappop(self.pos)

    def erase(self, key):
        if self.exist(key):
            self.f[key] -= 1
            self._delete(key)
            self.len -= 1



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    query_num = int(input())
    query_list = [list(map(int, input().split())) for _ in range(query_num)]

    multiset = Multiset()

    for q in query_list:
        if q[0] == 1:
            multiset.add(q[1])
        elif q[0] == 2:
            for _ in range(q[2]):
                if not multiset.exist(q[1]):
                    break
                multiset.erase(q[1])
        else:
            print(multiset.search_max() - multiset.search_min())



if __name__ == '__main__':
    main()
