#!/usr/bin/env python3
import sys
import itertools
from collections import defaultdict

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(N: int, R: str, C: str):

    pattern_set = set()
    for pattern in itertools.permutations("ABC..", N):
        if pattern in pattern_set: continue
        pattern_set.add("".join(pattern))

    col_check_idx = [False] * N
    field = [" " * N] * N

    def col_check_line(pattern):
        nonlocal col_check_idx
        stock = col_check_idx.copy()
        for idx, flg in enumerate(col_check_idx):
            if flg: continue
            if pattern[idx] == ".": continue
            if pattern[idx] == C[idx]:
                stock[idx] = True
                continue
            else:
                return False

        col_check_idx = stock.copy()
        return True

    def row_check_line(i, pattern):
        pattern_wo_space = pattern.replace(".", "")
        return pattern_wo_space[0] == R[i]

    def row_unique_check():
        nonlocal field
        for i in range(N):
            cnt = defaultdict(int)
            for j in range(N):
                cnt[field[j][i]] += 1
            for c in "ABC":
                if cnt[c] != 1:
                    return False
        return True

    field = None
    is_ok = False

    def dfs(cnt=0):
        nonlocal col_check_idx, field, is_ok
        if cnt == N:
            if sum(col_check_idx) == N and row_unique_check():
                is_ok = True
                print(YES)
                for line in field:
                    print(line)
                exit()
            return

        # init & backup var
        if cnt == 0:
            col_check_idx, prev_col_check_idx = [False] * N, [False] * N
            field, prev_field = [" " * N] * N, [" " * N] * N
        else:
            prev_col_check_idx = col_check_idx.copy()
            prev_field = field.copy()

        # dfs process
        for pattern in pattern_set:
            if not col_check_line(pattern):
                continue
            if not row_check_line(cnt, pattern):
                continue

            field[cnt] = pattern
            dfs(cnt + 1)

            # remove var
            col_check_idx = prev_col_check_idx.copy()
            field = prev_field.copy()

    dfs()
    print(NO)




# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    R = next(tokens)  # type: str
    C = next(tokens)  # type: str
    solve(N, R, C)

if __name__ == '__main__':
    main()
