#!/usr/bin/env python3
import sys
from collections import defaultdict

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(N: int, R: str, C: str):

    board = [[""] * N for _ in range(N)]

    row = [defaultdict(int) for _ in range(N)]
    col = [defaultdict(int) for _ in range(N)]

    for i in range(N):
        if i == 0 and (R[i] != C[i]):
            print(NO)
            return
        board[i][0] = R[i]
        board[0][i] = C[i]

    def row_counter(row_idx):
        cnt = defaultdict(int)
        for i in range(N):
            cnt[board[i][row_idx]] += 1
        return cnt

    def col_counter(col_idx):
        cnt = defaultdict(int)
        for i in range(N):
            cnt[board[col_idx][i]] += 1
        return cnt

    row = [row_counter(i) for i in range(N)]
    col = [col_counter(i) for i in range(N)]

    def row_preprocess():
        nonlocal board, row, col
        counter = defaultdict(int)
        for i in range(N):
            c = board[i][0]
            if row[0][c] > 1: counter[c] += 1
            if counter[c] > 1:
                j = 1
                while True:
                    if j >= N: return False
                    if row[j][c] == 0:
                        for t in range(j):
                            board[i][t] = "*"
                        #board[i][0] = ""
                        board[i][j] = c
                        row[0] = row_counter(0)
                        row[j] = row_counter(j)
                        break
                    j += 1

    def col_preprocess():
        nonlocal board, row, col
        counter = defaultdict(int)
        for i in range(N):
            c = board[0][i]
            if col[0][c] > 1: counter[c] += 1
            if counter[c] > 1:
                j = 1
                while True:
                    if j >= N: return False
                    if col[j][c] == 0:
                        for t in range(j):
                            board[t][i] = "*"
                        #board[0][i] = "*"
                        board[j][i] = c
                        col[0] = col_counter(0)
                        col[j] = col_counter(j)
                        break
                    j += 1

    if row_preprocess():
        print(NO)
        return
    if col_preprocess():
        print(NO)
        return

    """
    for c in ["A", "B", "C"]:
        row_ids = [i for i in range(N) if row[i][c] != 1]
        col_ids = [i for i in range(N) if col[i][c] != 1]

        if len(row_ids) != len(col_ids):
            print(NO)
            return

        for ri, ci in zip(row_ids, col_ids):
            board[ri][ci] = c
            col[ci] = col_counter(ci)
            row[ri] = row_counter(ri)
    """

    print(YES)
    for b in board:
        line = "".join(b)
        line = line.replace("*", ".")
        print(line)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    R = next(tokens)  # type: str
    C = next(tokens)  # type: str
    solve(N, R, C)

if __name__ == '__main__':
    main()
