#!/usr/bin/env python3
import sys
from collections import defaultdict
INF = float('inf')  # type: float


def solve(N: int):

    x = N // 5

    diff1 = abs(N - x * 5)
    diff2 = abs(N - (x + 1) * 5)
    if diff1 < diff2:
        print(x * 5)
    else:
        print((x + 1) * 5)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
