#!/usr/bin/env python3
import sys


def solve(H: int, W: int, K: int, S: "List[str]"):
    # 0: . 1: o, 2: x
    cumsum_lat = [[[0 for _ in range(W)] for _ in range(H + 1)] for _ in range(3)]
    cumsum_lon = [[[0 for _ in range(W + 1)] for _ in range(H)] for _ in range(3)]

    code = {".": 0, "o": 1, "x": 2}

    for i in range(H):
        for j in range(W):
            for k in range(3):
                cumsum_lon[k][i][j + 1] = cumsum_lon[k][i][j]
                cumsum_lat[k][i + 1][j] = cumsum_lat[k][i][j]
            c = code[S[i][j]]
            cumsum_lon[c][i][j + 1] += 1
            cumsum_lat[c][i + 1][j] += 1

    ans = float("INF")
    for i in range(H):
        for j in range(W):
            # check lat
            if i <= H - K:
                x_cnt = cumsum_lat[code["x"]][i + K][j] - cumsum_lat[code["x"]][i][j]
                if x_cnt == 0:
                    d_cnt = cumsum_lat[code["."]][i + K][j] - cumsum_lat[code["."]][i][j]
                    ans = min(ans, d_cnt)

            # check lon
            if j <= W - K:
                x_cnt = cumsum_lon[code["x"]][i][j + K] - cumsum_lon[code["x"]][i][j]
                if x_cnt == 0:
                    d_cnt = cumsum_lon[code["."]][i][j + K] - cumsum_lon[code["."]][i][j]
                    ans = min(ans, d_cnt)

    if ans == float("INF"):
        print(-1)
    else:
        print(ans)


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    H = int(next(tokens))  # type: int
    W = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    S = [next(tokens) for _ in range(H)]  # type: "List[str]"
    solve(H, W, K, S)

if __name__ == '__main__':
    main()
