#!/usr/bin/env python3
import sys


def solve(N: int, S: str, W: "List[int]"):

    v_list = [[W[i], int(S[i])] for i in range(N)]

    v_list.sort()

    one_cumsum = [0] * (N + 1)
    zero_cumsum = [0] * (N + 1)
    for i, v in enumerate(v_list):
        if v[1] == 1:
            one_cumsum[i + 1] = one_cumsum[i] + 1
            zero_cumsum[i + 1] = zero_cumsum[i]
        else:
            zero_cumsum[i + 1] = zero_cumsum[i] + 1
            one_cumsum[i + 1] = one_cumsum[i]


    """
    left_idx = 0
    right_idx = N

    while left_idx < right_idx - 1:
        mid_idx = (left_idx + right_idx) // 2

        r_zero_cnt = zero_cumsum[right_idx]
        r_one_cnt = one_cumsum[-1] - one_cumsum[right_idx]
        r_cnt = r_zero_cnt + r_one_cnt

        l_zero_cnt = zero_cumsum[left_idx]
        l_one_cnt = one_cumsum[-1] - one_cumsum[left_idx]
        l_cnt = l_zero_cnt + l_one_cnt

        mid_zero_cnt = zero_cumsum[mid_idx]
        mid_one_cnt = one_cumsum[-1] - one_cumsum[mid_idx]
        mid_cnt = mid_zero_cnt + mid_one_cnt

        print('/////////')
        print(zero_cumsum)
        print(one_cumsum)
        print(left_idx, mid_idx, right_idx)
        print(l_cnt, mid_cnt, r_cnt)

        if mid_cnt <= r_cnt:
            left_idx = mid_idx
        else:
            right_idx = mid_idx

    print(max(l_cnt, r_cnt))
    """



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    W = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, S, W)

if __name__ == '__main__':
    main()
