#!/usr/bin/env python3
import sys
from collections import Counter


def solve(N: int, S: str, W: "List[int]"):

    v_list = [[W[i], int(S[i])] for i in range(N)]

    v_list.sort()

    w_list = sorted(list(set(W)))

    one_list = []
    zero_list = []

    for i, v in enumerate(v_list):
        if v[1] == 1:
            one_list.append(v[0])
        else:
            zero_list.append(v[0])

    one_counter = Counter(one_list)
    zero_counter = Counter(zero_list)

    n_w = len(w_list)
    one_cumsum = [0] * (n_w + 1)
    zero_cumsum = [0] * (n_w + 1)
    for i, w in enumerate(w_list):
        one_cumsum[i + 1] = one_counter[w] + one_cumsum[i]
        zero_cumsum[i + 1] = zero_counter[w] + zero_cumsum[i]


    ans = 0
    #print(v_list)
    #print(zero_cumsum)
    #print(one_cumsum)
    for i in range(n_w):
        zero_cnt = zero_cumsum[i + 1]
        one_cnt = one_cumsum[-1] - one_cumsum[i + 1]
        ans = max(ans, zero_cnt + one_cnt)
        #print(ans, i, zero_cnt, one_cnt)

    print(ans)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    W = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, S, W)

if __name__ == '__main__':
    main()
