#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque, Counter
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1


def solve(S: str):
    cnt = Counter(S)
    n = max([a for a in cnt.values()])

    ss = []
    for c, v in cnt.items():
        if v == n:
            ss.append(c)

    ans = S
    for c in ss:
        ans = ans.replace(c, "")
    print(ans)


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
