#!/usr/bin/env python3
import heapq
from collections import defaultdict

# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N = int(input())
    Q = int(input())

    q_list = [list(map(int, input().split())) for _ in range(Q)]

    box_dict = defaultdict(list)
    card_dict = defaultdict(set)

    for q in q_list:
        if q[0] == 1:
            i, j = q[1:]
            #heapq.heappush(card_dict[i], j)
            #heapq.heappush(box_dict[j], i)
            card_dict[i].add(j)
            box_dict[j].append(i)
        elif q[0] == 2:
            j = q[-1]
            print(*sorted(box_dict[j]))
        else:
            i = q[-1]
            print(*sorted(card_dict[i]))

        #print(card_dict)
        #print(box_dict)
        #print("---")




if __name__ == '__main__':
    main()
