#!/usr/bin/env python3
import sys


def solve(N: int, A: "List[List[int]]"):

    for i in range(N):
        ans_list = []
        for j in range(N):
            if A[i][j] == 1:
                ans_list.append(j + 1)
        print(*ans_list)

# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [[int(next(tokens)) for _ in range(N)] for _ in range(N)]  # type: "List[List[int]]"
    solve(N, A)

if __name__ == '__main__':
    main()
