#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1

YES = "Yes"  # type: str
NO = "No"  # type: str


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N, M, K = map(int, input().split())
    H = list(map(int, input().split()))
    B = list(map(int, input().split()))
    
    H.sort()
    B.sort()


    def calc():
        i_b = 0
        cnt = 0
        for i_h, h in enumerate(H):
            is_ok = False
            while not is_ok and i_b < M:
                b = B[i_b]
                if h <= b:
                    cnt += 1
                    is_ok = True
                i_b += 1

            if i_b >= M:
                break
            
        return cnt


    if calc() >= K:
        print(YES)
    else:
        print(NO)

if __name__ == '__main__':
    main()
