#!/usr/bin/env python3
import sys
from collections import defaultdict


NO = "Impossible"  # type: str
INF = float('inf')  # type: float


def solve(N: int, A: "List[int]", S: "List[str]", Q: int, U: "List[int]", V: "List[int]"):

    costs = [[0] * N for _ in range(N)]
    dists = [[INF] * N for _ in range(N)]

    for i in range(N):
        for j in range(N):
            if i == j:
                dists[i][j] = 0
            elif S[i][j] == "Y":
                costs[i][j] = A[j]
                dists[i][j] = 1

    # warshall_floyd
    for k in range(N):
        for i in range(N):
            for j in range(N):
                dist = dists[i][k] + dists[k][j]
                cost = costs[i][k] + costs[k][j]
                if ((dists[i][j] > dist) or
                    (dists[i][j] == dist and costs[i][j] < cost)
                ):
                    costs[i][j] = cost
                    dists[i][j] = dist

    for u, v in zip(U, V):
        if dists[u][v] == INF:
            print(NO)
        else:
            print(dists[u][v], costs[u][v] + A[u])



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    S = [next(tokens) for _ in range(N)]  # type: "List[str]"
    Q = int(next(tokens))  # type: int
    U = [int()] * (Q)  # type: "List[int]"
    V = [int()] * (Q)  # type: "List[int]"
    for i in range(Q):
        U[i] = int(next(tokens)) - 1
        V[i] = int(next(tokens)) - 1
    solve(N, A, S, Q, U, V)

if __name__ == '__main__':
    main()
