#!/usr/bin/env python3

YES = "Yes"  # type: str
NO = "No"  # type: str


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    origin_polys = [[] for _ in range(3)]
    for i in range(3):
        for _ in range(4):
            origin_polys[i].append(input())

    base_polys_pos = [[] for _ in range(3)]
    for idx, origin_poly in enumerate(origin_polys):
        base = None
        for y in range(4):
            for x in range(4):
                if origin_poly[y][x] == "#":
                    if base is None:
                        base = (x, y)
                        base_polys_pos[idx].append((0, 0))
                    else:
                        pos = (x - base[0], y - base[1])
                        base_polys_pos[idx].append(pos)

    #for pos in base_polys_pos:
    #    print(pos)

    def transform(poly_pos, n_rot, sx, sy):
        def rotate(x, y, n_rot):
            nx, ny = x, y
            for _ in range(n_rot):
                nx, ny = -ny, nx
            return nx, ny

        trans_pos = []
        for x, y in poly_pos:
            nx, ny = rotate(x, y, n_rot)
            nx += sx
            ny += sy
            trans_pos.append((nx, ny))
        return trans_pos

    def is_out(poly_pos):
        for x, y in poly_pos:
            if x < 0 or y < 0 or x >=4 or y >= 4:
                return True
        return False

    def process(infos):
        field = [[0] * 4 for _ in range(4)]
        for idx in range(3):
            info = infos[idx]
            poly_pos = base_polys_pos[idx]
            trans_poly_pos = transform(poly_pos, info[0], info[1], info[2])
            if is_out(trans_poly_pos):
                return False
            for x, y in trans_poly_pos:
                field[y][x] += 1
        for i in range(4):
            for j in range(4):
                if field[i][j] != 1:
                    return False
        return True

    def update(x_index):
        x_index[2] += 1
        if x_index[2] >= 4:
            x_index[2] = 0
            x_index[1] += 1
            if x_index[1] >= 4:
                x_index[1] = 0
                x_index[0] += 1
                if x_index[0] >= 4:
                    return False
        return True

    # rot, sx, sy
    a_info = [0, 0, 0]
    while True:
        # rot, sx, sy
        b_info = [0, 0, 0]
        while True:
            # rot, sx, sy
            c_info = [0, 0, 0]
            while True:
                if process([a_info, b_info, c_info]):
                    print(YES)
                    return
                if not update(c_info):
                    break
            if not update(b_info):
                break
        if not update(a_info):
            break

    print(NO)


if __name__ == '__main__':
    main()
