#!/usr/bin/env python3
import sys
import string

def solve(N: int, K: int, S: str):
    
    char_list = list(string.ascii_lowercase)
    char_dict = {c: i for i, c in  enumerate(char_list)}

    table = [[0]*len(char_list) for _ in range(N)]

    for i in range(N - 1, -1, -1):
        for c in char_list:
            if i == N - 1:
                if c == S[i]:
                    table[i][char_dict[c]] = i
                else:
                    table[i][char_dict[c]] = float('INF')
            else:
                if c == S[i]:
                    table[i][char_dict[c]] = i
                else:
                    table[i][char_dict[c]] = table[i + 1][char_dict[c]]
    
    
    ans = ''
    pos = 0
    for k in range(K):
        for i, c in enumerate(table[pos]):
            if N - c >= K - k:
                ans += char_list[i]
                pos = (c + 1)
                break


    print(ans)




# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    solve(N, K, S)

if __name__ == '__main__':
    main()
