#!/usr/bin/env python3
import sys


def solve(B: int):

    a = 1
    while True:
        aa = a ** a
        if aa == B:
            print(a)
            return
        if aa > B:
            print(-1)
            return
        a += 1


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    B = int(next(tokens))  # type: int
    solve(B)

if __name__ == '__main__':
    main()
