#!/usr/bin/env python3
import sys
from collections import defaultdict

def solve(N: int, U: "List[int]", V: "List[int]"):
    edges = [[] for i in range(N)]

    for u, v in zip(U, V):
        u -= 1
        v -= 1
        edges[u].append(v)
        edges[v].append(u)

    deg = [0] * N
    for i in range(N):
        deg[i] = len(edges[i])

    deg_freq = defaultdict(int)

    for d in deg:
        deg_freq[d] += 1

    ans = []
    n_used = 0

    # レベル3以上の処理
    for key, value in deg_freq.items():
        if key >= 3:
            n_used += (key + 1) * value
            ans += [key] * value

    # レベル2の処理
    ans += [2] * ((N - n_used) // 3)
    ans.sort()

    print(*ans)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    u = [int()] * (N - 1)  # type: "List[int]"
    v = [int()] * (N - 1)  # type: "List[int]"
    for i in range(N - 1):
        u[i] = int(next(tokens))
        v[i] = int(next(tokens))
    solve(N, u, v)

if __name__ == '__main__':
    main()
