#!/usr/bin/env python3
import sys

from itertools import combinations

def solve(N: int, M: int, a: "List[List[int]]"):

    pairs = set()
    for i in range(M):
        for j in range(N - 1):
            min_h = min(a[i][j], a[i][j + 1])
            max_h = max(a[i][j], a[i][j + 1])
            pairs.add((min_h, max_h))

    n_max = len(list(combinations(list(range(N)), 2)))
    print(n_max - len(pairs))



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    a = [[int(next(tokens)) for _ in range(N)] for _ in range(M)]  # type: "List[List[int]]"
    solve(N, M, a)

if __name__ == '__main__':
    main()
