#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str


def solve(S: "List[str]", T: "List[str]"):
    
    n_diff = 0
    for s, t in zip(S, T):
        if s != t:
            n_diff += 1
    
    if n_diff == 0 or n_diff == 3:
        print("Yes")
    else:
        print("No")


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = [next(tokens) for _ in range(3)]  # type: "List[str]"
    T = [next(tokens) for _ in range(3)]  # type: "List[str]"
    solve(S, T)

if __name__ == '__main__':
    main()
