#!/usr/bin/env python3
import sys


def solve(N: int):

    def base10int(value, base):
        if (int(value / base)):
            return base10int(int(value / base), base) + str(value % base)
        return str(value % base)

    value = base10int(N - 1, 5)

    ans = ""
    for c in value:
        ans += str(int(c) * 2)

    print(ans)

# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
