#!/usr/bin/env python3
import sys
from collections import defaultdict
INF = float('inf')  # type: float


def solve(N: int, S: "List[str]", A: "List[int]"):

    min_idx = INF
    min_a = INF
    for i, a in enumerate(A):
        if min_a > a:
            min_a = a
            min_idx = i

    curr_i = min_idx
    for i in range(N):
        print(S[curr_i])
        curr_i += 1
        curr_i %= N



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = [str()] * (N)  # type: "List[str]"
    A = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        S[i] = next(tokens)
        A[i] = int(next(tokens))
    solve(N, S, A)

if __name__ == '__main__':
    main()
