#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


import string


def solve(S: str):

    big = set(string.ascii_uppercase)
    #small = set(string.ascii_lowercase)

    if S[0] not in big:
        print(NO)
        return

    for c in S[1:]:
        if c in big:
            print(NO)
            return
    print(YES)


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
