#!/usr/bin/env python3
import sys


def solve(N: int, A: "List[str]"):

    for i in range(N):
        for j in range(i, N):
            if i == j: continue

            value = A[i][j]
            inv_value = A[j][i]

            if value == 'D':
                if inv_value != 'D':
                    print('incorrect')
                    return

            else:
                if value == 'W':
                    if inv_value != 'L':
                        print('incorrect')
                        return
                elif value == 'L':
                    if inv_value != 'W':
                        print('incorrect')
                        return

    print('correct')




# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [next(tokens) for _ in range(N)]  # type: "List[str]"
    solve(N, A)

if __name__ == '__main__':
    main()
