#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
#import pypyjit
#pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

# sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1


def create_cost(N, S):
    cost_row = [[0] * (N + 1) for _ in range(N)]
    cost_col = [[0] * N for _ in range(N + 1)]
    for r in range(N):
        for c in range(N):
            cost_row[r][c + 1] = cost_row[r][c] + int(S[r][c] == "#")
    
    for r in range(N):
        for c in range(N):
            cost_col[r + 1][c] = cost_col[r][c] + int(S[r][c] == "#")
    
    return cost_row, cost_col


def solve(N: int, S: list[str]):
    # 縦方向に反転して見通しをよくする
    S = S[::-1]

    cost_row, cost_col = create_cost(N, S)

    """
    def disp_a():
        for s in S: print(s)
        print()
        for s in cost_row: print(s)
        print()
        for s in cost_col: print(s)
        print()
    disp_a()
    """
    
    dp = [[INF] * (N + 1) for _ in range(N + 1)]

    dp[0][0] = 0

    for i in range(N + 1):      # 縦方向
        for j in range(N + 1):  # 横方向
            if i < N:
                dp[i + 1][j] = min(dp[i + 1][j], dp[i][j] + cost_row[i][j])
            if j < N:
                dp[i][j + 1] = min(dp[i][j + 1], dp[i][j] + (i - cost_col[i][j]))

    """
    def disp_b():
        for s in dp:
            print(s)
    disp_b()
    """

    print(dp[-1][-1]) 


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = [next(tokens) for _ in range(N)]  # type: list[str]
    solve(N, S)

if __name__ == '__main__':
    main()
