#!/usr/bin/env python3
import sys
import string

from collections import defaultdict
INF = float('inf')  # type: float


def solve(S: str):
    upper_set = set(string.ascii_uppercase)

    for i, s in enumerate(S):
        if s in upper_set:
            print(i + 1)
            break


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
