#!/usr/bin/env python3
import bisect


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N,Q = map(int, input().split())
    R = list(map(int, input().split()))

    QUERY = [int(input()) for _ in range(Q)]

    R.sort()

    r_cumsum = [0]
    for r in R:
        r_cumsum.append(r_cumsum[-1] + r)


    for x in QUERY:
        ind = bisect.bisect_right(r_cumsum, x)
        print(ind - 1)


if __name__ == '__main__':
    main()
