#!/usr/bin/env python3
import sys
import bisect


def solve(N: int, A: "List[int]", Q: int, B: "List[int]"):
    
    A.sort()

    for b in B:
        
        idx = 0
        if len(A) > 1:
            idx = bisect.bisect(A, b)

        left_dist = float('INF')
        right_dist = float('INF')

        if idx != 0:
            left_dist = abs(b - A[idx - 1])
        if idx != N:
            right_dist = abs(b - A[idx])

        print(min(left_dist, right_dist))
        



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    Q = int(next(tokens))  # type: int
    B = [int(next(tokens)) for _ in range(Q)]  # type: "List[int]"
    solve(N, A, Q, B)

if __name__ == '__main__':
    main()
