#!/usr/bin/env python3
import sys


def solve(N: int, lx: "List[int]", ly: "List[int]", rx: "List[int]", ry: "List[int]"):

    L_MAX = 1001
    field = [[0] * L_MAX for _ in range(L_MAX)]

    for _lx, _ly, _rx, _ry in zip(lx, ly, rx, ry):
        field[_ly][_lx] += 1
        field[_ry][_rx] += 1
        field[_ly][_rx] -= 1
        field[_ry][_lx] -= 1

    for i in range(1, L_MAX):
        for j in range(L_MAX):
            field[i][j] += field[i - 1][j]

    for i in range(1, L_MAX):
        for j in range(L_MAX):
            field[j][i] += field[j][i - 1]

    ans_list = [0] * (10 ** 5 + 1)
    for i in range(L_MAX):
        for j in range(L_MAX):
            if field[i][j] > 0:
                ans_list[field[i][j]] += 1


    for i in range(1, N + 1):
        print(ans_list[i])




# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    lx = [int()] * (N)  # type: "List[int]"
    ly = [int()] * (N)  # type: "List[int]"
    rx = [int()] * (N)  # type: "List[int]"
    ry = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        lx[i] = int(next(tokens))
        ly[i] = int(next(tokens))
        rx[i] = int(next(tokens))
        ry[i] = int(next(tokens))
    solve(N, lx, ly, rx, ry)

if __name__ == '__main__':
    main()
