#!/usr/bin/env python3
import sys
#sys.setrecursionlimit(10**4)

def solve(N: int, X: int, Y: int):
    if N == 1:
        print(0)
        return

    RED = 1
    BLUE = 2
    def calc(n, v=1, color=RED):
        if n == 1:
            if color == RED:
                return 0
            else:
                return v
        elif n == 2:
            if color == RED:
                return v*X*Y
            else:
                return v*Y
        else:
            if color == RED:
                return calc(n - 1, v + v*X, RED) + calc(n - 1, v*X*Y, BLUE)
            else:
                return calc(n - 1, v, RED) + calc(n - 1, v*Y, BLUE)


    print(calc(N))





# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    X = int(next(tokens))  # type: int
    Y = int(next(tokens))  # type: int
    solve(N, X, Y)

if __name__ == '__main__':
    main()
