#!/usr/bin/env python3
import sys
from collections import defaultdict

MOD = 998244353  # type: int
INF = float('inf')  # type: float


def make_divisors(n):
    lower_divisors , upper_divisors = [], []
    i = 1
    while i*i <= n:
        if n % i == 0:
            lower_divisors.append(i)
            if n != n // i and i != n // i:

                upper_divisors.append(n//i)
        i += 1
    return lower_divisors + upper_divisors[::-1]


def solve(N: int, S: str):
    divs = make_divisors(N)

    ans = 1
    for div in divs:
        if div == 1:
            continue
        dp = [True] * div
        for i in range(N):
            if S[i] == ".":
                dp[i % div] = False

        # TODO: 重複を削除できていない(例えば、6周期と3周期だとパターンが重複する可能性がある)
        cnt = sum(dp)
        if cnt > 0:
            ans += 2 ** (cnt) - 1
        print(dp)

    print(ans)

# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    solve(N, S)

if __name__ == '__main__':
    main()
