#!/usr/bin/env python3
import sys
from collections import defaultdict

MOD = 998244353  # type: int
INF = float('inf')  # type: float


def make_divisors(n, is_include_n=False):
    lower_divisors , upper_divisors = [], []
    i = 1
    while i * i <= n:
        if n % i == 0:
            lower_divisors.append(i)
            if not is_include_n and n == n // i:
                pass
            elif i != n // i:
                upper_divisors.append(n//i)
        i += 1
    return lower_divisors + upper_divisors[::-1]


def solve(N: int, S: str):

    div_dict = defaultdict(list)
    for div in make_divisors(N):
        div_dict[div] = make_divisors(div)

    cnt_dict = defaultdict(int)
    for div in div_dict.keys():
        dp = [True] * div
        for i in range(N):
            if S[i] == ".":
                dp[i % div] = False

        n_pow = sum(dp)
        cnt = 2 ** n_pow
        for num in div_dict[div]:
            cnt -= cnt_dict[num]
            cnt %= MOD
        cnt_dict[div] = cnt

    ans = 0
    for num in cnt_dict.values():
        ans += num
        ans %= MOD
    print(ans)


def solve_other(N: int, S: str):

    cnt_dict = defaultdict(int)
    for n in range(1, N):
        if N % n != 0:
            continue

        dp = [True] * n
        for i in range(N):
            if S[i] == ".":
                dp[i % n] = False

        n_pow = sum(dp)
        cnt = 2 ** n_pow
        for d in range(1, n):
            if n % d != 0:
                continue
            cnt -= cnt_dict[d]
            cnt %= MOD
        cnt_dict[n] = cnt

    ans = 0
    for num in cnt_dict.values():
        ans += num
        ans %= MOD

    print(ans)

# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    solve(N, S)

if __name__ == '__main__':
    main()
