#!/usr/bin/env python3
import sys
from collections import defaultdict
from heapq import heappop, heappush

INF = float('inf')  # type: float


def solve(N: int, M: int, P: "List[int]", L: "List[int]", D: "List[int]"):

    LD = [(l, d) for l, d in zip(L, D)]

    P.sort()
    LD.sort()

    que = []
    idx = 0

    ans = 0
    for p in P:

        while idx < M and LD[idx][0] <= p:
            heappush(que, LD[idx][1] * -1)
            idx += 1
        ans += p
        if que:
            ans += heappop(que)

    print(ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    P = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    L = [int(next(tokens)) for _ in range(M)]  # type: "List[int]"
    D = [int(next(tokens)) for _ in range(M)]  # type: "List[int]"
    solve(N, M, P, L, D)

if __name__ == '__main__':
    main()
