#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(N: int, A: "List[int]"):

    a_sum = sum(A)
    c_a = A + A
    c_a_cumsum = [0] * (2 * N + 1)
    for i in range(len(c_a)):
        c_a_cumsum[i + 1] = c_a[i] + c_a_cumsum[i]

    head_i = 0
    tail_i = 1
    while head_i < N:
        curr = c_a_cumsum[tail_i] - c_a_cumsum[head_i]
        if curr * 10 == a_sum:
            print(YES)
            return
        elif curr * 10 > a_sum:
            head_i += 1
        else:
            tail_i += 1
    print(NO)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, A)

if __name__ == '__main__':
    main()
