#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1

MOD = 998244353  # type: int


def cumsum_1d(data: list[int]) -> list[int]:
    n = len(data)
    cumsum_data = [0] * (n + 1)
    for i in range(n):
        cumsum_data[i + 1] = data[i] + cumsum_data[i]
    return cumsum_data


def solve(N: int, M: int, A: list[int], B: list[int]):
    
    A.sort()
    B.sort()

    a_cumsum = cumsum_1d(A)

    ans = 0
    for b in B:
        ind = bisect_left(A, b)
        ans += (ind * b - a_cumsum[ind]) % MOD
        ans += ((a_cumsum[-1] - a_cumsum[ind]) - (N - ind) * b) % MOD
        ans %= MOD

    print(ans)



# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: list[int]
    B = [int(next(tokens)) for _ in range(M)]  # type: list[int]
    solve(N, M, A, B)

if __name__ == '__main__':
    main()
