#!/usr/bin/env python3


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    T = int(input())

    for _ in range(T):
        N = int(input())
        cnt = 0
        A = list(map(int, input().split()))
        for a in A:
            if a % 2 == 1:
                cnt += 1
        print(cnt)



if __name__ == '__main__':
    main()
