#!/usr/bin/env python3
import sys
import string

def solve(S: str):

    char_list = string.ascii_uppercase
    n_chars = len(char_list)
    char_dict = {c: i + 1 for i, c in enumerate(char_list)}

    n_s = len(S)

    ans = 0
    for i, s in enumerate(S):
        d = n_s - i - 1
        ans += char_dict[s] * (n_chars ** d)
    print(ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
