#!/usr/bin/env python3
import sys

def solve(D: int):

    ans = float("INF")
    for x in range(int(D ** 0.5) + 1):
        yy = D - x ** 2
        y = yy ** 0.5
        min_y = int(y)
        max_y = int(y + 1)

        for n in [min_y, max_y]:
            n = int(n)
            ans = min(ans, abs(x ** 2 + n ** 2 - D))

    print(ans)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    D = int(next(tokens))  # type: int
    solve(D)

if __name__ == '__main__':
    main()
