#!/usr/bin/env python3
import sys

INF = float("INF")


def solve(N, X1, Y1, Z1, X2, Y2, Z2):
    
    W = 101
    grids = [[[INF] * W for _ in range(W)] for _ in range(W)]

    for i, (x1, y1, z1, x2, y2, z2) in enumerate(zip(X1, Y1, Z1, X2, Y2, Z2)):
        for x in range(x1, x2):
            for y in range(y1, y2):
                for z in range(z1, z2):
                    grids[x][y][z] = i
    
    fit_list = [set() for _ in range(N)]

    MOVE = [
        (1, 0, 0), (-1, 0, 0),
        (0, 1, 0), (0, -1, 0),
        (0, 0, 1), (0, 0, -1),
    ]

    for x in range(W):
        for y in range(W):
            for z in range(W):
                ci = grids[x][y][z]
                if ci == INF:
                    continue
                
                for dx, dy, dz in MOVE:
                    nx, ny, nz = x + dx, y + dy, z + dz
                    ni = grids[nx][ny][nz]
                    if ni == INF:
                        continue
                    if ci != ni:
                        fit_list[ci].add(ni)

    for s in fit_list:
        print(len(s))


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    X1, X2 = [], []
    Y1, Y2 = [], []
    Z1, Z2 = [], []
    for _ in range(N):
        X1.append(int(next(tokens)))
        Y1.append(int(next(tokens)))
        Z1.append(int(next(tokens)))
        X2.append(int(next(tokens)))
        Y2.append(int(next(tokens)))
        Z2.append(int(next(tokens)))
    solve(N, X1, Y1, Z1, X2, Y2, Z2)

if __name__ == '__main__':
    main()
