#!/usr/bin/env python3

def cumsum_1d(data):
    n = len(data)
    cumsum_data = [0] * (n + 1)
    for i in range(n):
        cumsum_data[i + 1] = data[i] + cumsum_data[i]
    return cumsum_data


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    T = int(input())
    cases = []

    for _ in range(T):
        N, W = map(int, input().split())
        CS = list(map(int, input().split()))
        cases.append((N, W, CS))

    for case in cases:
        N, W, CS = case
        W2 = W * 2
    
        v_sum = [0] * W2
        for idx, c in enumerate(CS):
            v_sum[idx % W2] += c

        v2_sum = v_sum + v_sum

        v2_cumsum = cumsum_1d(v2_sum)

        """
        print(v2_sum)
        print(v2_cumsum)
        print()
        """

        ans = float("INF")
        for idx in range(W2):
            ans = min(ans, v2_cumsum[idx + W] - v2_cumsum[idx])
        print(ans)


if __name__ == '__main__':
    main()
