#!/usr/bin/env python3
import sys


INF = float("INF")


def solve(N: int, D: int, P: int, F: "List[int]"):

    max_ticket = D * N
    dp = [[INF] * (max_ticket + 1) for _ in range(N + 1)]
    dp[0][0] = 0

    for i in range(N):
        for j in range(max_ticket):
            # 1 day
            dp[i + 1][j] = min(dp[i + 1][j], dp[i][j] + F[i])
            # use ticket
            if j - 1 >= 0:
                dp[i + 1][j - 1] = min(dp[i + 1][j - 1], dp[i][j])
            # buy & use ticket
            if j + (D - 1) <= max_ticket:
                dp[i + 1][j + (D - 1)] = min(dp[i + 1][j + (D - 1)], dp[i][j] + P)

    print(min(dp[N]))


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    D = int(next(tokens))  # type: int
    P = int(next(tokens))  # type: int
    F = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, D, P, F)

if __name__ == '__main__':
    main()
