#!/usr/bin/env python3
import sys
from collections import deque


def solve(N: int, S: str):

    ans_list = [""] * N
    close_idx = deque()

    curr_idx = 0
    for c in S:
        if c == "(":
            close_idx.append(curr_idx)
            ans_list[curr_idx] = c
        elif c == ")":
            if not close_idx:
                ans_list[curr_idx] = c
            else:
                curr_idx = close_idx.pop() - 1
        else:
            ans_list[curr_idx] = c
        curr_idx += 1


    ans = "".join([ans_list[i] for i in range(curr_idx)])
    print(ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    solve(N, S)

if __name__ == '__main__':
    main()
