#!/usr/bin/env python3
import sys
from collections import deque


def solve(N: int, S: str):

    ans_list = [""] * N
    close_idx = deque()

    offset = 0
    end_idx = -float("INF")
    for i, c in enumerate(S):
        if c == "(":
            close_idx.append(i)
            ans_list[i - offset] = c
            end_idx = max(end_idx, i - offset)
        elif c == ")":
            if not close_idx:
                ans_list[i - offset] = c
                end_idx = max(end_idx, i - offset)
                continue
            last_idx = close_idx.pop()
            offset = i - last_idx + offset + 1
            end_idx -= offset
        else:
            ans_list[i - offset] = c
            end_idx = max(end_idx, i - offset)
        print(ans_list)
        print(end_idx)

    ans = ""
    print(end_idx)
    for i in range(end_idx):
        ans += ans_list[i]
    print(ans)

"""
11
a(a)b(vs)s
"""


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    solve(N, S)

if __name__ == '__main__':
    main()
