#!/usr/bin/env python3
import sys
from collections import defaultdict, deque
INF = float('inf')  # type: float


def solve(N: int, M: int, P: "List[int]", X: "List[int]", Y: "List[int]"):

    P = [0] + P
    P = [p - 1 for p in P]

    xy_list = [(x - 1, y) for x, y in zip(X, Y)]

    dp = [-1] * N
    for x, y in xy_list:
        dp[x] = max(dp[x], y)

    for i in range(1, N):
    #for i in range(N - 1, 0, -1):
        dp[i] = max(dp[i], dp[P[i]] - 1)

    ans = 0
    for a in dp:
        if a >= 0:
            ans += 1

    print(dp)
    print(ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    p = [int(next(tokens)) for _ in range(N - 2 + 1)]  # type: "List[int]"
    x = [int()] * (M)  # type: "List[int]"
    y = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        x[i] = int(next(tokens))
        y[i] = int(next(tokens))
    solve(N, M, p, x, y)

if __name__ == '__main__':
    main()
