#!/usr/bin/env python3

"""
N = 3  (N < 10**9)
-> Nのループはきつい

1 2 3  x
1 3 2  x
2 1 3  x
2 3 1  1  (2, 3) (3, 1)
3 1 2  1  (3, 1) (1, 2)
3 2 1  x
-> (2, 3) (1, 2)
  この計算量は(10**9 * 10**8) * (10**9) ** 2になる。。。

ある程度回答の形は決まっている？

・N % 2 == 0の場合
(2, 1)  => 1
(4, 3, 2, 1)  => 6
(6, 5, 4, 3, 2, 1) => 15 (5 + 4 + 3 + 2 + 1)
-> N - 1の累積和 になる？

・N % 2 == 1の場合
(3, 1, 2)  => 2
(5, 4, 2, 3, 1)  => 9

-> N - 1の累積 - 1 になる？
"""

import sys


def solve(N: int):

    tmp = (N - 1) * N // 2
    if N % 2 == 0:
        print(tmp)
    else:
        print(tmp - 1)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
