#!/usr/bin/env python3
import sys

PI = "3.1415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679"


def solve(N: int):

    N += 2

    print(PI[:N])

    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
