#!/usr/bin/env python3
import sys


def rot(x, y):
    nx = y
    ny = -x
    return nx, ny

def rrot(x, y):
    nx = -y
    ny = x
    return nx, ny

def solve(H: int, W: int, N: int):

    px, py = 0, 0
    dx, dy = 0, -1

    field = [["."] * W for _ in range(H)]

    for _ in range(N):
        if field[py][px] == ".":
            field[py][px] = "#"
            dx, dy = rrot(dx, dy)
        else:
            field[py][px] = "."
            dx, dy = rot(dx, dy)

        px += dx
        py += dy

        px %= W
        py %= H

    for f in field:
        print("".join(f))

# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    H = int(next(tokens))  # type: int
    W = int(next(tokens))  # type: int
    N = int(next(tokens))  # type: int
    solve(H, W, N)

if __name__ == '__main__':
    main()
