#!/usr/bin/env python3
import sys


def solve(N: int, M: int, S: str, C: "List[int]"):

    c_list = [[] for _ in range(M + 1)]
    c_map_list = [{} for _ in range(M + 1)]

    for i, c in enumerate(C):
        c_list[c].append(i)

    for k, v in enumerate(c_list):
        nv = len(v)
        for iv in range(nv):
            niv = (iv - 1) % nv
            c_map_list[k][v[iv]] = v[niv]

    ans = ""
    for i, c in enumerate(C):
        ni = c_map_list[c][i]
        ans += S[ni]
    print(ans)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    C = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, M, S, C)

if __name__ == '__main__':
    main()