#!/usr/bin/env python3
import sys
from math import sqrt, floor, ceil

def solve(A: int, B: int):
    """
    f(x) = Bn + A / sqrt(n + 1)
         = Bn + A * (n + 1)^(-1/2)
    f'(x) = B + A * (-1/2) * (n + 1)^(-3/2) = 0

    A * (-1/2) * (n + 1)^(-3/2) = -B
    A/2 * (n + 1)^(-3/2) = B
    A/2 = B * (n + 1)^(3/2)
    (n + 1)^(3/2) = A/(2 * B)
    (n + 1)^3 = (A/(2 * B))^2
    n = ((A/(2 * B))^2) ** (1/3) - 1

    nは小数になるが、問題文から正の整数になるので、整数の最小値となるところが正解になる
    """

    f = lambda x: B*x + A / (sqrt(x + 1))

    min_x = (A/(2 * B)) ** (2/3) - 1

    h_x = max(int(ceil(min_x)), 0)
    l_x = max(int(floor(min_x)), 0)

    ans = float("Inf")
    for i in range(l_x, h_x + 1):
        ans = min(ans, f(i))

    print(ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    solve(A, B)

if __name__ == '__main__':
    main()
