#!/usr/bin/env python3
import sys
from collections import defaultdict

YES = "Yes"  # type: str
NO = "No"  # type: str
INF = float('inf')  # type: float


def solve(N: int, M: int, X: "List[int]", Y: "List[int]"):

    f_edge = [set() for _ in range(N)]
    b_edge = [set() for _ in range(N)]

    for x, y in zip(X, Y):
        f_edge[x].add(y)
        b_edge[y].add(x)

    #print(b_edge)
    #print(f_edge)

    idx = None
    for i in range(N):
        if len(b_edge[i]) == 0:
            idx = i
            break

    if idx is None:
        print(NO)


    is_visit = [False] * N
    ans_list = [-1] * N
    ok_flg = False

    def dfs(v, d=1):
        nonlocal ok_flg
        if len(f_edge[v]) == 0:
            if d < N:
                return
            else:
                ans_list[v] = d
                ok_flg = True

        if not ok_flg:
            is_visit[v] = True
            ans_list[v] = d

            for n in f_edge[v]:
                dfs(n, d + 1)

            is_visit[v] = False

    dfs(idx)
    if not ok_flg:
        print(NO)
    else:
        print(YES)
        print(*ans_list)

    """
    while True:
        #print(f"idx - {idx}, {curr_num}")
        if len(f_edge[idx]) == 0:
            if curr_num < N:
                print(NO)
                return
            ans_list[idx] = curr_num
            break

        if len(f_edge[idx]) > 1:
            print(NO)
            return

        ans_list[idx] = curr_num
        idx = f_edge[idx].pop()
        curr_num += 1

    print(YES)
    print(*ans_list)
    """


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    X = [int()] * (M)  # type: "List[int]"
    Y = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        X[i] = int(next(tokens)) - 1
        Y[i] = int(next(tokens)) - 1
    solve(N, M, X, Y)

if __name__ == '__main__':
    main()
