#!/usr/bin/env python3
import sys
from collections import defaultdict
from collections import deque

YES = "Yes"  # type: str
NO = "No"  # type: str
INF = float('inf')  # type: float


def solve(N: int, M: int, X: "List[int]", Y: "List[int]"):

    graph = [set() for _ in range(N)]
    n_in = [0] * N
    for x, y in zip(X, Y):
        if y not in graph[x]:
            graph[x].add(y)
            n_in[y] += 1


    parent_nodes = [i for i, n in enumerate(n_in) if n == 0]

    que = deque(parent_nodes)

    ans = [None] * N
    cnt = 1
    while que:
        if len(que) != 1:
            print(NO)
            return

        curr = que.popleft()

        ans[curr] = cnt
        cnt += 1

        for next in graph[curr]:
            n_in[next] -= 1
            if n_in[next] == 0:
                que.append(next)

    print(YES)
    print(*ans)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    X = [int()] * (M)  # type: "List[int]"
    Y = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        X[i] = int(next(tokens)) - 1
        Y[i] = int(next(tokens)) - 1
    solve(N, M, X, Y)

if __name__ == '__main__':
    main()
