#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
from atcoder import fenwicktree
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)


INF = 2 ** 64 - 1


def solve(N: int, A: list[int]):
    
    a_max = max(A)
    bit = fenwicktree.FenwickTree(a_max + 1)

    for a in A:
        bit.add(a, 1)

    n_ans = a_max + 1
    ans = [0] * n_ans
    for i in range(a_max):
        v = N - bit.sum(0, i + 1)
        p0 = ans[n_ans - 1 - i]
        p1 = ans[n_ans - 1 - i - 1]
        ans[n_ans - 1 - i] = (p0 + v) % 10
        ans[n_ans - 1 - i - 1] = p1 + (p0 + v) // 10
    
    if ans[0] != 0:
        print(ans[0], end="")
    for a in ans[1:]:
        print(a, end="")
    print()


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: list[int]
    solve(N, A)

if __name__ == '__main__':
    main()
