#!/usr/bin/env python3
import sys


def solve(N: int, M: int, S: str, T: str):
    
    def calc(s, t):
        res = 0
        for x, y in zip(s, t):
            nx, ny = int(x), int(y)
            res += (nx - ny) % 10
        return res

    ans = float("INF")
    for idx in range(N - M + 1):
        ans = min(ans, calc(S[idx : idx + M], T))
    print(ans)



# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    T = next(tokens)  # type: str
    solve(N, M, S, T)

if __name__ == '__main__':
    main()
