#!/usr/bin/env python3
import sys
from collections import defaultdict, Counter

YES = "Yes"  # type: str
NO = "No"  # type: str
INF = float('inf')  # type: float

TEMP_SET = set("atcoder")


def solve(S: str, T: str):
    s_cnt = Counter(S)
    t_cnt = Counter(T)

    col = set()
    for k in s_cnt.keys():
        col.add(k)
    for k in t_cnt.keys():
        col.add(k)

    s_diff, t_diff = 0, 0
    for c in col:
        if c == "@": continue
        s_n = 0 if c not in s_cnt else s_cnt[c]
        t_n = 0 if c not in t_cnt else t_cnt[c]

        if s_n != t_n and c not in TEMP_SET:
            print(NO)
            return

        s_diff += max(t_n - s_n, 0)
        t_diff += max(s_n - t_n, 0)

    if s_cnt["@"] >= s_diff and t_cnt["@"] >= t_diff:
        print(YES)
    else:
        print(NO)




# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    T = next(tokens)  # type: str
    solve(S, T)

if __name__ == '__main__':
    main()
