#!/usr/bin/env python3
import sys


def solve(N: int, Q: int, A: "List[int]", T: "List[int]", X: "List[int]", Y: "List[int]"):

    n_shitf = 0
    for t, x, y in zip(T, X, Y):
        x = (x + n_shitf) % N
        y = (y + n_shitf) % N

        if t == 1:
            A[x], A[y] = A[y], A[x]
        elif t == 2:
            n_shitf -= 1
        else:
            print(A[x])




# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    Q = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    T = [int()] * (Q)  # type: "List[int]"
    x = [int()] * (Q)  # type: "List[int]"
    y = [int()] * (Q)  # type: "List[int]"
    for i in range(Q):
        T[i] = int(next(tokens))
        x[i] = int(next(tokens)) - 1
        y[i] = int(next(tokens)) - 1
    solve(N, Q, A, T, x, y)

if __name__ == '__main__':
    main()
