#!/usr/bin/env python3
import bisect

# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N = int(input())
    a_list = list(map(int, input().split()))

    Q = int(input())

    query = [list(map(int, input().split())) for _ in range(Q)]

    sleep = [0] * N
    for i in range(1, N):
        if i % 2 == 0:
            sleep[i - 1] = a_list[i] - a_list[i - 1]

    cumsum_sleep = [0] * (N + 1)
    for i in range(N):
        cumsum_sleep[i + 1] = cumsum_sleep[i] + sleep[i]

    #print(sleep)
    #print(cumsum_sleep)

    for l, r in query:
        ans = 0
        l_ind = bisect.bisect_left(a_list, l)
        r_ind = bisect.bisect_left(a_list, r)

        if l_ind % 2 == 0:
            ans += a_list[l_ind] - l
        if r_ind % 2 == 0:
            ans += r - a_list[r_ind]
        #print(l_ind, r_ind)
        ans += cumsum_sleep[r_ind] - cumsum_sleep[l_ind]
        print(ans)

if __name__ == '__main__':
    main()
