#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N = int(input())
    A = list(map(lambda x: int(x) - 1, input().split()))

    ans = [INF] * N

    def func(i = 0):
        nonlocal ans 
        if ans[i] != INF:
            return
        
        cur = i
        memo = [i]
        while cur != A[cur]:
            memo.append(A[cur])
            cur = A[cur]
        
        for m in memo:
            ans[m] = cur + 1

    for i in range(N):
        func(i)
    print(*ans)
        



if __name__ == '__main__':
    main()
