#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(N: int, A: list[int], U: list[int], V: list[int]):
    
    edge = [[] for _ in range(N)]
    for u, v in zip(U, V):
        edge[u].append(v)
        edge[v].append(u)
    
    memo = defaultdict(int)
    used = [False] * N
    ans = [NO] * N

    def dfs(cur = 0, last_flg = False):
        nonlocal memo, used, ans
        
        if used[cur]:
            return
        
        used[cur] = True

        for nxt in edge[cur]:
            if used[nxt]:
                continue
            
            memo[A[nxt]] += 1

            cur_flg = False
            if last_flg:
                cur_flg = True
                ans[nxt] = YES
            else:
                if memo[A[nxt]] >= 2:
                    cur_flg = True
                    ans[nxt] = YES
                    
            dfs(nxt, cur_flg)
            memo[A[nxt]] -= 1

    memo[A[0]] += 1
    dfs()

    for a in ans:
        print(a)




# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: list[int]
    U = [int()] * (N - 1)  # type: list[int]
    V = [int()] * (N - 1)  # type: list[int]
    for i in range(N - 1):
        U[i] = int(next(tokens)) - 1
        V[i] = int(next(tokens)) - 1
    solve(N, A, U, V)

if __name__ == '__main__':
    main()
