#!/usr/bin/env python3
import sys


def solve(N: int, Q: int, A: "List[int]", L: "List[int]", R: "List[int]", V: "List[int]"):

    diff = [A[i + 1] - A[i] for i in range(N - 1)]
    diff_sum = 0
    for x in diff:
        diff_sum += abs(x)

    for l, r, v in zip(L, R, V):
        l -= 1
        r -= 1
        if l > 0:
            prev = diff[l - 1]
            diff[l - 1] += v
            diff_sum += abs(diff[l - 1]) - abs(prev)
        if r < N - 1:
            prev = diff[r]
            diff[r] -= v
            diff_sum += abs(diff[r]) - abs(prev)

        print(diff_sum)





# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    Q = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    L = [int()] * (Q)  # type: "List[int]"
    R = [int()] * (Q)  # type: "List[int]"
    V = [int()] * (Q)  # type: "List[int]"
    for i in range(Q):
        L[i] = int(next(tokens))
        R[i] = int(next(tokens))
        V[i] = int(next(tokens))
    solve(N, Q, A, L, R, V)

if __name__ == '__main__':
    main()
