#!/usr/bin/env python3
import sys


def gcd(a, b):
    if b == 0: return a
    return gcd(b, a % b)

def solve(A: int, B: int, C: int):

    a = gcd(max(A, B), min(A, B))
    b = gcd(max(a, C), min(a, C))

    ans = 0
    ans += A // b - 1
    ans += B // b - 1
    ans += C // b - 1
    print(ans)

    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    C = int(next(tokens))  # type: int
    solve(A, B, C)

if __name__ == '__main__':
    main()
