#!/usr/bin/env python3
import sys


def solve(N: int, A: int, B: int):

    field = [['.']*(N*B) for _ in range(N*A)]

    for i in range(N):
        for j in range(N):
            if (i + j) % 2 == 0: continue

            for a in range(A):
                for b in range(B):
                    ci = i*A + a
                    cj = j*B + b
                    field[ci][cj] = '#'


    for f in field:
        print(''.join(f))


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    solve(N, A, B)

if __name__ == '__main__':
    main()
