#!/usr/bin/env python3
import sys
from collections import deque

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(N: int, s_x: int, s_y: int, t_x: int, t_y: int, X: "List[int]", Y: "List[int]", R: "List[int]"):


    def check_on_circle(px, py, cx, cy, cr):
        dist = ((cx - px) ** 2 + (cy - py) ** 2) ** 0.5
        if abs(cr - dist) <= 0.0001:
            return True
        return False

    start = None
    end = None
    edges = [[] for _ in range(N)]
    for i in range(N):
        xi, yi, ri = X[i], Y[i], R[i]
        if i < N - 1:
            for j in range(i + 1, N):
                xj, yj, rj = X[j], Y[j], R[j]
                dist = ((xi - xj) ** 2 + (yi - yj) ** 2)
                if (dist >= (ri - rj) ** 2) and (dist <= (ri + rj) ** 2):
                    edges[i].append(j)
                    edges[j].append(i)

        if not start and check_on_circle(s_x, s_y, xi, yi, ri):
            start = i
        if not end and check_on_circle(t_x, t_y, xi, yi, ri):
            end = i

    deq = deque()
    deq.append(start)

    visit = [False] * N

    while deq:
        idx = deq.popleft()
        if idx == end:
            print(YES)
            return
        visit[idx] = True

        for e in edges[idx]:
            if not visit[e]:
                deq.append(e)

    print(NO)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    s_x = int(next(tokens))  # type: int
    s_y = int(next(tokens))  # type: int
    t_x = int(next(tokens))  # type: int
    t_y = int(next(tokens))  # type: int
    x = [int()] * (N)  # type: "List[int]"
    y = [int()] * (N)  # type: "List[int]"
    r = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        x[i] = int(next(tokens))
        y[i] = int(next(tokens))
        r[i] = int(next(tokens))
    solve(N, s_x, s_y, t_x, t_y, x, y, r)

if __name__ == '__main__':
    main()
