#!/usr/bin/env python3
import sys


def solve(N: int, A: int, B: int, C: int):
    max_l = 9999
    ans = max_l
    for i in range(max_l):
        if A * i > N:
            break
        for j in range(max_l - i):
            if B * j > N or A * i + B * j > N:
                break

            C_value = N - (A * i + B * j)
            C_div = C_value // C
            C_mod = C_value % C
            num = i + j + C_div

            if C_mod == 0 and num <= max_l:
                ans = min(ans, num)
    
    print(ans)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    C = int(next(tokens))  # type: int
    solve(N, A, B, C)

if __name__ == '__main__':
    main()
