#!/usr/bin/env python3
import sys


# 桁DP
def calc(N):

    n_unit = len(N)

    # dp[<上から何桁目か>][<与えられた数値より小さいかどうか>][<条件を満たすかどうか>] = 個数
    dp = [[[0] * 2 for _ in range(2)] for _ in range(n_unit + 1)]

    dp[0][0][0] = 1

    for unit in range(n_unit):
        unit_num = int(N[unit])
        for less in range(2):
            unit_limit = 9 if less else unit_num
            for enable in range(2):
                for value in range(unit_limit + 1):
                    enable_next = 0
                    less_next = 0
                    if less or value < unit_limit:
                        less_next = 1
                    if enable or value == 4 or value == 9:
                        enable_next = 1

                    dp[unit + 1][less_next][enable_next] += dp[unit][less][enable]

    return dp[-1][0][1] + dp[-1][1][1]


def solve(A, B):
    print(calc(B) - calc(str(int(A)-1)))





# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    A = next(tokens)
    B = next(tokens)
    solve(A, B)

if __name__ == '__main__':
    main()
