#!/usr/bin/env python3
import sys


def solve(H: int, W: int, A: "List[List[int]]"):

    a_col = [0] * W
    a_row = [0] * H

    for i in range(H):
        a_row[i] = sum(A[i])

    for i in range(W):
        a_col[i] = sum([A[j][i] for j in range(H)])

    for i in range(H):
        ans = [0] * W
        for j in range(W):
            ans[j] = a_row[i] + a_col[j] - A[i][j]
        print(*ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    H = int(next(tokens))  # type: int
    W = int(next(tokens))  # type: int
    A = [[int(next(tokens)) for _ in range(W)] for _ in range(H)]  # type: "List[List[int]]"
    solve(H, W, A)

if __name__ == '__main__':
    main()
