#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1


def solve(N: int, L: int, R: int, S: str):
    
    X = set(S)

    cumsum = {x: [0] for x in X}

    for s in S:
        for x in X:
            v = cumsum[x][-1]
            cumsum[x].append(v)
        
        cumsum[s][-1] += 1

#    print(cumsum)

    ans = 0
    for idx, s in enumerate(S):
        if idx + L >= N:
            break

        l = idx + L
        r = min(N, idx + R + 1)
        
        v = cumsum[s][r] - cumsum[s][l]
        ans += v
        
#        print((L, R), (l, r), s, v)

    print(ans)


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    L = int(next(tokens))  # type: int
    R = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    solve(N, L, R, S)

if __name__ == '__main__':
    main()
