#!/usr/bin/env python3
import sys


def solve(N: int, M: int, S: "List[str]"):
    
    C = [[[False, False, False] for _ in range(M)] for _ in range(N)]

    ans = []
    for i in range(N - 8):
        for j in range(M - 8):
            is_ok = True
            for k in range(9):
                if S[i + k // 3][j + k % 3] == ".":
                    is_ok = False
                    break
                if S[i + k // 3 + 6][j + k % 3 + 6] == ".":
                    is_ok = False
                    break
            if not is_ok:
                continue
            
            for d in range(4):
                if S[i + 3][j + d] == "#":
                    is_ok = False
                    break
                if S[i + d][j + 3] == "#":
                    is_ok = False
                    break
                
                if S[i + 5][j + 5 + d] == "#":
                    is_ok = False
                    break
                if S[i + 5 + d][j + 5] == "#":
                    is_ok = False
                    break
            if not is_ok:
                continue
            
            ans.append((i + 1, j + 1))

    for a in ans:
        print(*a)

            
                


            

    """
    for i in range(N - 2):
        for j in range(M - 2):
            
            is_ok = True
            for k in range(9):
                ni = i + k // 3
                nj = j + k % 3
                if S[ni][nj] != ".":
                    is_ok = False
                    break
            if is_ok:
                C[i][j][0] = True

                lt_i, lt_j = i, j
                rd_i, rd_j = i + 3, j + 3
                if lt_i > 0 and lt_j > 0:
                    is_ok = True
                    for d in range(4):
                        if S[lt_i - 1][lt_j - 1 + d] == "#":
                            is_ok = False
                            break
                        if S[lt_i - 1 + d][lt_j - 1] == "#":
                            is_ok = False
                            break
                    if is_ok:
                        C[i][j][1] = True
                
                if rd_i < N - 1 and lt_j < M - 1:
                    is_ok = True
                    for d in range(4):
                        if S[rd_i + 1][rd_j + 1 - d] == "#":
                            is_ok = False
                            break
                        if S[rd_i + 1 - d][rd_j + 1] == "#":
                            is_ok = False
                            break
                    if is_ok:
                        C[i][j][2] = True

    """



            



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    S = [next(tokens) for _ in range(N)]  # type: "List[str]"
    solve(N, M, S)

if __name__ == '__main__':
    main()
