#!/usr/bin/env python3
import sys
from collections import deque


YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(H, W, K, A):

    field = [[]] * (H + 2)
    for i in range(H + 2): field[i] = ['#'] * (W + 2)

    for i in range(H):
        for j in range(W):
            field[i + 1][j + 1] = A[i][j]

    p_deq = deque()
    p_deq.append([1, 1, 0])     # pos_x pos_y time
    field[1][1] = '-'

    m_deq = deque([])
    for i in range(1, H + 1):
        for j in range(1, W + 1):
            if field[i][j] == '@':
                m_deq.append([j, i])
    m_deq.append([-1, -1])

    is_clear = False
    pt = 0

    move = [[0, 1], [0, -1], [1, 0], [-1, 0]]

    while p_deq:
        cx, cy, ct = p_deq.popleft()

        if pt != ct:
            pt = ct

            if ct % K == 0:
                while True:
                    mcx, mcy = m_deq.popleft()
                    if mcx == -1: break
                    for m in move:
                        mnx = mcx + m[0]
                        mny = mcy + m[1]
                        if (field[mny][mnx] != '#') and (field[mny][mnx] != '@'):
                            field[mny][mnx] = '@'
                            m_deq.append([mnx, mny])
                m_deq.append([-1, -1])


        if field[cy][cx] == '@':
            continue

        if (cx == W) and (cy == H):
            is_clear = True
            break

        for m in move:
            nx = cx + m[0]
            ny = cy + m[1]
            if field[ny][nx] == '.':
                field[ny][nx] = '-'
                p_deq.append([nx, ny, ct + 1])

    if is_clear:
        print(YES)
    else:
        print(NO)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    H = int(next(tokens))  # type: int
    W = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    A = [next(tokens) for _ in range(W)]  # type: "List[str]"
    solve(H, W, K, A)

if __name__ == '__main__':
    main()
