#!/usr/bin/env python3


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    L, N1, N2 = map(int, input().split())

    n1_list = []
    n2_list = []
    for _ in range(N1):
        n1_list.append(list(map(int, input().split())))
    for _ in range(N2):
        n2_list.append(list(map(int, input().split())))

    n1_idx = 0
    n2_idx = 0

    ans = 0
    while n1_idx < N1 and n2_idx < N2:
        n1_value, n1_cnt = n1_list[n1_idx]
        n2_value, n2_cnt = n2_list[n2_idx]

        max_cnt = max(n1_cnt, n2_cnt)
        min_cnt = min(n1_cnt, n2_cnt)

        if n1_value == n2_value:
            ans += min_cnt

        if max_cnt == min_cnt:
            n1_list[n1_idx][1] = 0
            n2_list[n2_idx][1] = 0
            n1_idx += 1
            n2_idx += 1
        else:
            if n2_cnt > n1_cnt:
                n1_list[n1_idx][1] = 0
                n1_idx += 1
                n2_list[n2_idx][1] -= min_cnt
            else:
                n2_list[n2_idx][1] = 0
                n2_idx += 1
                n1_list[n1_idx][1] -= min_cnt

    print(ans)


if __name__ == '__main__':
    main()
