#!/usr/bin/env python3
import sys


def solve(N: int, S: str):

    a, b, c = 0, 0, 0
    for i, s in enumerate(S):
        if s == "A":
            a += 1
        if s == "B":
            b += 1
        if s == "C":
            c += 1

        if a > 0 and b > 0 and c > 0:
            print(i + 1)
            break



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    solve(N, S)

if __name__ == '__main__':
    main()
