#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1


def solve(N: int, S: list[str]):
    max_ns = max([len(s) for s in S])

    for s in S:
        ns = len(s)
        pad_ns = (max_ns - ns) // 2

        ans = "." * pad_ns
        ans += s
        ans += "." * pad_ns
        print(ans)



# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = [next(tokens) for _ in range(N)]  # type: list[str]
    solve(N, S)

if __name__ == '__main__':
    main()
