#!/usr/bin/env python3
import sys
import bisect
from collections import defaultdict
INF = float('inf')  # type: float


calc = lambda a, b: a / (a + b)

calc_add = lambda a, b, c, d: (a + c) / (a + c + b + b)

def solve(N: int, M: int, K: int, A: "List[int]", B: "List[int]", C: "List[int]", D: "List[int]"):

    left = 0
    right = 1


    for _ in range(100):
        mid = (left + right) / 2

        rate = mid / (1 - mid)

        v_list = [c - d * rate for c, d in zip(C, D)]
        v_list.sort()

        num = 0
        for a, b in zip(A, B):
            z = a - b * rate
            idx = bisect.bisect_left(v_list, -z)
            num += M - idx

        if num < K:
            right = mid
        else:
            left = mid

    print(mid * 100)



    return

# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    A = [int()] * (N)  # type: "List[int]"
    B = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        A[i] = int(next(tokens))
        B[i] = int(next(tokens))
    C = [int()] * (M)  # type: "List[int]"
    D = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        C[i] = int(next(tokens))
        D[i] = int(next(tokens))
    solve(N, M, K, A, B, C, D)

if __name__ == '__main__':
    main()
