"""
1 2 3  1 2 3 ...

k (k - 1) (k - 2) (k - 2) ... (k - 2)
-> k * (k - 1) * pow(k - 2, N - 2)

N = 2, K = 3

3 * 2 = 6
"""

#!/usr/bin/env python3
import sys

MOD = 1000000007  # type: int


def solve(N: int, K: int):

    ans = K
    if N < 2:
        print(ans)
    else:
        ans *= (K - 1)
        n = N - 2
        ans *= pow(K - 2, n, MOD)
        ans %= MOD
        print(ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    solve(N, K)

if __name__ == '__main__':
    main()
