#!/usr/bin/env python3
import sys


def solve(N: int, T: list[int]):
    datas = [(idx + 1, v) for idx, v in enumerate(T)]
    datas.sort(key = lambda x: x[1])
    ans_list = [str(data[0]) for data in datas[:3]]
    print(" ".join(ans_list))
    return


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    T = [int(next(tokens)) for _ in range(N)]  # type: list[int]
    solve(N, T)

if __name__ == '__main__':
    main()
