#!/usr/bin/env python3
import sys


def solve(N: int, S: "List[str]"):

    win_cnt = []
    for i, s in enumerate(S):
        win_cnt.append((i + 1, s.count("o")))

    win_cnt.sort(key=lambda x: x[1], reverse=True)

    ans = []
    for cnt in win_cnt:
        ans.append(cnt[0])
    print(*ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = [next(tokens) for _ in range(N)]  # type: "List[str]"
    solve(N, S)

if __name__ == '__main__':
    main()
