#!/usr/bin/env python3
import sys


def solve(D: int, F: int):
    tmp = (D - F) // 7
    ans = (tmp + 1) * 7 - (D - F)
    print(ans) 


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    D = int(next(tokens))  # type: int
    F = int(next(tokens))  # type: int
    solve(D, F)

if __name__ == '__main__':
    main()
