#!/usr/bin/env python3


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    R, C = map(int, input().split())

    field = [list(input()) for _ in range(R)]

    num_set = set([str(i) for i in range(1, 10)])

    for i in range(R):
        for j in range(C):

            if field[i][j] not in num_set:
                continue

            length = int(field[i][j])

            field[i][j] = "."
            for ii in range(length + 1):
                for jj in range(length - ii + 1):
                    flg11 = i - ii >= 0 and i - ii < R
                    flg12 = i + ii >= 0 and i + ii < R
                    flg21 = j - jj >= 0 and j - jj < C
                    flg22 = j + jj >= 0 and j + jj < C

                    if flg11 and flg21 and field[i - ii][j - jj] not in num_set:
                        field[i - ii][j - jj] = "."
                    if flg12 and flg21 and field[i + ii][j - jj] not in num_set:
                        field[i + ii][j - jj] = "."
                    if flg11 and flg22 and field[i - ii][j + jj] not in num_set:
                        field[i - ii][j + jj] = "."
                    if flg12 and flg22 and field[i + ii][j + jj] not in num_set:
                        field[i + ii][j + jj] = "."

    for line in field:
        print("".join(line))



if __name__ == '__main__':
    main()
