#!/usr/bin/env python3
import sys

def solve(N: int, Q: int, x: "List[int]"):

    ray = list(range(1, N + 1))

    idx_dict = {i: i - 1 for i in range(1, N + 1)}

    for i in range(Q):
        curr_idx = idx_dict[x[i]]
        curr_num = ray[curr_idx]

        if curr_idx == N - 1:
            left_idx = curr_idx - 1
            left_num = ray[left_idx]

            tmp = ray[curr_idx]
            ray[curr_idx] = ray[left_idx]
            ray[left_idx] = tmp

            tmp = idx_dict[curr_num]
            idx_dict[curr_num] = idx_dict[left_num]
            idx_dict[left_num] = tmp

        else:
            right_idx = curr_idx + 1
            right_num = ray[right_idx]

            tmp = ray[curr_idx]
            ray[curr_idx] = ray[right_idx]
            ray[right_idx] = tmp

            tmp = idx_dict[curr_num]
            idx_dict[curr_num] = idx_dict[right_num]
            idx_dict[right_num] = tmp



    print(*ray)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    Q = int(next(tokens))  # type: int
    x = [int(next(tokens)) for _ in range(Q)]  # type: "List[int]"
    solve(N, Q, x)

if __name__ == '__main__':
    main()
