#!/usr/bin/env python3
import sys


def solve(X: int, Y: int, N: int):

    c = N % 3
    if X * 3 > Y:
        if c == 0:
            print(Y * (N // 3))
        else:
            print(Y * (N // 3) + X * c)
    else:
        print(X * N)




# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    X = int(next(tokens))  # type: int
    Y = int(next(tokens))  # type: int
    N = int(next(tokens))  # type: int
    solve(X, Y, N)

if __name__ == '__main__':
    main()
