#!/usr/bin/env python3
import sys
from collections import defaultdict
INF = float('inf')  # type: float


def solve(N: int, K: int, a: "List[int]", b: "List[int]"):

    ab_list = [(a_, b_) for a_, b_ in zip(a, b)]
    ab_list.sort(key=lambda x: x[0])

    total = sum([b for _, b in ab_list])

    ab_list = [(0, 0)] + ab_list

    day = 1
    num = 0
    for a, b in ab_list:
        num += b
        if total - num <= K:
            day += a
            print(day)
            return



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    a = [int()] * (N)  # type: "List[int]"
    b = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        a[i] = int(next(tokens))
        b[i] = int(next(tokens))
    solve(N, K, a, b)

if __name__ == '__main__':
    main()
