#!/usr/bin/env python3
import sys


def solve(N: int):

    board = [[-1] * N for _ in range(N)]
    board[N // 2][N // 2] = "T"

    def num2dir(num):
        if num == 0:
            return (1, 0)
        elif num == 1:
            return (0, 1)
        elif num == 2:
            return (-1, 0)
        else:
            return (0, -1)

    def is_out(x, y):
        if x < 0 or y < 0 or x >= N or y >= N:
            return False
        if board[y][x] != -1:
            return False
        return True

    dir_num = 0
    curr_id = 1
    curr_x, curr_y = 0, 0
    while curr_id <= N * N - 1:
        board[curr_y][curr_x] = curr_id
        curr_id += 1
        direct = num2dir(dir_num)
        next_x, next_y = curr_x + direct[0], curr_y + direct[1]
        if not is_out(next_x, next_y):
            dir_num = (dir_num + 1) % 4
            direct = num2dir(dir_num)
            next_x, next_y = curr_x + direct[0], curr_y + direct[1]

        curr_x, curr_y = next_x, next_y

    for b in board:
        print(*b)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
