#!/usr/bin/env python3
import sys


def solve(L: "List[int]", R: "List[int]"):

    ans = 0
    if L[0] > L[1]:
        if L[0] < R[1]:
            ans = min(R) - L[0]
    elif L[0] < L[1]:
        if L[1] < R[0]:
            ans = min(R) - L[1]
    else:
        ans = min(R) - L[0]

    print(ans)




# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    L = [int()] * (2)  # type: "List[int]"
    R = [int()] * (2)  # type: "List[int]"
    for i in range(2):
        L[i] = int(next(tokens))
        R[i] = int(next(tokens))
    solve(L, R)

if __name__ == '__main__':
    main()
