#!/usr/bin/env python3
import sys


def solve_1(L: "List[int]", R: "List[int]"):

    ans = 0

    l_data = (L[0], R[0])
    r_data = (L[1], R[1])

    if l_data[0] > r_data[0]:
        l_data, r_data = r_data, l_data

    ans = 0
    if l_data[0] == r_data[0]:
        ans = min(r_data[1], l_data[1]) - l_data[0]
    elif r_data[0] < l_data[1]:
        ans = min(r_data[1], l_data[1]) - r_data[0]

    print(ans)


def solve_2(L: "List[int]", R: "List[int]"):
    N = 100

    paints = [-1] * N

    for i in range(L[0], R[0]):
        paints[i] += 1
    for i in range(L[1], R[1]):
        paints[i] += 1

    ans = 0
    for d in paints:
        ans += max(d, 0)
    print(ans)


def solve(L: "List[int]", R: "List[int]"):
    #solve_1(L, R)
    solve_2(L, R)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    L = [int()] * (2)  # type: "List[int]"
    R = [int()] * (2)  # type: "List[int]"
    for i in range(2):
        L[i] = int(next(tokens))
        R[i] = int(next(tokens))
    solve(L, R)

if __name__ == '__main__':
    main()
