#!/usr/bin/env python3
import sys
from collections import defaultdict
from collections import deque



INF = float('inf')  # type: float


def solve(N: int, M: int, A: "List[int]", B: "List[str]", C: "List[int]", D: "List[str]"):

    CODE = {'R': 0, 'B': 1}
    G = [[] for _ in range(N * 2)]
    for i in range(0, N * 2, 2):
        G[i].append(i + 1)
        G[i + 1].append(i)

    for a, b, c, d, in zip(A, B, C, D):
        a, c = a - 1, c- 1
        G[a * 2 + CODE[b]].append(c * 2 + CODE[d])
        G[c * 2 + CODE[d]].append(a * 2 + CODE[b])

    ans_list = [0, 0]
    visited = set()

    for i in range(0, N * 2, 2):
        if i in visited or (i + 1) in visited:
            continue
        begin_idx = i
        prev_idx = None
        que = deque()
        que.append((begin_idx, prev_idx))

        curr_visit = set()
        is_continue = False
        is_circle = False

        def dfs(curr_idx, prev_idx=None):
            nonlocal is_continue
            nonlocal curr_visit
            nonlocal is_circle

            if curr_idx in visited:
                is_continue = True
                return

            curr_visit.add(curr_idx)

            for next_idx in G[curr_idx]:
                if (prev_idx is not None) and (next_idx == prev_idx):
                    continue
                if next_idx == begin_idx:
                    is_circle = True
                if next_idx in curr_visit:
                    continue
                dfs(next_idx, curr_idx)

        dfs(i)
        visited = visited | curr_visit

        if is_continue:
            continue

        if is_circle:
            ans_list[0] += 1
        else:
            ans_list[1] += 1

    print(*ans_list)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    A = [int()] * (M)  # type: "List[int]"
    B = [str()] * (M)  # type: "List[str]"
    C = [int()] * (M)  # type: "List[int]"
    D = [str()] * (M)  # type: "List[str]"
    for i in range(M):
        A[i] = int(next(tokens))
        B[i] = next(tokens)
        C[i] = int(next(tokens))
        D[i] = next(tokens)
    solve(N, M, A, B, C, D)

if __name__ == '__main__':
    main()
