#!/usr/bin/env python3
import sys


def solve(A: int, M: int, L: int, R: int):

    ri = (R - A) // M
    li = (L - A + M - 1) // M
    print(ri - li + 1)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    A = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    L = int(next(tokens))  # type: int
    R = int(next(tokens))  # type: int
    solve(A, M, L, R)

if __name__ == '__main__':
    main()
