#!/usr/bin/env python3
import sys
import copy


def solve(N: int):

    prev = [1]
    print(*prev)
    for i in range(1, N):
        curr = [1]
        if i > 1:
            for j in range(1, i):
                curr.append(prev[j - 1] + prev[j])
        curr.append(1)

        print(*curr)
        prev = copy.deepcopy(curr)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
