#!/usr/bin/env python3
import sys
from bisect import bisect_left

O = 0
X = 1


def solve(N: int, S: str):

    pos_dict = {
        O: [],
        X: []
    }

    for i, s in enumerate(S):
        idx = X if s == "x" else O
        pos_dict[idx].append(i)

    ans = 0
    for i, s in enumerate(S):
        idx = O if s == "x" else X
        n_pos = len(pos_dict[idx])

        ind = bisect_left(pos_dict[idx], i)
        if ind == n_pos or pos_dict[idx][ind] < i: continue
        ans += N - pos_dict[idx][ind]

    print(ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    solve(N, S)

if __name__ == '__main__':
    main()
