#!/usr/bin/env python3
import sys
from collections import defaultdict

from heapq import heappop, heappush



def solve(N: int, T: "List[int]", D: "List[int]"):

    td = [(t, d) for t, d in zip(T, D)]

    td.sort(key=lambda x: x[0])

    correct = defaultdict(list)
    for t, d in td:
        correct[t].append(d)

    que = []
    prev_t = None
    ans = 0
    for key, values in correct.items():

        if prev_t is not None:
            while len(que) > 0:
                num, tmp = heappop(que)
                if num > key:
                    heappush(que, (num, tmp))
                    break
                if prev_t <= num:
                    print((num, tmp))
                    ans += 1
                    prev_t += 1

        for value in values:
            heappush(que, (key + value, key))

        prev_t = key

    while len(que) > 0:
        num, tmp = heappop(que)
        if prev_t <= num:
            print((num, tmp))
            prev_t += 1
            ans += 1

    print(ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    T = [int()] * (N)  # type: "List[int]"
    D = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        T[i] = int(next(tokens))
        D[i] = int(next(tokens))
    solve(N, T, D)

if __name__ == '__main__':
    main()
