#!/usr/bin/env python3
import sys


def solve(N: int, M: int, E: int, U: "List[int]", V: "List[int]", Q: int, X: "List[int]"):
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    E = int(next(tokens))  # type: int
    U = [int()] * (E)  # type: "List[int]"
    V = [int()] * (E)  # type: "List[int]"
    for i in range(E):
        U[i] = int(next(tokens))
        V[i] = int(next(tokens))
    Q = int(next(tokens))  # type: int
    X = [int(next(tokens)) for _ in range(Q)]  # type: "List[int]"
    solve(N, M, E, U, V, Q, X)

if __name__ == '__main__':
    main()
