#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1



def solve(M: int, A: int, B: int):

    def index(i, j):
        return i * M + j

    edges = defaultdict(list)
    for y in range(M):
        for x in range(M):
            v = (y * A + x * B) % M
            edges[index(y, v)].append(index(x, y))
    
    que = deque()
    flag = [False] * (M * M)
    for i in range(M):
        for j in range(M):
            if i == 0 or j == 0:
                v = index(i, j)
                que.append(v)
                flag[v] = True

    while que:
        v = que.popleft()

        for nv in edges[v]:
            if not flag[nv]:
                flag[nv] = True
                que.append(nv)

    ans = len(flag) - sum(flag)
    print(ans)


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    M = int(next(tokens))  # type: int
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    solve(M, A, B)

if __name__ == '__main__':
    main()
