#!/usr/bin/env python3
"""
N = 3

0 1 2

for i in range(1, N + 1) の探索

i = 1 : P1 mod N              = Q1
i = 2 : (P1 + P2) mod N       = Q2
i = 3 : (P1 + P2, + P3) mod N = Q3

(0, 1, 2) = (Q1, Q2, Q3)

---------
P=(0,1,2) のとき

Q1 = (0)            :[0] mod 3   = 0
Q2 = (0 + 1)        :[1] mod 3   = 1
Q3 = (0 + 1 + 2)    :[3] mod 3   = 0

Q=(0,1,0)となる
->成り立たない

---------
P=(0,1,2,3) のとき

Q1 = (0)            :[0] mod 4   = 0
Q2 = (0 + 1)        :[1] mod 4   = 1
Q3 = (0 + 1 + 2)    :[3] mod 4   = 3
Q4 = (0 + 1 + 2 + 3):[6] mod 4   = 2

Q=(0,1,3,2)となる
->成り立つ


---------
P=(0,1,2,3,4) のとき

Q1 = (0)                :[0]  mod 5   = 0
Q2 = (0 + 1)            :[1]  mod 5   = 1
Q3 = (0 + 1 + 2)        :[3]  mod 5   = 3
Q4 = (0 + 1 + 2 + 4)    :[7]  mod 5   = 2
Q5 = (0 + 1 + 2 + 4 + 3):[10] mod 5   = 0


---------
P=(0,1,2,3,4,5) のとき

Q1 = (0)                    :[0]  mod 6   = 0
Q2 = (0 + 1)                :[1]  mod 6   = 1
Q3 = (0 + 1 + 2)            :[3]  mod 6   = 3
Q4 = (0 + 1 + 2 + 3)        :[6]  mod 6   = 0
Q5 = (0 + 1 + 2 + 3 + 4)    :[10] mod 6   = 4
Q6 = (0 + 1 + 2 + 3 + 4 + 5):[15] mod 6   = 3

"""

import sys


def solve(N: int):

    if N == 1:
        print(0)
        return

    a = set([i % N for i in range(N)])
    print(a)




# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
