#!/usr/bin/env python3
import sys
from collections import deque

def solve(N: int, A: "List[int]", B: "List[int]"):
    INF = float('INF')


    edges = [[] for _ in range(N + 1)]
    node_colors = [INF] + [None] * N

    for a, b in zip(A, B):
        edges[a].append(b)
        edges[b].append(a)

    que = deque()
    que.append((1, 0))


    node_cnt = [0] * 2
    node_group = [[] for _ in range(2)]

    while que:
        curr_node, curr_color = que.popleft()
        node_colors[curr_node] = curr_color
        node_cnt[curr_color] += 1
        node_group[curr_color].append(curr_node)

        for next_node in edges[curr_node]:
            if node_colors[next_node] is None:
                que.append((next_node, 1 - curr_color))

    idx = 0 if node_cnt[0] >= node_cnt[1] else 1
    print(*node_group[idx][:N//2])



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int()] * (N - 1)  # type: "List[int]"
    B = [int()] * (N - 1)  # type: "List[int]"
    for i in range(N - 1):
        A[i] = int(next(tokens))
        B[i] = int(next(tokens))
    solve(N, A, B)

if __name__ == '__main__':
    main()
