#!/usr/bin/env python3
import sys


def solve(N: int, a: "List[int]"):

    a_aum = sum(a)
    a.sort()
    b = [a_aum // N for _ in range(N)]

    for i in range(a_aum % N):
        idx = N - i - 1
        b[idx] += 1

    ans = 0
    for na, nb in zip(a, b):
        ans += abs(na - nb)

    print(ans // 2)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, A)

if __name__ == '__main__':
    main()
