#!/usr/bin/env python3
import sys
import math


def calc(N, A):
    num = N // A
    tail = num * A
    total = num*(A + tail)//2
    return total


def solve(N: int, A: int, B: int):

    total = N*(1 + N)//2

    total_a = calc(N, A)
    total_b = calc(N, B)
    lcm_a_b = A * B // math.gcd(A, B)
    total_a_b = calc(N,  lcm_a_b)
    disable_total = total_a + total_b - total_a_b

    print(total - disable_total)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    solve(N, A, B)

if __name__ == '__main__':
    main()
