#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1


"""
[bad case]
N = 10
1 2 1 2 1 2 1 2 1 2
 - - - - - - - - - 
a a c c e e g g i i
  b b d d f f h h
-> (N - 1) * 2
"""

def solve(S: str):
    
    s = "-" + S + "-"

    curr = INF
    idx_list = []
    for i in range(1, len(s) - 1):
        num = int(s[i])
        if curr == INF:
            curr = num
        else:
            if curr != num:
                if curr + 1 == num:
                    idx_list.append(i)
                curr = num

    def calc(idx):
        h_idx, t_idx = idx - 1, idx
        h_c, t_c = s[h_idx], s[t_idx]

        cnt = 1
        diff = 1
        while (s[h_idx - diff] == h_c) and (s[t_idx + diff] == t_c):
            cnt += 1
            diff += 1
        return cnt
    
    ans = 0
    for idx in idx_list:
        ans += calc(idx)
    print(ans)


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = str(next(tokens))  # type: int
    solve(S)

if __name__ == '__main__':
    main()
