#!/usr/bin/env python3
import sys
from collections import defaultdict
INF = float('inf')  # type: float


def solve(A: "List[int]"):

    ans = 0
    for i, b in enumerate(A):
        if b == 1:
            ans += pow(2, i)

    print(ans)




# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    A = [int(next(tokens)) for _ in range(63 + 1)]  # type: "List[int]"
    solve(A)

if __name__ == '__main__':
    main()
