#!/usr/bin/env python3


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N, K = map(int, input().split())
    A = list(map(int, input().split()))

    ans = 0
    cur = 0
    idx = 0
    while idx < N:
        a = A[idx]
        if cur + a < K:
            cur += a
            idx += 1
        elif cur + a == K:
            cur = 0
            ans += 1
            idx += 1
        else:
            cur = 0
            ans += 1

    if cur > 0:
        ans += 1
    print(ans)

if __name__ == '__main__':
    main()
