#!/usr/bin/env python3
import sys


def solve(R: int, C: int):

    fields = [[0] * 15 for _ in range(15)]

    for i in [0, 2, 4, 6]:
        ri = 15 - i
        li = i
        for j in range(li, ri):
            fields[li][j] = 1
            fields[j][ri - 1] = 1

            fields[j][li] = 1
            fields[ri - 1][j] = 1

    ans = 'white'
    if fields[R - 1][C - 1] == 1:
        ans = 'black'
    print(ans)




# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    R = int(next(tokens))  # type: int
    C = int(next(tokens))  # type: int
    solve(R, C)

if __name__ == '__main__':
    main()
