#!/usr/bin/env python3
import sys


def solve(N: int, M: int, A: "List[int]", B: "List[int]"):

    edges = [[] for _ in range(N)]
    for a, b in zip(A, B):
        a -= 1
        b -= 1
        edges[b].append(a)

    ans_list = []
    for i in range(N):
        if len(edges[i]) == 0:
            ans_list.append(i)

    if len(ans_list) == 1:
        print(ans_list[0] + 1)
    else:
        print(-1)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    A = [int()] * (M)  # type: "List[int]"
    B = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        A[i] = int(next(tokens))
        B[i] = int(next(tokens))
    solve(N, M, A, B)

if __name__ == '__main__':
    main()
