#!/usr/bin/env python3
import sys


def solve(N: int, M: int, A: "List[int]", C: "List[int]", X: "List[int]"):

    X = set(X)

    INF = float('INF')
    dp = [[INF] * (N + 1) for _ in range(N + 1)]
    dp[0][0] = 0
    for i in range(1, N + 1):
        v = INF
        for j in range(i):
            v = min(v, C[i - j - 1])
            dp[i][j + 1] = dp[i - 1][j] + A[i - 1] + v
        if i not in X:
            for j in range(i):
                dp[i][j] = min(dp[i][j], dp[i - 1][j])

    print(min(dp[-1]))



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    C = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    X = [int(next(tokens)) for _ in range(M)]  # type: "List[int]"
    solve(N, M, A, C, X)

if __name__ == '__main__':
    main()
