#!/usr/bin/env python3
import sys


def solve(N: int, X: int, Y: int, P: "List[int]", T: "List[int]", Q: int, q: "List[int]"):
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    X = int(next(tokens))  # type: int
    Y = int(next(tokens))  # type: int
    P = [int()] * (N - 1)  # type: "List[int]"
    T = [int()] * (N - 1)  # type: "List[int]"
    for i in range(N - 1):
        P[i] = int(next(tokens))
        T[i] = int(next(tokens))
    Q = int(next(tokens))  # type: int
    q = [int(next(tokens)) for _ in range(Q)]  # type: "List[int]"
    solve(N, X, Y, P, T, Q, q)

if __name__ == '__main__':
    main()
