#!/usr/bin/env python3
import sys

MOD = 1000000007  # type: int

from math import log10


# Get the value of a/b
def mod_div(a, b, mod):
	return (a * pow(b, mod - 2, mod)) % mod


def sum_seq(num, mod):
    a = num % mod
    b = (num + 1) % mod
    v = a * b % mod
    return mod_div(v, 2, mod)


def solve(L: int, R: int):

    l_digit = int(log10(L)) + 1
    r_digit = int(log10(R)) + 1

    ans = 0
    for d in range(l_digit, r_digit + 1):
        head = max(L, 10 ** (d - 1))
        tail = min(R, 10 ** d - 1)
        curr = (sum_seq(tail, MOD) - sum_seq(head - 1, MOD)) * d
        curr %= MOD
        ans += curr
        ans %= MOD
    print(ans)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    L = int(next(tokens))  # type: int
    R = int(next(tokens))  # type: int
    solve(L, R)

if __name__ == '__main__':
    main()
