#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1


from functools import reduce

def comb(n: int, r: int) -> int:
    r = min(r, n - r)
    numer = reduce(lambda x, y: x * y, range(n, n - r, -1), 1)
    denom = reduce(lambda x, y: x * y, range(1, r + 1), 1)
    return numer // denom


def solve(N: int, M: int, A: list[int], B: list[int]):
    pairs = {idx: set() for idx in range(N)}
    for a, b in zip(A, B):
        a -= 1
        b -= 1
        pairs[a].add(b)
        pairs[b].add(a)

    ans = [0] * N
    for idx in range(N):
        np = N - len(pairs[idx]) - 1
        if np >= 3:
            ans[idx] = comb(np, 3)
    
    print(*ans)



# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    A = [int()] * (M)  # type: list[int]
    B = [int()] * (M)  # type: list[int]
    for i in range(M):
        A[i] = int(next(tokens))
        B[i] = int(next(tokens))
    solve(N, M, A, B)

if __name__ == '__main__':
    main()
