#!/usr/bin/env python3
import sys
from collections import defaultdict
from collections import Counter
INF = float('inf')  # type: float

import sys
sys.setrecursionlimit(10 ** 8)


def solve(S: str):

    counter = Counter(S)

    ans = 0

    def recursive(s, cnt):
        nonlocal ans
        print(s)

        is_happy = True
        for v in cnt.values():
            if v % 2 == 1:
                is_happy = False
                break
        if is_happy:
            ans += 1

        if len(s) <= 2:
            return

        pop_head_1 = s[0]
        pop_head_2 = s[1]
        pop_head_cnt = cnt.copy()
        pop_head_cnt[pop_head_1] -= 1
        pop_head_cnt[pop_head_2] -= 1

        pop_mid_1 = s[0]
        pop_mid_2 = s[-1]
        pop_mid_cnt = cnt.copy()
        pop_mid_cnt[pop_mid_1] -= 1
        pop_mid_cnt[pop_mid_2] -= 1

        pop_tail_1 = s[-2]
        pop_tail_2 = s[-1]
        pop_tail_cnt = cnt.copy()
        pop_tail_cnt[pop_tail_1] -= 1
        pop_tail_cnt[pop_tail_2] -= 1

        recursive(s[2:], pop_head_cnt)
        recursive(s[1:-1], pop_mid_cnt)
        recursive(s[:-2], pop_tail_cnt)

    recursive(S, counter)

    print(ans)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
