#!/usr/bin/env python3
import sys
from collections import defaultdict
from collections import Counter
INF = float('inf')  # type: float

import sys
sys.setrecursionlimit(10 ** 8)


def solve(S: str):

    encoder = {str(i): i for i in range(10)}
    cumsum = [[0] * (len(S) + 2) for _ in range(10)]

    for i, s in enumerate(S):
        for j in range(10):
            cumsum[j][i + 1] = cumsum[j][i]
            if j in encoder[s]:
                cumsum[j][i + 1] += 1

    begin_idx = None
    for i in range(len(S)):
        is_valid = True
        for j in range(10):

            if cumsum[i][j] % 2 != 0:
                is_valid = False
                break

        if is_valid:
            if begin_idx is None:
                begin_idx = i
        else:
            if begin_idx is not None:
                # TODO
                begin_idx = True

    print(ans)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
