#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1



# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N, M = map(int, input().split())
    A = list(map(int, input().split()))

    data = defaultdict(list)
    for a in A:
        data[len(str(a))].append(a)

    ans = 0
    for k, aa in data.items():
        unit = (10 ** k)

        a_mod_map = defaultdict(int)
        
        for a in aa:
            a_mod_map[a % M] += 1
        
        for a in A:
            v_mod = (-a * unit) % M
            ans += a_mod_map[v_mod]

    print(ans)



if __name__ == '__main__':
    main()
