#!/usr/bin/env python3
import sys
from collections import defaultdict
from bisect import bisect_left
INF = float('inf')  # type: float


def solve(W: int, H: int, N: int, P: "List[int]", Q: "List[int]", A: int, a: "List[int]", B: int, b: "List[int]"):

    def to_index(x, y):
        return y * W + x

    n_rect = (A + 1) * (B + 1)
    storage = defaultdict(int)

    min_struct = defaultdict(int)
    min_struct[0] = n_rect

    ans_max = 0
    ans_min = INF
    for p, q in zip(P, Q):
        ind_a = bisect_left(a, p)
        ind_b = bisect_left(b, q)

        idx = to_index(ind_a, ind_b)
        storage[idx] += 1

        if ans_max < storage[idx]:
            ans_max = storage[idx]

        min_struct[storage[idx] - 1] -= 1
        min_struct[storage[idx]] += 1

    for i in range(len(min_struct)):
        if min_struct[i] > 0:
            ans_min = i
            break

    print(ans_min, ans_max)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    W = int(next(tokens))  # type: int
    H = int(next(tokens))  # type: int
    N = int(next(tokens))  # type: int
    p = [int()] * (N)  # type: "List[int]"
    q = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        p[i] = int(next(tokens))
        q[i] = int(next(tokens))
    A = int(next(tokens))  # type: int
    a = [int(next(tokens)) for _ in range(A)]  # type: "List[int]"
    B = int(next(tokens))  # type: int
    b = [int(next(tokens)) for _ in range(B)]  # type: "List[int]"
    solve(W, H, N, p, q, A, a, B, b)

if __name__ == '__main__':
    main()
