#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(S: str):
    if not S[0].isupper() or not S[-1].isupper():
        print(NO)
        return

    for i in range(1, len(S) - 1):
        if not S[i].isdigit():
            print(NO)
            return

    if len(S) - 2 != 6:
        print(NO)
        return

    if S[1] == "0":
        print(NO)
        return

    print(YES)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
