#!/usr/bin/env python3
import sys
from collections import defaultdict
INF = float('inf')  # type: float


def solve(H: int, W: int, A: "List[List[int]]"):

    ans = 0
    def dfs(ch=0, cw=0, visited=set()):
        nonlocal ans
        curr = A[ch][cw]
        if curr in visited:
            return

        if cw == W - 1 and ch == H - 1:
            ans += 1
            return

        curr_visited = visited.copy()
        curr_visited.add(curr)

        nh, nw = ch + 1, cw + 1
        if nh <= H - 1:
            dfs(nh, cw, curr_visited)
        if nw <= W - 1:
            dfs(ch, nw, curr_visited)

    dfs()
    print(ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    H = int(next(tokens))  # type: int
    W = int(next(tokens))  # type: int
    A = [[int(next(tokens)) for _ in range(W)] for _ in range(H)]  # type: "List[List[int]]"
    solve(H, W, A)

if __name__ == '__main__':
    main()
