#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1


def imos_2d(H: int, W: int, top: list[int], bot: list[int], left: list[int], right: list[int]) -> list[int]:
    field = [[0] * (W + 1) for _ in range(H + 1)]

    for (t, b, l, r) in zip(top, bot, left, right):
        b += 1
        r += 1

        field[t][l] += 1
        field[b][r] += 1
        field[t][r] -= 1
        field[b][l] -= 1

    for y in range(H + 1):
        for x in range(1, W + 1):
            field[y][x] += field[y][x - 1]

    for y in range(1, H + 1):
        for x in range(W + 1):
            field[y][x] += field[y - 1][x]

    return field


def kind_imos_2d(H: int, W: int, top: list[int], bot: list[int], left: list[int], right: list[int]) -> list[int]:
    field = [[0] * (H + 1) for _ in range(W + 1)]

    k = 1
    for (t, b, l, r) in zip(top, bot, left, right):
        b += 1
        r += 1

        field[t][l] += k
        field[b][r] += k
        field[t][r] -= k
        field[b][l] -= k
        k += 1

    for y in range(H + 1):
        for x in range(1, W + 1):
            field[y][x] += field[y][x - 1]

    for y in range(1, H + 1):
        for x in range(W + 1):
            field[y][x] += field[y - 1][x]

    return field


def solve(N: int, U: list[int], D: list[int], L: list[int], R: list[int]):
    s = 2000
    cloud_cnt = imos_2d(s, s, U, D, L, R)
    cloud_kind = kind_imos_2d(s, s, U, D, L, R)

    total = s * s
    all_cloud = 0
    k_cloud_cnt = {k: 0 for k in range(1, N + 1)}

    for y in range(s):
        for x in range(s):
            if cloud_cnt[y][x] > 0:
                all_cloud += 1
            
            if cloud_cnt[y][x] == 1:
                k = cloud_kind[y][x]
                k_cloud_cnt[k] += 1

    for k in range(1, N + 1):
        ans = total - (all_cloud - k_cloud_cnt[k])
        print(ans)


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    U = [int()] * (N)  # type: list[int]
    D = [int()] * (N)  # type: list[int]
    L = [int()] * (N)  # type: list[int]
    R = [int()] * (N)  # type: list[int]
    for i in range(N):
        U[i] = int(next(tokens)) - 1
        D[i] = int(next(tokens)) - 1
        L[i] = int(next(tokens)) - 1
        R[i] = int(next(tokens)) - 1
    solve(N, U, D, L, R)

if __name__ == '__main__':
    main()
