#!/usr/bin/env python3
import sys


def solve(N: int, S: "List[str]"):

    lon_cumsum = [[0] * (N + 1) for _ in range(N)]
    lat_cumsum = [[0] * (N + 1) for _ in range(N)]

    for i in range(N):
        for j in range(N):
            lon_cumsum[i][j + 1] = lon_cumsum[i][j]
            lat_cumsum[i][j + 1] = lat_cumsum[i][j]
            if S[i][j] == "o":
                lon_cumsum[i][j + 1] += 1
            if S[j][i] == "o":
                lat_cumsum[i][j + 1] += 1

    ans = 0
    for i in range(N):
        for j in range(N):
            if S[i][j] != "o":
                continue

            n_lon = lon_cumsum[i][-1] - lon_cumsum[i][0] - 1
            n_lat = lat_cumsum[j][-1] - lat_cumsum[j][0] - 1
            print((i, j), (n_lon, n_lat))
            ans += n_lon * n_lat

    print(ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = [next(tokens) for _ in range(N)]  # type: "List[str]"
    solve(N, S)

if __name__ == '__main__':
    main()
