#!/usr/bin/env python3
import sys


def solve(N: int, K: int, X: int, A: list[int]):
    A.sort(reverse=True)

    water_cnt = 0
    sake_cnt = 0
    sake_amount = 0
    for a in A:
        if water_cnt < N - K:
            water_cnt += 1
            continue
        
        sake_amount += a
        sake_cnt += 1
        if sake_amount >= X:
            print(water_cnt + sake_cnt)
            return
    
    print(-1)



# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    X = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: list[int]
    solve(N, K, X, A)

if __name__ == '__main__':
    main()
