#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    T = int(input())

    for _ in range(T):
        N, D = map(int, input().split())
        A = list(map(int, input().split()))
        B = list(map(int, input().split()))

        eggs = [0] * N
        used_idx = 0
        for idx, (a, b) in enumerate(zip(A, B)):
            if idx - D > used_idx:
                eggs[used_idx] = 0
                used_idx += 1
            
            eggs[idx] = a

            while b > 0:
                eggs[used_idx] -= b
                b = 0
                if eggs[used_idx] < 0:
                    b -= eggs[used_idx]
                    eggs[used_idx] = 0                    

                if eggs[used_idx] == 0:
                    used_idx += 1
        
        if N - D > used_idx:
            eggs[used_idx] = 0

        print(sum(eggs))


if __name__ == '__main__':
    main()
