#!/usr/bin/env python3
import sys
from collections import deque

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(N: int, M: int, A: "List[int]", B: "List[int]"):

    edges = [set() for _ in range(N)]

    for a, b in zip(A, B):
        a -= 1
        b -= 1
        edges[a].add(b)
        edges[b].add(a)

    used = [-1] * N

    for i in range(N):
        if used[i] != -1:
            continue

        # 0: node, 1: label
        que = deque()
        que.append((i, 0))

        while que:
            cur_i, cur_l = que.popleft()
            for nxt_i in edges[cur_i]:
                nxt_l = 1 - cur_l   # ラベル反転
                if used[nxt_i] == -1:
                    used[nxt_i] = nxt_l
                    que.append((nxt_i, nxt_l))
                elif used[nxt_i] != nxt_l:
                    print(NO)
                    return

    print(YES)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(M)]  # type: "List[int]"
    B = [int(next(tokens)) for _ in range(M)]  # type: "List[int]"
    solve(N, M, A, B)

if __name__ == '__main__':
    main()
