#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1


def check(n: int, base: int, ds: list[int]):    
    for i in range(n // 2):
        h, t = ds[i], ds[n - i - 1]
        if base != h + t:
            return False
    
    if n % 2 == 1:
        if base != ds[n // 2]:
            return False
    return True


def solve(N: int, A: list[int]):
    
    A.sort()

    ans = []

    # すべての棒が折れている場合のチェック
    v = A[0] + A[-1]
    if check(N, v, A):
        ans.append(v)

    # 一番長い棒が折れていない場合のチェック
    v = A[-1]
    while A and A[-1] == v:
        A.pop()
        N -= 1
    if check(N, v, A):
        ans.append(v)

    ans = sorted(ans)
    print(*ans)


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: list[int]
    solve(N, A)

if __name__ == '__main__':
    main()
