#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1


def solve(N: int, A: list[int]):
    
    A.sort()
    a_max = max(A)

    ans = set()

    v = A[0] + A[-1]
    is_ok = True
    for i in range(N // 2):
        h, t = A[i], A[N - i - 1]
        if v != h + t:
            is_ok = False
            break
    if N % 2 == 1:
        if v != A[N // 2]:
            is_ok = False
    if is_ok:
        ans.add(v)

    v = A[-1]
    while A and A[-1] == v:
        A.pop()
        N -= 1

    is_ok = True
    for i in range(N // 2):
        h, t = A[i], A[N - i - 1]
        if v != h + t:
            is_ok = False
            break
    if A and N % 2 == 1:
        if v != A[N // 2]:
            is_ok = False
    if is_ok:
        ans.add(v)

    ans = sorted(ans)
    print(*ans)


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: list[int]
    solve(N, A)

if __name__ == '__main__':
    main()
