#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(N: int, P: int, Q: int, R: int, A: "List[int]"):

    A_cumsum = [0] * N
    for i, a in enumerate(A):
        if i == 0:
            A_cumsum[i] = a
        A_cumsum[i] = A_cumsum[i - 1] + a

    """
    for i in range(1, N - 2):
        for j in range(i + 1, N - 1):
            calc_p = A_cumsum[i - 1]
            calc_q = A_cumsum[j - 1] - A_cumsum[i - 1]
            calc_r = A_cumsum[N - 1] - A_cumsum[j - 1]
            print((i, j), (calc_p, calc_q, calc_r))

            if calc_p == P and calc_q == Q and calc_r == R:
                print(YES)
                return
    """
    for x in range(N):
        if A_cumsum[-1] - A_cumsum[x] < P + Q + R:
            break
        for w in range(N - 1, -1, -1):
            if A_cumsum[w - 1] - A_cumsum[x] < P + Q + R:
                break

            if A_cumsum[w - 1] - A_cumsum[x] == P + Q + R:
                is_p = False
                for y in range(x + 1, w):
                    if A_cumsum[y] - A_cumsum[x] > P:
                        break
                    if A_cumsum[y] - A_cumsum[x] == P:
                        is_p = True
                        break
                if not is_p:
                    break

                is_q = False
                for z in range(y + 1, w):
                    if A_cumsum[z] - A_cumsum[y] > Q:
                        break
                    if A_cumsum[z] - A_cumsum[y] == Q:
                        is_q = True
                        break

                #print(x, y, z, w)
                #print(A_cumsum)
                #print(A_cumsum[x])
                #print(A_cumsum[y - 1] - A_cumsum[x])
                #print(A_cumsum[z - 1] - A_cumsum[y])
                #print(A_cumsum[w - 1] - A_cumsum[z])

                if not is_q:
                    break

                print(YES)
                return

    print(NO)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    P = int(next(tokens))  # type: int
    Q = int(next(tokens))  # type: int
    R = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, P, Q, R, A)

if __name__ == '__main__':
    main()
