#!/usr/bin/env python3


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    ans = []
    while True:
        v = int(input())
        ans.append(v)
        if v == 0:
            break
    ans = ans[::-1]
    for a in ans:
        print(a)


if __name__ == "__main__":
    main()
