#!/usr/bin/env python3
import sys
from collections import defaultdict
INF = float('inf')  # type: float


def solve(N: int, A: "List[str]"):

    A = [list(map(int, " ".join(a).split())) for a in A]

    pos_list = []
    for i in range(N):
        pos_list.append((i, 0))
    for i in range(1, N - 1):
        pos_list.append((N - 1, i))
    for i in range(N - 1, -1, -1):
        pos_list.append((i, N - 1))
    for i in range(N - 2, 0, -1):
        pos_list.append((0, i))

    pos_list = pos_list[::-1]
    x0, y0 = pos_list[0]
    a0 = A[y0][x0]
    for i in range(0, len(pos_list) - 1):
        x1, y1 = pos_list[i]
        x2, y2 = pos_list[i + 1]
        A[y1][x1] = A[y2][x2]

    xe, ye = pos_list[-1]
    A[ye][xe] = a0

    for a in A:
        print("".join(map(str, a)))


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [next(tokens) for _ in range(N)]  # type: "List[str]"
    solve(N, A)

if __name__ == '__main__':
    main()
