#!/usr/bin/env python3
import sys


def solve(N: int, X: "List[int]", Y: "List[int]", Z: "List[int]"):

    INF = float("INF")
    Z_CUM_MAX = sum(Z)

    dp = [[INF] * (Z_CUM_MAX + 1) for _ in range(N + 1)]
    dp[0][0] = 0

    for i in range(1, N + 1):
        for j in range(Z_CUM_MAX + 1):
            if dp[i - 1][j] == INF:
                continue

            num = Y[i - 1] - X[i - 1]
            if num >= 0:
                num = num // 2 + 1
            else:
                num = 0
            score = Z[i - 1]

            dp[i][j] = min(dp[i][j], dp[i - 1][j])
            if j + score <= Z_CUM_MAX:
                dp[i][j + score] = min(dp[i][j + score], dp[i - 1][j] + num)

    ans = INF
    for i in range(Z_CUM_MAX // 2 + 1, Z_CUM_MAX + 1):
        ans = min(ans, dp[N][i])

    print(ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    X = [int()] * (N)  # type: "List[int]"
    Y = [int()] * (N)  # type: "List[int]"
    Z = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        X[i] = int(next(tokens))
        Y[i] = int(next(tokens))
        Z[i] = int(next(tokens))
    solve(N, X, Y, Z)

if __name__ == '__main__':
    main()
