#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N, M = map(int, input().split())
    S = [input() for _ in range(N)]

    def get_subgrid(ci, cj):
        res = ""
        for di in range(M):
            for dj in range(M):
                res += S[ci + di][cj + dj]
        return res

    store = set()
    for i in range(N - M + 1):
        for j in range(N - M + 1):
            res = get_subgrid(i, j)
            if res not in store:
                store.add(res)

    print(len(store))


if __name__ == '__main__':
    main()
