#!/usr/bin/env python3
import sys

# コメントしてpypiなら通った！
#sys.setrecursionlimit(10 ** 8)


def solve(N: int, A: "List[List[int]]", M: int, X: "List[int]", Y: "List[int]"):

    fail_edges = [set() for _ in range(N)]
    for x, y in zip(X, Y):
        x, y = x - 1, y - 1
        fail_edges[x].add(y)
        fail_edges[y].add(x)

    edges = [[] for _ in range(N)]
    for i, edge in enumerate(fail_edges):
        for j in range(N):
            if i != j and j not in edge:
                edges[i].append(j)

    INF = float('INF')
    ans = INF


    def dfs(v, r, res):
        nonlocal ans
        if is_visit[v]:
            return
        is_visit[v] = True

        res += A[v][r]
        r += 1
        r %= N

        for n in edges[v]:
            dfs(n, r, res)

        if sum(is_visit) == N:
            ans = min(ans, res)

        is_visit[v] = False


    for i in range(N):
        is_visit = [False] * N
        dfs(i, 0, 0)

    if ans == INF:
        print(-1)
    else:
        print(ans)


    #for pattern in permutations(range(N), N):
    #    edges = [[] for _ in range()]


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [[int(next(tokens)) for _ in range(N)] for _ in range(N)]  # type: "List[List[int]]"
    M = int(next(tokens))  # type: int
    X = [int()] * (M)  # type: "List[int]"
    Y = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        X[i] = int(next(tokens))
        Y[i] = int(next(tokens))
    solve(N, A, M, X, Y)

if __name__ == '__main__':
    main()
