
#!/usr/bin/env python3
import sys
from itertools import permutations


def solve(N: int, A: "List[List[int]]", M: int, X: "List[int]", Y: "List[int]"):

    fail_edges = [set() for _ in range(N)]
    for x, y in zip(X, Y):
        x, y = x - 1, y - 1
        fail_edges[x].add(y)
        fail_edges[y].add(x)


    ans = 10 ** 6
    for pattern in permutations(range(N), N):
        res = 0
        prev_id = None
        for i, curr_id in enumerate(pattern):
            if (prev_id is not None) and (curr_id in fail_edges[prev_id]):
                res = None
                break
            res += A[curr_id][i]
            prev_id = curr_id

        if res is not None:
            ans = min(ans, res)


    if ans < 10 ** 6:
        print(ans)
    else:
        print(-1)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [[int(next(tokens)) for _ in range(N)] for _ in range(N)]  # type: "List[List[int]]"
    M = int(next(tokens))  # type: int
    X = [int()] * (M)  # type: "List[int]"
    Y = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        X[i] = int(next(tokens))
        Y[i] = int(next(tokens))
    solve(N, A, M, X, Y)

if __name__ == '__main__':
    main()
