#!/usr/bin/env python3
import sys

def solve_old(N: int):
    ans = 0
    square_set = set()

    for i in range(1, N + 1):
        ans += 1
        square_set.add(i ** 2)

    """
    #for i in range(N, 0, -1):
    for i in range(1, N + 1):
        if i in square_set:
            ans += 2
            num = i
            while True:
                num = int(math.sqrt(num)) * num
                if num in square_set:
                    ans += 2
                else:
                    break

        square_set.add(i ** 2)
        ans += 1
    """
    print(ans)


def solve(N: int):

    ans = 0
    for i in range(1, N + 1):

        k = i
        d = 2
        while d*d <= k:
            while k % (d*d) == 0:
                k /= (d*d)
            d += 1

        d = 1
        while k*d*d <= N:
            ans += 1
            d += 1

    print(ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
