#!/usr/bin/env python3


from collections import defaultdict

class UnionFind():

    def __init__(self, n, zero_index=False):
        self.n = n
        self.offset = 0 if zero_index else 1

        self.root = [-1] * (n + self.offset)

    def find(self, x):
        if self.root[x] < 0:
            return x
        else:
            # Path compression
            self.root[x] = self.find(self.root[x])
            return self.root[x]

    def unite(self, x, y):
        x = self.find(x)
        y = self.find(y)

        if x == y:
            return

        if self.root[x] > self.root[y]:
            x, y = y, x

        self.root[x] += self.root[y]
        self.root[y] = x

    def same(self, x, y):
        return self.find(x) == self.find(y)

    def roots(self):
        return [i for i, r in enumerate(self.root) if r < 0]

    def size(self, x):
        return -self.root[self.find(x)]

    def members(self, x):
        r = self.find(x)
        return [i + self.offset for i in range(self.n) if r == self.find(i + self.offset)]

    def group_size(self):
        return len(self.roots())

    def group_members(self):
        group = defaultdict(list)

        for i in range(self.n):
            i += self.offset
            group[self.find(i)].append(i)

        return group


YES = "Yes"  # type: str
NO = "No"  # type: str


# https://atcoder.jp/contests/typical90/tasks/typical90_l
# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    H, W = map(int, input().split())
    Q = int(input())

    n = H * W

    tree = UnionFind(n, True)
    is_paint = [False] * n

    move = [(0, 1), (1, 0), (0, -1), (-1, 0)]

    def index(r, c):
        return r * W + c

    for _ in range(Q):
        q = list(map(int, input().split()))

        if q[0] == 1:
            r, c = q[1:]
            r -= 1
            c -= 1
            idx_1 = index(r, c)

            for m in move:
                nr = r + m[0]
                nc = c + m[1]
                if nr < 0 or nc < 0 or nr >= H or nc >= W: continue

                idx_2 = index(nr, nc)
                if not is_paint[idx_2]: continue

                tree.unite(idx_1, idx_2)

            is_paint[idx_1] = True

        elif q[0] == 2:
            ra, ca, rb, cb = q[1:]
            ra -= 1
            ca -= 1
            rb -= 1
            cb -= 1
            idx_a = index(ra, ca)
            idx_b = index(rb, cb)
            if (not is_paint[idx_a]) or (not is_paint[idx_b]):
                print(NO)
            elif not tree.same(idx_a, idx_b):
                print(NO)
            else:
                print(YES)

if __name__ == '__main__':
    main()
