#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(S: str):

    X = ["A", "B", "C", None]

    cur = 0
    is_ok = True
    for c in S:
        while X[cur] != c:
            cur += 1
            if X[cur] is None:
                is_ok = False
                break
        if not is_ok:
            break
    if is_ok:
        print("Yes")
    else:
        print("No")


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
