#!/usr/bin/env python3
import sys
from collections import defaultdict
INF = float('inf')  # type: float


def solve(N: int, M: int, C: "List[str]", D: "List[str]", P: "List[int]"):

    dct = defaultdict(int)
    for i, d in enumerate(D):
        dct[d] = i + 1

    ans = 0
    for c in C:
        code = dct[c]
        ans += P[code]

    print(ans)




# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    C = [next(tokens) for _ in range(N)]  # type: "List[str]"
    D = [next(tokens) for _ in range(M)]  # type: "List[str]"
    P = [int(next(tokens)) for _ in range(M + 1)]  # type: "List[int]"
    solve(N, M, C, D, P)

if __name__ == '__main__':
    main()
