#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(Q: int, A: list[int]):
    state = 0
    volume = 0

    for a in A:
        if a == 1:
            volume += 1
        elif a == 2:
            volume = max(volume - 1, 0)
        else:
            state = (state + 1) % 2

        if state == 1 and volume >= 3:
            print(YES)
        else:
            print(NO)


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    Q = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(Q)]  # type: list[int]
    solve(Q, A)

if __name__ == '__main__':
    main()
