#!/usr/bin/env python3
import sys


def solve(N: int, K: int, h: "List[int]"):

    dp = [float('Inf')] * N

    dp[0] = 0
    for i in range(1, N):
        for k in range(1, K + 1):
            if i - k >= 0:
                dp[i] = min(dp[i], dp[i - k] + abs(h[i] - h[i - k]))

    print(dp[N - 1])




# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    h = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, K, h)

if __name__ == '__main__':
    main()
