#!/usr/bin/env python3

from math import sqrt


def first_prime_factorize(n):
    f = 2
    while f ** 3 <= n:
        if n % f == 0:
            return f
        else:
            f += 1
    return None


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N = int(input())
    test = [int(input()) for _ in range(N)]

    for t in test:
        prime = first_prime_factorize(t)

        if t % (prime ** 2) == 0:
            p = prime
            q = t // (prime ** 2)
        else:
            p = int(sqrt(t / prime))
            q = prime

        print(p, q)



if __name__ == '__main__':
    main()
