#!/usr/bin/env python3
import sys


def solve(N: int, A: list[int]):
    stack = []

    for a in A:
        if not stack:
            stack.append([a, 1])
        else:
            if stack[-1][0] == a:
                stack[-1][1] += 1
                if stack[-1][1] == 4:
                    stack.pop()
            else:
                stack.append([a, 1])

    ans = sum([a[1] for a in stack])
    print(ans)


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: list[int]
    solve(N, A)

if __name__ == '__main__':
    main()
