#!/usr/bin/env python3
import sys
sys.setrecursionlimit(10 ** 6)

MOD = 998244353  # type: int

from collections import defaultdict



def mod_div(a, b, m=MOD):
    return a * pow(b, m - 2, m) % m


class UnionFind:

    def __init__(self, n, zero_index=False):
        self.n = n
        self.offset = 0 if zero_index else 1

        self.root = [-1] * (n + self.offset)

    def find(self, x):
        if self.root[x] < 0:
            return x
        else:
            # Path compression
            self.root[x] = self.find(self.root[x])
            return self.root[x]

    def unite(self, x, y):
        x = self.find(x)
        y = self.find(y)

        if x == y:
            return

        if self.root[x] > self.root[y]:
            x, y = y, x

        self.root[x] += self.root[y]
        self.root[y] = x

    def same(self, x, y):
        return self.find(x) == self.find(y)

    def roots(self):
        return [i for i, r in enumerate(self.root) if r < 0]

    def size(self, x):
        return -self.root[self.find(x)]

    def members(self, x):
        r = self.find(x)
        return [i + self.offset for i in range(self.n) if r == self.find(i + self.offset)]

    def group_size(self):
        return len(self.roots())

    def group_members(self):
        group = defaultdict(list)

        for i in range(self.n):
            i += self.offset
            group[self.find(i)].append(i)

        return group


def solve(N, P, Q):

    uf = UnionFind(N)
    teams = [i for i in range(N)]

    edges = [[] for _ in range(2 * N - 1)]

    for i, (p, q) in enumerate(zip(P, Q)):
        p -= 1
        q -= 1

        p_r = uf.find(p)
        q_r = uf.find(q)

        p_s = uf.size(p)
        q_s = uf.size(q)

        p_prob = mod_div(p_s, (p_s + q_s) % MOD)
        q_prob = mod_div(q_s, (p_s + q_s) % MOD)

        edges[N + i].append((teams[p_r], p_prob))
        edges[N + i].append((teams[q_r], q_prob))

        uf.unite(p, q)
        teams[uf.find(p)] = N + i

    ans_list = [0] * N

    def dfs(cur, sum_prop=0):
        nonlocal ans_list
        if len(edges[cur]) == 0:
            ans_list[cur] = sum_prop
            return

        for nxt, prop in edges[cur]:
            dfs(nxt, (sum_prop + prop) % MOD)

    dfs(2 * N - 2)
    print(*ans_list)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    p = [int()] * (N - 1)  # type: "List[int]"
    q = [int()] * (N - 1)  # type: "List[int]"
    for i in range(N - 1):
        p[i] = int(next(tokens))
        q[i] = int(next(tokens))
    solve(N, p, q)

if __name__ == '__main__':
    main()
