#!/usr/bin/env python3
import sys


def solve(N: int, F: "List[int]", S: "List[int]"):

    data = {}
    for f in F:
        data[f] = [-1, -1]

    mul_f = []
    for f, s in zip(F, S):
        if data[f][0] == -1:
            data[f][0] = s
        elif data[f][1] == -1:
            data[f][1] = min(s, data[f][0])
            data[f][0] = max(s, data[f][0])
            mul_f.append(f)
        else:
            if s >= data[f][0]:
                data[f][1] = data[f][0]
                data[f][0] = s
            elif s >= data[f][1]:
                data[f][1] = s

    ans = 0
    for f in mul_f:
        ans = max(ans, data[f][0] + data[f][1] // 2)
        ans = max(ans, data[f][1] + data[f][0] // 2)

    rank1, rank2 = -1, -1
    for f in data.keys():
        if rank1 == -1:
            rank1 = data[f][0]
        elif rank2 == -1:
            rank2 = min(rank1, data[f][0])
            rank1 = max(rank1, data[f][0])
        else:
            if data[f][0] >= rank1:
                rank2 = rank1
                rank1 = data[f][0]
            elif data[f][0] >= rank2:
                rank2 = data[f][0]

    ans = max(ans, rank1 + rank2)
    print(ans)

# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    F = [int()] * (N)  # type: "List[int]"
    S = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        F[i] = int(next(tokens))
        S[i] = int(next(tokens))
    solve(N, F, S)

if __name__ == '__main__':
    main()
