#!/usr/bin/env python3
import sys


def solve(N: int):

    divisor = [i for i in range(1, 10) if N % i == 0]

    ans = ""
    for num in range(0, N + 1):
        if_ok = False
        for div in divisor:
            m = N // div
            if num % m == 0:
                ans += str(div)
                if_ok = True
                break
        if not if_ok:
            ans += "-"
    print(ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
