#!/usr/bin/env python3
import sys

INF = float('inf')

def solve(N: int, h: "List[int]"):

    dp = [INF] * N
    dp[0] = 0

    for i in range(1, N):
        dp[i] = dp[i - 1] + abs(h[i] - h[i - 1])
        if i - 2 >= 0:
            dp[i] = min(dp[i], dp[i - 2] + abs(h[i] - h[i - 2]))

    print(dp[N - 1])



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    h = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, h)

if __name__ == '__main__':
    main()
