#!/usr/bin/env python3

# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    line = input()
    ans = 0
    for s in line:
        ans += int(s)
    print(ans)

if __name__ == '__main__':
    main()
