#!/usr/bin/env python3
import sys


def solve(N: int, L: int, K: int, A: "List[int]"):

    left = 0
    right = L

    while right > left + 1:

        mid = (right + left) // 2
        offset = 0
        cnt = 0
        for n in range(N):
            if (mid <= A[n] - offset) and (L - A[n]) >= mid:
                offset = A[n]
                cnt += 1

        if cnt >= K:
            left = mid
        else:
            right = mid

    print(left)





# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    L = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, L, K, A)

if __name__ == '__main__':
    main()
