#!/usr/bin/env python3
import sys


def solve(N: int, A: int, B: int, S: str):

    ans = N // 2 * B

    for n in range(N):

        n_b = N // 2
        for c in range(N // 2):
            i = c + n
            if i >= N: i -= N

            j = (N - 1) - c + n
            if j >= N: j -= N

            if S[i] == S[j]:
                n_b -= 1

        ans = min(ans, n * A + n_b * B)


    print(ans)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    solve(N, A, B, S)

if __name__ == '__main__':
    main()
