#!/usr/bin/env python3
import sys


def solve(H: int, W: int):

    if H == 1:
        bh = 1
        bw = W
    elif W == 1:
        bh = H
        bw = 1
    else:
        bh = H // 2 + H % 2
        bw = W // 2 + W % 2

    print(bh * bw)




# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    H = int(next(tokens))  # type: int
    W = int(next(tokens))  # type: int
    solve(H, W)

if __name__ == '__main__':
    main()
