#!/usr/bin/env python3
import sys


def solve(N: int, M: int, X: int, T: int, D: int):

    if M >= X:
        print(T)
    else:
        print(T - (X - M)*D)




# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    X = int(next(tokens))  # type: int
    T = int(next(tokens))  # type: int
    D = int(next(tokens))  # type: int
    solve(N, M, X, T, D)

if __name__ == '__main__':
    main()
