#!/usr/bin/env python3
import sys
from collections import defaultdict
INF = float('inf')  # type: float


def solve(N: int, X: "List[int]", Y: "List[int]"):

    # 0:健康,1:毒状態
    dp = [[-INF, -INF] for _ in range(N + 1)]
    dp[0][0] = 0

    for i, (x, y) in enumerate(zip(X, Y)):
        dp[i + 1][0] = dp[i][0]
        dp[i + 1][1] = dp[i][1]

        if x == 0:
            dp[i + 1][0] = max(dp[i + 1][0], dp[i][0] + y)
            dp[i + 1][0] = max(dp[i + 1][0], dp[i][1] + y)
        else:
            dp[i + 1][1] = max(dp[i + 1][1], dp[i][0] + y)

    print(max(dp[N]))


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    X = [int()] * (N)  # type: "List[int]"
    Y = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        X[i] = int(next(tokens))
        Y[i] = int(next(tokens))
    solve(N, X, Y)

if __name__ == '__main__':
    main()
