#!/usr/bin/env python3
import sys


def solve(L: int, R: int):

    def calc(r):
        def calc_i(r):
            i = 0
            while r % 2 == 0:
                i += 1
                r //= 2
            return i

        def calc_lj(i, r):
            v = pow(2, i)
            j = r // v - 1
            l = v * j
            return l, j

        i = calc_i(r)
        l, j = calc_lj(i, r)


        while l < L:
            i -= 1
            l, j = calc_lj(i, r)

        return l

    ans = []
    r = R
    while r > L:
        n_r = calc(r)
        ans.append([n_r, r])
        r = n_r

    print(len(ans))
    for a in ans[::-1]:
        print(*a)


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    L = int(next(tokens))  # type: int
    R = int(next(tokens))  # type: int
    solve(L, R)

if __name__ == '__main__':
    main()
