#!/usr/bin/env python3

YES = "Yes"  # type: str
NO = "No"  # type: str


def check(H, a_list, b_list):
    for h in range(H):
        if a_list[h] != b_list[h]:
            return False
    return True

# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    # Failed to predict input format
    H, W = map(int, input().split())
    a_list = [input() for _ in range(H)]
    b_list = [input() for _ in range(H)]

    for cnt_h in range(H):

        tmp = b_list[0]
        for i in range(1, H):
            b_list[i - 1] = b_list[i]
        b_list[-1] = tmp

        for cnt_w in range(W):
            for i in range(H):
                tmp = b_list[i][0]
                b_list[i] = b_list[i][1:] + tmp

            if check(H, a_list, b_list):
                print(YES)
                return

    print(NO)



if __name__ == '__main__':
    main()
