#!/usr/bin/env python3
import sys


def solve(N: int, A: "List[int]"):

    A = [0] + A
    b = [0] * (N + 1)
    for i in range(1, N + 1):
        b[i] = b[i - 1] + A[(i + 1) // 2]

    dp = [[-float("INF")] * (N + 1) for _ in range(N + 1)]

    dp[1][0] = 0
    for i in range(1, N):
        for j in range(N):
            if dp[i][j] < 0: continue
            dp[i + 1][j + 1] = max(dp[i + 1][j + 1], dp[i][j])
            dp[i + 1][0] = max(dp[i + 1][0], dp[i][j] + b[j])

    ans = 0
    for i in range(N):
        ans = max(ans, dp[N][i] + b[i])
    print(ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, A)

if __name__ == '__main__':
    main()
