#!/usr/bin/env python3
import sys


def n_to_dec(n, base):
    ret = 0
    cnt = 0
    while n:
        mod = n % 10
        ret += (base ** cnt) * mod
        n //= 10
        cnt += 1
    return ret

def dec_to_n(n, base):
    ret = 0
    cnt = 0
    while n:
        mod = n % base
        ret += mod * (10 ** cnt)
        n //= base
        cnt += 1
    return ret

def solve(N: int, K: int):

    for _ in range(K):
        dec = n_to_dec(N, 8)
        nine = dec_to_n(dec, 9)
        ans = str(nine).replace("8", "5")
        N = int(ans)
    print(ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    solve(N, K)

if __name__ == '__main__':
    main()
