#!/usr/bin/env python3
import sys
from collections import defaultdict


def solve(N: int, M: int, X: "List[int]", C: "List[int]", Y: "List[int]"):

    bornus_list = [[c, y, 0] for c, y in zip(C, Y)]
    bornus_list.sort()
    for i in range(1, M):
        bornus_list[i][1] += bornus_list[i - 1][1]
    for i in range(M):
        bornus_list[i][2] = bornus_list[i][1] / bornus_list[i][0]
    bornus_list.sort(reverse=True, key=lambda x: x[2])

    bornus_dict = defaultdict(int)
    for c, y in zip(C, Y):
        bornus_dict[c] = y


    ans = 0
    counter = 0

    for n in range(N):

        for m in range(M):
            tmp = bornus_list[m]
            if tmp[0] + n < N:
                break
        else:
            ans += X[n]
            counter += 1
            ans += bornus_dict[counter]
            continue

        if counter >= tmp[0]:
            if X[n] < tmp[2]:
                counter = 0
            else:
                ans += X[n]
                counter += 1
                ans += bornus_dict[counter]
        else:
            ans += X[n]
            counter += 1
            ans += bornus_dict[counter]

    print(ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    X = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    C = [int()] * (M)  # type: "List[int]"
    Y = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        C[i] = int(next(tokens))
        Y[i] = int(next(tokens))
    solve(N, M, X, C, Y)

if __name__ == '__main__':
    main()
