#!/usr/bin/env python3
import sys
from collections import defaultdict


def solve(N: int, M: int, X: "List[int]", C: "List[int]", Y: "List[int]"):

    X = [0] + X
    dp = [[-float('INF')] * (N + 1) for _ in range((N + 1))]

    bornus = defaultdict(int)
    for c, y in zip(C, Y):
        bornus[c] = y


    dp[0][0] = 0
    for i in range(1, N + 1):
        for j in range(1, i + 1):
            dp[i][j] = dp[i-1][j-1] + X[i] + bornus[j]

        dp[i][0] = 0
        for j in range(i):
            dp[i][0] = max(dp[i][0], dp[i - 1][j])


    ans = max(dp[-1])
    print(ans)


    #for a in dp:
    #    print(a)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    X = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    C = [int()] * (M)  # type: "List[int]"
    Y = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        C[i] = int(next(tokens))
        Y[i] = int(next(tokens))
    solve(N, M, X, C, Y)

if __name__ == '__main__':
    main()
