#!/usr/bin/env python3
import sys


def solve(N: int, P: "List[List[int]]", R: "List[List[int]]", D: "List[List[int]]"):
    return


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    P = [[int(next(tokens)) for _ in range(N)] for _ in range(N)]  # type: "List[List[int]]"
    R = [[int(next(tokens)) for _ in range(N - 1)] for _ in range(N)]  # type: "List[List[int]]"
    D = [[int(next(tokens)) for _ in range(N)] for _ in range(N - 1)]  # type: "List[List[int]]"
    solve(N, P, R, D)

if __name__ == '__main__':
    main()
