#!/usr/bin/env python3
import sys


def solve(N: int, X: int, A: "List[int]", B: "List[int]"):

    ans = float('Inf')
    cumsum_a_b = 0
    count = 1
    for a, b in zip(A, B):
        cumsum_a_b += (a + b)
        score = cumsum_a_b + b*(X - count)
        if score <= 0: continue
        ans = min(ans, score)
        count += 1

    print(ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    X = int(next(tokens))  # type: int
    A = [int()] * (N)  # type: "List[int]"
    B = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        A[i] = int(next(tokens))
        B[i] = int(next(tokens))
    solve(N, X, A, B)

if __name__ == '__main__':
    main()
