#!/usr/bin/env python3
import sys
from collections import defaultdict

def solve(N: int, S: str):

    d = defaultdict(int)
    ps = None
    cnt = 0
    for s in S:
        if ps != s:
            if ps is not None:
                d[ps] = max(d[ps], cnt)
            ps = s
            cnt = 1
        else:
            cnt += 1

    d[ps] = max(d[ps], cnt)
    print(sum([n for n in d.values()]))


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    solve(N, S)

if __name__ == '__main__':
    main()
