"""
K = 10
N_MAX = 111111111
[N%9 == 0 and sum(N)%K == 0]

ans = [9の表現数]^[9で割ったときの商]
9の表現数は再起関数で求める。

111111111 : 1
21111111 : 8
3111111  : 7
...
9,

n! / (p! * q! * r! * ...)

"""

#!/usr/bin/env python3
import sys
sys.setrecursionlimit(10 ** 8)

MOD = 1000000007  # type: int


def solve(K: int):

    if K % 9 != 0:
        print(0)
        return

    dp = [0] * (K + 1)
    dp[0] = 1

    for i in range(1, K + 1):
        b = min(i, 9)
        for j in range(1, b + 1):
            dp[i] += dp[i - j]
            dp[i] %= MOD
    print(dp[K])







# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    K = int(next(tokens))  # type: int
    solve(K)

if __name__ == '__main__':
    main()
