#!/usr/bin/env python3
import sys

MOD = 2  # type: int


def solve(N: int, X: "List[int]", Y: "List[int]", Q: int, G: "List[int]", R_a: int, R_b: int):
    return


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    X = [int()] * (N)  # type: "List[int]"
    Y = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        X[i] = int(next(tokens))
        Y[i] = int(next(tokens))
    Q = int(next(tokens))  # type: int
    G = [int(next(tokens)) for _ in range(0 + 1)]  # type: "List[int]"
    R_a = int(next(tokens))  # type: int
    R_b = int(next(tokens))  # type: int
    solve(N, X, Y, Q, G, R_a, R_b)

if __name__ == '__main__':
    main()
