#!/usr/bin/env python3
import sys


def solve(K: int):
    h = K // 60
    m = K % 60

    h_str = str(21 + h)
    m_str = str(m)
    if len(m_str) == 1:
        m_str = '0' + m_str

    print(f'{h_str}:{m_str}')


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    K = int(next(tokens))  # type: int
    solve(K)

if __name__ == '__main__':
    main()
