#!/usr/bin/env python3

YES = "Yes"  # type: str
NO = "No"  # type: str


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N = int(input())
    A_list = list(map(int, input().split()))
    M = int(input())
    tmm_B_list = list(map(int, input().split()))
    X = int(input())

    B_list = [False] * (X + 1)
    for b in tmm_B_list:
        B_list[b] = True

    dp = [False] * (X + 1)
    dp[0] = True

    for i in range(1, X + 1):
        if B_list[i]: continue

        for a in A_list:
            if i - a < 0: continue
            if B_list[i - a]: continue
            dp[i] = dp[i] | dp[i - a]

    if dp[X]: print(YES)
    else: print(NO)


if __name__ == '__main__':
    main()
