#!/usr/bin/env python3
import sys

INF = float("INF")


def solve(X: int, Y: int, Z: int, S: str):

    datas = []
    S += "-"
    cs = S[0]
    cnt = 0
    for s in S:
        if cs == s:
            cnt += 1
        else:
            datas.append([cs, cnt])
            cs = s
            cnt = 1

    n_datas = len(datas)
    # 0: cap off
    # 1: cap on
    dp = [[INF, INF] for _ in range(n_datas + 1)]
    dp[0][0] = 0

    for i in range(n_datas):
        for j in range(2):

            state = datas[i][0]
            cnt = datas[i][1]

            # cap off
            if j == 0:
                if state == "a":
                    dp[i + 1][0] = min(dp[i + 1][0], dp[i][0] + X * cnt)
                    dp[i + 1][1] = min(dp[i + 1][1], dp[i][0] + Y * cnt + Z)
                else:
                    dp[i + 1][0] = min(dp[i + 1][0], dp[i][0] + Y * cnt)
                    dp[i + 1][1] = min(dp[i + 1][1], dp[i][0] + X * cnt + Z)
            # cap on
            else:
                if state == "A":
                    dp[i + 1][1] = min(dp[i + 1][1], dp[i][1] + X * cnt)
                    dp[i + 1][0] = min(dp[i + 1][0], dp[i][1] + Y * cnt + Z)
                else:
                    dp[i + 1][1] = min(dp[i + 1][1], dp[i][1] + Y * cnt)
                    dp[i + 1][0] = min(dp[i + 1][0], dp[i][1] + X * cnt + Z)

    print(min(dp[-1]))


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    X = int(next(tokens))  # type: int
    Y = int(next(tokens))  # type: int
    Z = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    solve(X, Y, Z, S)

if __name__ == '__main__':
    main()
