#!/usr/bin/env python3
import sys


def solve(N: int, M: int, A: "List[int]"):

    votes = [0] * (N + 1)

    prev_win = -1
    prev_max = 0

    for curr_vote in A:
        votes[curr_vote] += 1
        if prev_win == -1:
            prev_win = curr_vote
            prev_max = votes[curr_vote]
        elif votes[curr_vote] > prev_max:
            prev_win = curr_vote
            prev_max = votes[curr_vote]
        elif votes[curr_vote] == prev_max and prev_win > curr_vote:
            prev_win = curr_vote
            prev_max = votes[curr_vote]

        print(prev_win)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(M)]  # type: "List[int]"
    solve(N, M, A)

if __name__ == '__main__':
    main()
