#!/usr/bin/env python3
from collections import deque

INF = float("INF")

# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    H, W = map(int, input().split())
    rs, cs = map(int, input().split())
    rt, ct = map(int, input().split())

    rs -= 1
    cs -= 1
    rt -= 1
    ct -= 1

    field = []
    dir_cnt = []
    for _ in range(H):
        line = input()
        field.append(line)
        for c in line:
            if c != "#":
                dir_cnt.extend([INF] * 4)
            else:
                dir_cnt.extend([-1] * 4)

    idx = lambda r, c, d: (r * W + c) * 4 + d

    deq = deque()

    move = [(-1, 0), (1, 0), (0, -1), (0, 1)]
    for d in range(4):
        dir_cnt[idx(rs, cs, d)] = 0
        deq.append((rs, cs, d))

    while deq:
        curr_r, curr_c, curr_dir = deq.popleft()
        curr_cost = dir_cnt[idx(curr_r, curr_c, curr_dir)]

        for d, m in enumerate(move):
            next_r = curr_r + m[0]
            next_c = curr_c + m[1]

            if not (0 <= next_r < H and 0 <= next_c < W):
                continue

            if field[next_r][next_c] == "#":
                continue
            if d == curr_dir:
                cost = curr_cost
                if dir_cnt[idx(next_r, next_c, d)] > cost:
                    dir_cnt[idx(next_r, next_c, d)] = cost
                    deq.appendleft((next_r, next_c, d))
            else:
                cost = curr_cost + 1
                if dir_cnt[idx(next_r, next_c, d)] > cost:
                    dir_cnt[idx(next_r, next_c, d)] = cost
                    deq.append((next_r, next_c, d))

    ans = INF
    for d in range(4):
        ans = min(ans, dir_cnt[idx(rt, ct, d)])

    print(ans)

if __name__ == '__main__':
    main()
