#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1


"""
Aをソート。
A最小 * Y が W の候補となる。
A最小以外は、W の候補となるようにYをXに分配する
-> W の候補を X - Y するだけ Y のあめを X のあめに交換できる
-> 交換するあめがない場合は-1
"""


def solve(N: int, X: int, Y: int, A: list[int]):
    A.sort()

    n_y = [0] * N
    w = A[0] * Y

    n_y[0] = A[0]
    d_yx = Y - X

    for i, a in enumerate(A):
        if i == 0: continue
        curr_w = a * Y

        d_w = curr_w - w

        # 交換しても重さの帳尻が合わない場合
        if d_w % d_yx != 0:
            print(-1)
            return

        chg_x = d_w // d_yx

        # 交換するあめが足りない場合
        if chg_x > a:
            print(-1)
            return
        
        n_y[i] = a - chg_x

    print(sum(n_y))


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    X = int(next(tokens))  # type: int
    Y = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: list[int]
    solve(N, X, Y, A)

if __name__ == '__main__':
    main()
