#!/usr/bin/env python3
import sys
from bisect import bisect_left

def solve(N: int, M: int, A: "List[int]", B: "List[int]"):

    edges = [[] for _ in range(N)]
    for a, b in zip(A, B):
        a -= 1
        b -= 1
        edges[a].append(b)
        edges[b].append(a)

    ans = 0
    for i in range(N):
        edges[i].sort()
        ind = bisect_left(edges[i], i)
        if ind == 1:
            ans += 1
    print(ans)




# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    a = [int()] * (M)  # type: "List[int]"
    b = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        a[i] = int(next(tokens))
        b[i] = int(next(tokens))
    solve(N, M, a, b)

if __name__ == '__main__':
    main()
