#!/usr/bin/env python3
import sys
from collections import defaultdict

def solve(N: int, A: "List[int]"):

    def square_divide(v):
        div = 2
        while div ** 2 <= v:
            while v % (div ** 2) == 0:
                v //= (div ** 2)
            div += 1
        return v

    ans = 0
    store = defaultdict(int)
    for a in A:
        c = square_divide(a)
        ans += store[c]
        store[c] += 1
    ans += store[0] * (N - store[0])
    print(ans)


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, A)

if __name__ == '__main__':
    main()
