#!/usr/bin/env python3
import sys


def solve(N: int, X: int, P: "List[int]", B: "List[int]", W: "List[int]", C: "List[int]"):
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    X = int(next(tokens))  # type: int
    P = [int(next(tokens)) for _ in range(N - 2 + 1)]  # type: "List[int]"
    B = [int()] * (N)  # type: "List[int]"
    W = [int()] * (N)  # type: "List[int]"
    C = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        B[i] = int(next(tokens))
        W[i] = int(next(tokens))
        C[i] = int(next(tokens))
    solve(N, X, P, B, W, C)

if __name__ == '__main__':
    main()
