#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(S: str, T: str):

    i_s = 0
    i_t = 0
    nS = len(S)
    nT = len(T)

    while i_t < nT and i_s < nS:
        if S[i_s] == T[i_t]:
            p_value = T[i_t]

            t_cnt = 0
            while True:
                i_t += 1
                if i_t >= nT:
                    break
                if p_value != T[i_t]:
                    break
                t_cnt += 1

            s_cnt = 0
            while True:
                i_s += 1
                if i_s >= nS:
                    break
                if p_value != S[i_s]:
                    break
                s_cnt += 1

            if s_cnt == 0 and t_cnt > 0:
                print(NO)
                return
            if s_cnt > 0 and t_cnt == 0:
                print(NO)
                return
            if t_cnt < s_cnt:
                print(NO)
                return

        else:
            print(NO)
            return

    if i_t >= nT and i_s >= nS:
        print(YES)
    else:
        print(NO)






# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    T = next(tokens)  # type: str
    solve(S, T)

if __name__ == '__main__':
    main()
