#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


"""
abbaac
abbbbaaaC
"""


def solve(S: str, T: str):

    n_S = S[0]
    count = 0
    for i in range(1, len(S)):
        if n_S[-1] == S[i]:
            if count == 0:
                n_S += S[i]
                count = 1
        else:
            n_S += S[i]
            count = 0

    n_T = T[0]
    count = 0
    for i in range(1, len(T)):
        if n_T[-1] == T[i]:
            if count == 0:
                n_T += T[i]
                count = 1
        else:
            n_T += T[i]
            count = 0

    if n_S == n_T:
        print(YES)
    else:
        print(NO)






# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    T = next(tokens)  # type: str
    solve(S, T)

if __name__ == '__main__':
    main()
