#!/usr/bin/env python3
import sys
sys.setrecursionlimit(10 ** 9)


def solve(N: int, M: int, A: "List[int]", B: "List[int]", C: "List[int]"):

    edges = [[] for _ in range(N)]
    for a, b, c in zip(A, B, C):
        a -= 1
        b -= 1
        edges[a].append((b, c))
        edges[b].append((a, c))

    max_cost = 0
    visited = [False] * N

    def dfs(cur, sum_cost=0):
        nonlocal max_cost, visited

        max_cost = max(max_cost, sum_cost)
        visited[cur] = True
        for nxt, cost in edges[cur]:
            if not visited[nxt]:
                dfs(nxt, sum_cost + cost)
        visited[cur] = False

    for start in range(N):
        dfs(start)

    print(max_cost)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    A = [int()] * (M)  # type: "List[int]"
    B = [int()] * (M)  # type: "List[int]"
    C = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        A[i] = int(next(tokens))
        B[i] = int(next(tokens))
        C[i] = int(next(tokens))
    solve(N, M, A, B, C)

if __name__ == '__main__':
    main()
