#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    X = int(input())
    N = int(input())
    W = list(map(int, input().split()))
    Q = int(input())
    P = [int(input()) - 1 for _ in range(Q)]

    parts = set()
    weight = X
    for p in P:
        if p not in parts:
            parts.add(p)
            weight += W[p]
        else:
            parts.remove(p)
            weight -= W[p]
        
        print(weight)


if __name__ == '__main__':
    main()
