#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(V: "List[int]"):

    GRID = 7

    def check(a1, b1, c1, a2, b2, c2, a3, b3, c3):
        grid = [[[0] * (GRID * 2 + 1) for _ in range(GRID * 2 + 1)] for _ in range(GRID * 2 + 1)]

        def fill(a, b, c):
            nonlocal grid
            for i in range(a, a + 7):
                for j in range(b, b + 7):
                    for k in range(c, c + 7):
                        grid[i][j][k] += 1

        fill(a1, b1, c1)
        fill(a2, b2, c2)
        fill(a3, b3, c3)

        v_cnt = [0, 0, 0]
        for rect in grid:
            for box in rect:
                for cell in box:
                    if cell > 0:
                        v_cnt[cell - 1]

        return V == v_cnt

    a1, b1, c1 = 0, 0, 0
    for a2 in range(GRID + 1):
        for b2 in range(GRID + 1):
            for c2 in range(GRID + 1):

                """
                tmp_a = GRID - a2
                tmp_b = GRID - b2
                tmp_c = GRID - c2

                tmp_v2 = tmp_a * tmp_b * tmp_c
                if V[2] > tmp_v2:
                    continue
                if (GRID ** 3) * 3 - tmp_v2 < V[0]:
                    continue
                """

                for a3 in range(GRID + 1):
                    for b3 in range(GRID + 1):
                        for c3 in range(GRID + 1):
                            pass
                            if check(a1, b1, c1, a2, b2, c2, a3, b3, c3):
                                print(YES)
                                print(a1, b1, c1, a2, b2, c2, a3, b3, c3)
                                return

    print(NO)



# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    V = [int(next(tokens)) for _ in range(3)]  # type: "List[int]"
    solve(V)

if __name__ == '__main__':
    main()
