#!/usr/bin/env python3
import sys
import math
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1

def cumsum_1d(data: list[int]) -> list[int]:
    n = len(data)
    cumsum_data = [0] * (n + 1)
    for i in range(n):
        cumsum_data[i + 1] = data[i] + cumsum_data[i]
    return cumsum_data


def solve(N: int, Q: int, X: list[int], Y: list[int], A: list[int], B: list[int]):

    def calc_degree(x, y):
        rad = math.atan2(y, x)
        deg = rad * 180 / math.pi
        if deg < 0:
            deg += 360
        if int(deg * 10 ** 9) != 0:
            deg = 360 - deg
        return deg
    
    degrees = [calc_degree(x, y) for x, y in zip(X, Y)]
    sort_idx = sorted(list(range(N)), key=lambda x: degrees[x])

    cnt_idx_map = [None] * N

    cnt_idx = -1
    cnt_sum = []
    c_deg = float("INF")
    for idx in sort_idx:
        deg = degrees[idx]

        if math.isclose(c_deg, deg, rel_tol=1e-18):
            cnt_sum[cnt_idx] += 1
        else:
            c_deg = deg
            cnt_idx += 1
            cnt_sum.append(0)
            cnt_sum[cnt_idx] += 1

        cnt_idx_map[idx] = cnt_idx

    cnt_cumsum = cumsum_1d(cnt_sum)

#    print(cnt_sum)
#    print(cnt_cumsum)
#    print(id_map)

    for a, b in zip(A, B):
        a -= 1
        b -= 1
        
        a_idx = cnt_idx_map[a]
        b_idx = cnt_idx_map[b]

        if a_idx <= b_idx:
            ans = cnt_cumsum[b_idx + 1] - cnt_cumsum[a_idx]
        else:
            ans = (cnt_cumsum[-1] - cnt_cumsum[a_idx]) + cnt_cumsum[b_idx + 1]
        
        print(ans)


    return


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    Q = int(next(tokens))  # type: int
    X = [int()] * (N)  # type: list[int]
    Y = [int()] * (N)  # type: list[int]
    for i in range(N):
        X[i] = int(next(tokens))
        Y[i] = int(next(tokens))
    A = [int()] * (Q)  # type: list[int]
    B = [int()] * (Q)  # type: list[int]
    for i in range(Q):
        A[i] = int(next(tokens))
        B[i] = int(next(tokens))
    solve(N, Q, X, Y, A, B)

if __name__ == '__main__':
    main()
