#!/usr/bin/env python3
import sys
import numpy as np
from dataclasses import dataclass
# from atcoder import dsu
# from bisect import bisect_left
# from collections import defaultdict
# from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1


def cumsum_1d(data: list[int]) -> list[int]:
    n = len(data)
    cumsum_data = [0] * (n + 1)
    for i in range(n):
        cumsum_data[i + 1] = data[i] + cumsum_data[i]
    return cumsum_data


@dataclass
class Vector2d:
    x: int
    y: int


def solve(N: int, Q: int, X: list[int], Y: list[int], A: list[int], B: list[int]):

    pts = []
    for idx, (x, y) in enumerate(zip(X, Y)):
        pt = Vector2d(x, y)
        # 時計回りのため、x,yは逆にする
        pt.arg = np.atan2(np.float128(x), np.float128(y))
        pt.prev_idx = idx
        pts.append(pt)

    pts.sort(key=lambda pt: pt.arg)
    
#    for pt in pts:
#        print(f"[x: {pt.x}, y: {pt.y}, arg: {pt.arg}, prev_idx: {pt.prev_idx}]")

    cnt_idx_map = [None] * N

    cnt_idx = -1
    cnt_sum = []

    c_pt = None
    for idx, pt in enumerate(pts):
        if (c_pt is not None) and (c_pt.arg == pt.arg):
            cnt_sum[cnt_idx] += 1
        else:
            c_pt = pt
            cnt_idx += 1
            cnt_sum.append(0)
            cnt_sum[cnt_idx] += 1

        cnt_idx_map[pt.prev_idx] = cnt_idx
    
    cnt_cumsum = cumsum_1d(cnt_sum)

#    print(cnt_sum)
#    print(cnt_cumsum)
#    print(cnt_idx_map)

    for a, b in zip(A, B):
        a -= 1
        b -= 1
        
        a_idx = cnt_idx_map[a]
        b_idx = cnt_idx_map[b]

#        print((a, b), (a_idx, b_idx))
        
        if a_idx <= b_idx:
            ans = cnt_cumsum[b_idx + 1] - cnt_cumsum[a_idx]
        else:
            ans = (cnt_cumsum[-1] - cnt_cumsum[a_idx]) + cnt_cumsum[b_idx + 1]
        
        print(ans)


    return


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    Q = int(next(tokens))  # type: int
    X = [int()] * (N)  # type: list[int]
    Y = [int()] * (N)  # type: list[int]
    for i in range(N):
        X[i] = int(next(tokens))
        Y[i] = int(next(tokens))
    A = [int()] * (Q)  # type: list[int]
    B = [int()] * (Q)  # type: list[int]
    for i in range(Q):
        A[i] = int(next(tokens))
        B[i] = int(next(tokens))
    solve(N, Q, X, Y, A, B)

if __name__ == '__main__':
    main()
