#!/usr/bin/env python3
import sys
import math
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1

def cumsum_1d(data: list[int]) -> list[int]:
    n = len(data)
    cumsum_data = [0] * (n + 1)
    for i in range(n):
        cumsum_data[i + 1] = data[i] + cumsum_data[i]
    return cumsum_data


from functools import cmp_to_key
from collections import namedtuple
vector2d = namedtuple("vector2d", ["x", "y", "idx"])


def cross_product(pt1: vector2d, pt2: vector2d):
    cross_product = pt1.x * pt2.y - pt1.y * pt2.x
    if cross_product > 0:
        return 1
    elif cross_product < 0:
        return -1
    else:
        return 0


def arg_cmp(pt1: vector2d, pt2: vector2d) -> int:
    # [0 < deg <= 180度] か [180 < deg <= 360度] かを判定 
    is_pt1_lower = pt1.y < 0 or (pt1.y == 0 and pt1.x < 0)
    is_pt2_lower = pt2.y < 0 or (pt2.y == 0 and pt2.x < 0)

    # 片方だけ [180 < deg <= 360度] に存在する場合、それがpt2であれば1を返す 
    if is_pt1_lower != is_pt2_lower:
        return 1 if is_pt2_lower else -1
    
    # 同じ場合は、外積を計算して判断
    return cross_product(pt1, pt2)


def sorted_argument(pts: list[vector2d]) -> list[vector2d]:
    return sorted(pts, key=cmp_to_key(arg_cmp))


def solve(N: int, Q: int, X: list[int], Y: list[int], A: list[int], B: list[int]):

    pts = [vector2d(x, y, idx) for idx, (x, y) in enumerate(zip(X, Y))]
    pts = sorted_argument(pts)
#    print(pts)

    cnt_idx_map = [None] * N

    cnt_idx = -1
    cnt_sum = []

    c_pt = None
    for idx, pt in enumerate(pts):
        if (c_pt is not None) and (arg_cmp(c_pt, pt) == 0):
            cnt_sum[cnt_idx] += 1
        else:
            c_pt = pt
            cnt_idx += 1
            cnt_sum.append(0)
            cnt_sum[cnt_idx] += 1

        cnt_idx_map[pt.idx] = cnt_idx
    
    cnt_cumsum = cumsum_1d(cnt_sum)

#    print(cnt_sum)
#    print(cnt_cumsum)
#    print(cnt_idx_map)

    for a, b in zip(A, B):
        a -= 1
        b -= 1
        
        a_idx = cnt_idx_map[a]
        b_idx = cnt_idx_map[b]

        if a_idx <= b_idx:
            ans = cnt_cumsum[b_idx + 1] - cnt_cumsum[a_idx]
        else:
            ans = (cnt_cumsum[-1] - cnt_cumsum[a_idx]) + cnt_cumsum[b_idx + 1]
            #ans = None
        
        # print((a, b), (a_idx, b_idx),  ans)
        print(ans)


    return


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    Q = int(next(tokens))  # type: int
    X = [int()] * (N)  # type: list[int]
    Y = [int()] * (N)  # type: list[int]
    for i in range(N):
        X[i] = int(next(tokens))
        Y[i] = int(next(tokens))
    A = [int()] * (Q)  # type: list[int]
    B = [int()] * (Q)  # type: list[int]
    for i in range(Q):
        A[i] = int(next(tokens))
        B[i] = int(next(tokens))
    solve(N, Q, X, Y, A, B)

if __name__ == '__main__':
    main()
