#!/usr/bin/env python3
import sys

from heapq import heappop, heappush

def dijkstra(edges, n_node, start):
    dist = [float('Inf')] * n_node
    used = [False] * n_node

    route = [float('Inf')] * n_node

    dist[start] = 0
    used[start] = True
    queue = [(dist[start], start)]

    while queue:
        _, now = heappop(queue)
        used[now] = True
        for next, weight in edges[now]:
            if (not used[next]) and (dist[now] + weight < dist[next]):
                dist[next] = dist[now] + weight
                route[next] = now
                heappush(queue, (dist[next], next))
    return dist, route


def solve(N: int, X: int, Y: int, U: "List[int]", V: "List[int]"):

    edges = [[] for _ in range(N + 1)]
    for u, v in zip(U, V):
        edges[u].append((v, 1))
        edges[v].append((u, 1))

    dist, route = dijkstra(edges, N + 1, X)

    idx = Y
    ans = [idx]
    while idx != X:
        idx = route[idx]
        ans.append(idx)

    ans.reverse()
    print(*ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    X = int(next(tokens))  # type: int
    Y = int(next(tokens))  # type: int
    U = [int()] * (N - 1)  # type: "List[int]"
    V = [int()] * (N - 1)  # type: "List[int]"
    for i in range(N - 1):
        U[i] = int(next(tokens))
        V[i] = int(next(tokens))
    solve(N, X, Y, U, V)

if __name__ == '__main__':
    main()
