#!/usr/bin/env python3
import sys
import bisect


def solve(N: int, M: int, A: "List[int]"):

    INF = float("INF")
    A.sort()
    A.append(INF)

    lp, li = 0, 0
    rp, ri = 0, 0

    curr = 0
    ans = 0

    def shift(p, i, is_right):
        nonlocal curr, ans
        while p >= A[i]:
            if is_right:
                curr += 1
            else:
                curr -= 1
            i += 1
            ans = max(ans, curr)
        p += 1
        return p, i

    while rp < M:
        rp, ri = shift(rp, ri, True)

    while A[li] != INF and A[ri] != INF:
        lp, li = shift(lp, li, False)
        rp, ri = shift(rp, ri, True)

    print(ans)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, M, A)

if __name__ == '__main__':
    main()
