#!/usr/bin/env python3
import sys
from itertools import permutations


def solve(N: int, M: int, S: "List[str]", T: "List[str]"):

    t_set = set(T)

    def collect(p, idx, name):
        n_name = len(name)
        if n_name > 16:
            return

        if idx == N:
            if n_name >= 3 and (name not in t_set):
                print(name)
                sys.exit(1)
        else:
            if idx == 0:
                collect(p, idx + 1, S[idx])
            else:
                collect(p, idx + 1, f"{name}_{S[idx]}")
                collect(p, idx, f"{name}_")

    for p in permutations(S, N):
        collect(p, 0, "")

    print(-1)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    S = [next(tokens) for _ in range(N)]  # type: "List[str]"
    T = [next(tokens) for _ in range(M)]  # type: "List[str]"
    solve(N, M, S, T)

if __name__ == '__main__':
    main()
