#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():

    T = int(input())

    def solve():
        N = int(input())
        DATA = [list(map(int, input().split())) for _ in range(N)]

        p_sum = sum([p for _, p in DATA])
        wp_list = [w + p for w, p in DATA]
        wp_list.sort()

        wp_sum = 0
        cnt = 0
        for wp in wp_list:
            wp_sum += wp
            if p_sum < wp_sum:
                continue
            cnt += 1

        print(cnt)



    for _ in range(T):
        solve()
        

if __name__ == '__main__':
    main()
