#!/usr/bin/env python3
import sys
from collections import defaultdict

def solve(N: int, T: int, C: "List[int]", R: "List[int]"):

    cr_value_dict = defaultdict(int)
    cr_idx_dict = defaultdict(int)
    for i, (c, r) in enumerate(zip(C, R)):
        if cr_value_dict[c] < r:
            cr_value_dict[c] = r
            cr_idx_dict[c] = i + 1

    if cr_value_dict[T] > 0:
        print(cr_idx_dict[T])
    else:
        print(cr_idx_dict[C[0]])



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    T = int(next(tokens))  # type: int
    C = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    R = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, T, C, R)

if __name__ == '__main__':
    main()
