#!/usr/bin/env python3


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    h, w = map(int, input().split())
    field = [list(input()) for _ in range(h)]

    def dfs(i, j, pi=-1, pj=-1, score=0):
        nonlocal si, sj, visited

        if not (0 <= i < h and 0 <= j < w):
            return -1
        if visited[i][j]:
            return -1

        if si == i and sj == j:
            if score > 0:
                return score
        else:
            visited[i][j] = True

        ret = -1
        for m in [(0, 1), (0, -1), (1, 0), (-1, 0)]:
            ni, nj = i + m[0], j + m[1]
            if pi == ni and pj == nj:
                continue
            ret = max(ret, dfs(ni, nj, i, j, score + 1))

        visited[i][j] = False
        return ret

    ans = -1
    for i in range(h):
        for j in range(w):
            si, sj = i, j
            visited = [[False if c == "." else True for c in line] for line in field]
            ans = max(ans, dfs(i, j))

    print(ans)


if __name__ == '__main__':
    main()
