#!/usr/bin/env python3
import sys
from collections import defaultdict


MOD = 46

def solve(N: int, A: "List[int]", B: "List[int]", C: "List[int]"):

    a_cnt = defaultdict(int)
    b_cnt = defaultdict(int)
    c_cnt = defaultdict(int)

    for a, b, c in zip(A, B, C):
        a_cnt[a % MOD] += 1
        b_cnt[b % MOD] += 1
        c_cnt[c % MOD] += 1


    ans = 0
    for i in range(MOD):
        for j in range(MOD):
            k = (MOD - i - j) % MOD
            ans += a_cnt[i] * b_cnt[j] * c_cnt[k]

    print(ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    B = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    C = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, A, B, C)

if __name__ == '__main__':
    main()
