#!/usr/bin/env python3
import sys
from collections import defaultdict

MOD = 998244353  # type: int
INF = float('inf')  # type: float


def arg_cast(func):
    def wrapper(*args):
        s, n = args
        if not isinstance(s, ModInt): s = ModInt(s)
        if not isinstance(n, ModInt): n = ModInt(n)
        return func(s, n)
    return wrapper

class ModInt:
    def __init__(self, x): self.x = x % MOD
    def __str__(self): return str(self.x)
    @arg_cast
    def __add__(self, n): return ModInt(self.x + n.x)
    @arg_cast
    def __sub__(self, n): return ModInt(self.x - n.x)
    @arg_cast
    def __rsub__(self, n): return ModInt(n.x - self.x)
    @arg_cast
    def __mul__(self, n): return ModInt(self.x * n.x)
    @arg_cast
    def __pow__(self, n): return ModInt(pow(self.x, n.x, MOD))
    @arg_cast
    def __rpow__(self, n): return ModInt(pow(n.x, self.x, MOD))
    @arg_cast
    def __truediv__(self, n): return ModInt(self.x * pow(n.x, MOD - 2, MOD))
    @arg_cast
    def __rtruediv__(self, n): return ModInt(n.x * pow(self.x, MOD - 2, MOD))
    __repr__ = __str__
    __radd__ = __add__
    __rmul__ = __mul__
    __floordiv__ = __truediv__
    __rfloordiv__ = __rtruediv__


def solve(N: int, A: int, B: int, P: int, Q: int):

    dp = [[[0] * 2  for _ in range(N + 1)] for _ in range(N + 1)]

    for i in range(N):
        dp[N][i][0] = ModInt(1)
        dp[N][i][1] = ModInt(1)

    for i in range(N-1, -1, -1):
        for j in range(N-1, -1, -1):
            for k in range(1, P + 1):
                dp[i][j][0] += dp[min(i + k, N)][j][1]
            dp[i][j][0] //= P

            for k in range(1, Q + 1):
                dp[i][j][1] += dp[i][min(j + k, N)][0]
            dp[i][j][1] //= Q

    print(dp[A][B][0])


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    P = int(next(tokens))  # type: int
    Q = int(next(tokens))  # type: int
    solve(N, A, B, P, Q)

if __name__ == '__main__':
    main()
