#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    s, a, b, x = map(int, input().split())

    t = 0
    ans = 0
    while True:
        ans += s * a
        t += a
        if t >= x:
            ans -= s * (t - x)
            break

        t += b
        if t >= x:
            break
    
    print(ans)


if __name__ == '__main__':
    main()
