#!/usr/bin/env python3
import sys


def solve(N: int, X: int, Y: int, Z: int, A: "List[int]", B: "List[int]"):

    T = [a + b for a, b in zip(A, B)]

    a_list = [(a, i + 1) for i, a in enumerate(A)]
    b_list = [(a, i + 1) for i, a in enumerate(B)]
    t_list = [(a, i + 1) for i, a in enumerate(T)]

    a_list.sort()
    b_list.sort()
    t_list.sort()
    a_list.sort(key=lambda x: x[0], reverse=True)
    b_list.sort(key=lambda x: x[0], reverse=True)
    t_list.sort(key=lambda x: x[0], reverse=True)

    ans_set = set()
    for i in range(X):
        ans_set.add(a_list[i][1])

    cnt = 0
    for i in range(len(B)):
        if cnt >= Y:
            break
        if b_list[i][1] not in ans_set:
            ans_set.add(b_list[i][1])
            cnt += 1
    cnt = 0
    for i in range(len(T)):
        if cnt >= Z:
            break
        if t_list[i][1] not in ans_set:
            ans_set.add(t_list[i][1])
            cnt += 1

    ans = sorted(ans_set)
    for a in ans:
        print(a)






# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    X = int(next(tokens))  # type: int
    Y = int(next(tokens))  # type: int
    Z = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    B = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, X, Y, Z, A, B)

if __name__ == '__main__':
    main()
