#!/usr/bin/env python3
import sys

from bisect import bisect_right, bisect_left


def solve(N: int, M: int, A: "List[int]", B: "List[int]"):
    
    A.sort()
    B.sort()

    left, right = min(A[0], B[0]) - 1, max(A[-1], B[-1]) + 1

    while left + 1 < right:
        mid = (left + right) // 2
        
        n_a = bisect_right(A, mid)
        n_b = len(B) - bisect_left(B, mid)
        #print(((left, mid, right), n_a, n_b))

        if n_a >= n_b:
            right = mid
        else:
            left = mid

    print(right)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    B = [int(next(tokens)) for _ in range(M)]  # type: "List[int]"
    solve(N, M, A, B)

if __name__ == '__main__':
    main()
