#!/usr/bin/env python3
import sys
from collections import defaultdict

YES = "Yes"  # type: str
NO = "No"  # type: str

def solve(N: int, S: "List[str]", T: "List[str]"):

    is_visit = defaultdict(int)
    pair_dict = {s: t for s, t in zip(S, T)}

    change_char_set = set()

    cnt = 0
    for k, v in pair_dict.items():

        if is_visit[k]: continue
        cnt += 1
        is_visit[k] = cnt
        swap_k = v

        while swap_k in pair_dict:
            if is_visit[swap_k] == cnt:
                print(NO)
                return
            elif is_visit[swap_k] > 0:
                break
            is_visit[swap_k] = cnt
            swap_k = pair_dict[swap_k]

        if swap_k in change_char_set:
            print(NO)
            return

        change_char_set.add(swap_k)

    print(YES)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = [str()] * (N)  # type: "List[str]"
    T = [str()] * (N)  # type: "List[str]"
    for i in range(N):
        S[i] = next(tokens)
        T[i] = next(tokens)
    solve(N, S, T)

if __name__ == '__main__':
    main()
