#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1

YES = "Yes"  # type: str
NO = "No"  # type: str


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    q = int(input())

    values = [0]

    def solve():
        query = input().split()
        if query[0] == "1":
            c = query[1]
            last_v = values[-1]
            if last_v < 0:
                values.append(-1)
            else:
                dv = 1 if c == "(" else -1
                values.append(last_v + dv)
        else:
            values.pop()
        
        return values[-1]

    
    for _ in range(q):
        v = solve()
        if v == 0:
            print(YES)
        else:
            print(NO)


if __name__ == '__main__':
    main()
