#!/usr/bin/env python3
import sys
from math import sqrt

def solve(N: int, P: "List[int]"):

    INF = -float("INF")

    RP = P[::-1]
    nume_list = []
    rate = 1
    for _ in range(N):
        nume_list.append(rate)
        rate *= 0.9

    # 0: k, 1: p
    dp_deno = [[INF] * N for _ in range(N)]
    dp_nume = [[INF] * N for _ in range(N)]
    dp_k = [[INF] * N for _ in range(N)]

    for i in range(N):
        dp_deno[0][i] = P[i]
        dp_nume[0][i] = 1
        dp_k[0][i] = 1

    def calc(nume, deno, k):
        if nume == INF or deno == INF or k == INF: return INF
        return (deno / nume) - (1200 / sqrt(k))

    for ip in range(N):
        for ik in range(1, N):
            # 選ばない場合
            update = calc(dp_nume[ik - 1][ip], dp_deno[ik - 1][ip], dp_k[ik - 1][ip])
            through = calc(dp_nume[ip][ik], dp_deno[ip][ik], dp_k[ik][ip])
            if update > through:
                dp_deno[ik][ip] = dp_deno[ik - 1][ip]
                dp_nume[ik][ip] = dp_nume[ik - 1][ip]
                dp_k[ik][ip] = dp_k[ik - 1][ip]

            # 選ぶ場合
            if ip != 0:
                k = dp_k[ik - 1][ip - 1] + 1
                nume = dp_nume[ik - 1][ip - 1] + nume_list[k - 1]
                deno = dp_deno[ik - 1][ip - 1] + nume_list[k - 1] * RP[ip]
                update = calc(nume, deno, k)
                through = calc(dp_nume[ik][ip], dp_deno[ik][ip], dp_k[ik][ip])

                print()
                print((dp_deno[ik - 1][ip - 1], dp_nume[ik - 1][ip - 1], nume_list[k - 1]), [RP[ip],])
                print((deno, nume, k, update, [update > through,]))

                if update > through:
                    dp_deno[ip][ik] = deno
                    dp_nume[ip][ik] = nume
                    dp_k[ip][ik] = k

    print(dp_deno)
    print(dp_nume)
    print(dp_k)

    ans = INF
    for nume, deno, k in zip(dp_nume[-1], dp_deno[-1], dp_k[-1]):
        ans = max(ans, calc(nume, deno, k))
    print(ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    P = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, P)

if __name__ == '__main__':
    main()
