#!/usr/bin/env python3
import sys

from collections import defaultdict


def solve(N: int, S: "List[str]"):

    cnt_dict = defaultdict(int)

    for s in S:
        if s not in cnt_dict:
            print(s)
            cnt_dict[s] += 1
        else:
            print(f'{s}({cnt_dict[s]})')
            cnt_dict[s] += 1



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = [next(tokens) for _ in range(N)]  # type: "List[str]"
    solve(N, S)

if __name__ == '__main__':
    main()
