#!/usr/bin/env python3
import sys
import math


def solve(a: int, b: int, d: int):
    theta = d * math.pi / 180
    na = a * math.cos(theta) - b * math.sin(theta)
    nb = a * math.sin(theta) + b * math.cos(theta)

    print(f'{na} {nb}')




# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    a = int(next(tokens))  # type: int
    b = int(next(tokens))  # type: int
    d = int(next(tokens))  # type: int
    solve(a, b, d)

if __name__ == '__main__':
    main()
