#!/usr/bin/env python3
import sys


def SOE(N):
    prime_list = [i for i in range(N + 1)]
    prime_list[1] = 0

    n_search_max = int(N ** 0.5)

    for i in range(2, n_search_max + 1):
        if not prime_list[i]: continue

        for j in range(i**2, N + 1, i):
            prime_list[j] = 0

    prime_set = set(prime_list)
    prime_set.remove(0)
    return prime_set


def solve(N: int):

    primes = list(SOE(int(N ** 0.5)))
    primes.sort()
    n_prime = len(primes)

    ans = 0
    for i in range(1, n_prime - 1):
        b = primes[i]
        if b > N:
            break
        for j in range(0, i):
            a = primes[j]

            if (a ** 2) * b > N:
                break

            for k in range(i + 1, n_prime):
                c = primes[k]
                if (a ** 2) * b * (c ** 2) > N:
                    break
                ans += 1

    print(ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
