#!/usr/bin/env python3
import sys
sys.setrecursionlimit(10 ** 8)

def solve(N: int, M: int, A: "List[int]", B: "List[int]"):

    graph = [[] for _ in range(N)]
    for a, b in zip(A, B):
        a, b = a - 1, b - 1
        graph[a].append(b)
        graph[b].append(a)

    is_visit = [False] * N

    def dfs(i):
        nonlocal is_visit
        nonlocal count

        for n in graph[i]:
            if not is_visit[n]:
                is_visit[n] = True
                dfs(n)

    count = 0
    for i, flag in enumerate(is_visit):
        if not flag:
            dfs(i)
            count += 1

    print(M - N + count)






# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    A = [int()] * (M)  # type: "List[int]"
    B = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        A[i] = int(next(tokens))
        B[i] = int(next(tokens))
    solve(N, M, A, B)

if __name__ == '__main__':
    main()
