#!/usr/bin/env python3
import sys
sys.setrecursionlimit(10 * 8)


def scan():
    return list(map(int, input().split()))[1:]

# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N, M = map(int, input().split())

    visited = [False] * (N + 1)
    visited[1] = True

    def dfs(c_p, p_p):

        if c_p == N:
            input()
            sys.exit()

        for n_p in scan():
            if visited[n_p]: continue
            visited[n_p] = True
            print(n_p)
            dfs(n_p, c_p)

        print(p_p)
        scan()

    dfs(1, 1)


if __name__ == '__main__':
    main()
