#!/usr/bin/env python3


def solve(H, W, G):
    is_visits = [[False] * (W + 2) for _ in range(H + 2)]

    curr_i, curr_j = 1, 1
    prev_i, prev_j = 1, 1
    curr_mass = G[curr_i][curr_j]


    while curr_mass != '':

        is_visits[curr_i][curr_j] = True
        prev_i = curr_i
        prev_j = curr_j

        if curr_mass == 'U':
            curr_i -= 1
        elif curr_mass == 'D':
            curr_i += 1
        elif curr_mass == 'L':
            curr_j -= 1
        elif curr_mass == 'R':
            curr_j += 1

        curr_mass = G[curr_i][curr_j]

        if is_visits[curr_i][curr_j]:
            print(-1)
            return

    print(prev_i, prev_j)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    H, W = map(int, input().split())

    G = [[''] * (W + 2) for _ in range(H + 2)]

    for i in range(H):
        tmp = input()
        for j in range(W):
            G[i + 1][j + 1] = tmp[j]

    solve(H, W, G)


if __name__ == '__main__':
    main()
