#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1
MOVE = [(0, 0), (1, 0), (0, 1), (1, 1)]

def solve(N: int, M: int, R: list[int], C: list[int]):
    put = set()
    
    ans = 0
    for r, c in zip(R, C):
        def check():
            for mr, mc in MOVE:
                nr, nc = r + mr, c + mc
                if (nr, nc) in put:
                    return False
            return True

        if check():
            for mr, mc in MOVE:
                nr, nc = r + mr, c + mc
                put.add((nr, nc))
            ans += 1
    print(ans)



# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    R = [int()] * (M)  # type: list[int]
    C = [int()] * (M)  # type: list[int]
    for i in range(M):
        R[i] = int(next(tokens))
        C[i] = int(next(tokens))
    solve(N, M, R, C)

if __name__ == '__main__':
    main()
