#!/usr/bin/env python3
import sys
sys.setrecursionlimit(10 ** 8)


def solve(N: int, M: int, A: "List[int]", B: "List[int]"):

    is_visit_1 = [False] * N
    is_visit_2 = [False] * N
    depth_ranks = []
    node_count = 0

    edge_first = [[] for _ in range(N)]
    edge_second = [[] for _ in range(N)]
    for a, b in zip(A, B):
        a -= 1
        b -= 1
        edge_first[a].append(b)
        edge_second[b].append(a)

    def dfs_first(p):
        if is_visit_1[p]:
            return

        is_visit_1[p] = True

        for i in edge_first[p]:
            dfs_first(i)
        depth_ranks.append(p)

    def dfs_second(p):
        nonlocal node_count
        if is_visit_2[p]:
            return

        is_visit_2[p] = True
        node_count += 1

        for i in edge_second[p]:
            dfs_second(i)


    for i in range(N):
        dfs_first(i)

    depth_ranks.reverse()

    ans = 0
    for i in depth_ranks:
        node_count = 0
        dfs_second(i)
        ans += node_count * (node_count - 1) // 2

    print(ans)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    A = [int()] * (M)  # type: "List[int]"
    B = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        A[i] = int(next(tokens))
        B[i] = int(next(tokens))
    solve(N, M, A, B)

if __name__ == '__main__':
    main()
