#!/usr/bin/env python3
import sys
from itertools import permutations

def solve(M: int, S: "List[str]"):

    set_s = [set(s) for s in S]
    correct_s = (set_s[0] & set_s[1] & set_s[2])
    if len(correct_s) == 0:
        print(-1)
        return

    ans = float("INF")
    for ts in "0123456789":

        is_ok = True
        for c in range(3):
            if ts not in set_s[c]:
                is_ok = False
                break
        if not is_ok:
            continue

        for pattern in permutations([0, 1, 2]):
            n_fix = 0
            t = 0
            idx = 0
            while True:
                c = pattern[idx]
                if S[c][t % M] == ts:
                    n_fix += 1
                    idx += 1
                if n_fix >= 3:
                    break
                t += 1
            ans = min(ans, t)

    print(ans)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    M = int(next(tokens))  # type: int
    S = [next(tokens) for _ in range(3)]  # type: "List[str]"
    solve(M, S)

if __name__ == '__main__':
    main()
