"""
i0: 1 2 3 4 5 6
i1: 1 2 3 4 5 6
i2: 1 2 3 4 5 6

1*1 + 1*2 + 1*3 + ...

  1 * (1 + 2 + 3 + ...)
+ 2 * (1 + 2 + 3 + ...)
+ 3 * (1 + 2 + 3 + ...)
+ 4 * (1 + 2 + 3 + ...)

1*1*1 + 1*1*2 + ... + 1*2*1 + 1*2*2 + ...

1 * (1*1 + 1*2 + ... + 2*1 + 2*2 + ...)

1 * {1 * (1 + 2 + ...) + 2 * (1 + 2 + ...)}

1 * {(1 + 2 + ...) * (1 + 2 + ...)}

"""

#!/usr/bin/env python3
import sys

MOD = 1000000007  # type: int


def solve(N: int, A: "List[List[int]]"):

    a_sum = [sum(a) for a in A]

    ans = 1
    for a in a_sum:
        ans *= a
        ans %= MOD

    print(ans)



# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [[int(next(tokens)) for _ in range(6)] for _ in range(N)]  # type: "List[List[int]]"
    solve(N, A)

if __name__ == '__main__':
    main()
