#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    H, W, Q = map(int, input().split())
    
    for _ in range(Q):
        ans = 0
        k, v = map(int, input().split())
        if k == 1:
            ans = (v * W)
            H -= v
        else:
            ans = (v * H)
            W -= v
    
        print(ans)


if __name__ == '__main__':
    main()
