#!/usr/bin/env python3
import sys

MOD = 998244353  # type: int


from functools import reduce
def comb(n, r):
    r = min(r, n - r)
    numer = reduce(lambda x, y: x * y, range(n, n - r, -1), 1)
    denom = reduce(lambda x, y: x * y, range(1, r + 1), 1)
    return numer // denom


def solve(N: int, A: "List[int]"):

    ans = N
    """
    for i in range(2, N):
        cnt = 0
        for a in A:
            if a % i == 0:
    """


    ans = 0
    for i in range(1, 100):
        ans += comb(100, i)

    print(ans)
    print(comb(100, 50))


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    a = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, a)

if __name__ == '__main__':
    main()
