#!/usr/bin/env python3
import sys
from atcoder import dsu
from bisect import bisect_left
from collections import defaultdict
from collections import deque
# import pypyjit
# pypyjit.set_param(inlining=0)     # or pypyjit.set_param('max_unroll_recursion=-1')

sys.setrecursionlimit(10 ** 6)

INF = 2 ** 64 - 1

# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N, M = map(int, input().split())
    U, V = [], []
    for _ in range(M):
        u, v = map(int, input().split())
        U.append(u - 1)
        V.append(v - 1)
    

    def solve(bit):
        res = 0
        for u, v in zip(U, V):
            uc = (bit >> u) & 1
            vc = (bit >> v) & 1
            if uc == vc:
                res += 1
        return res
    
    ans = INF
    for i in range(2 ** N):
        ans = min(ans, solve(i))
    
    print(ans)
 


if __name__ == '__main__':
    main()
